### ISSUE TITLE
Suggestions menu and autocomplete for mathematics symbols

### ISSUE THREAD

**Issue by AymaneHrouch** [marktext/marktext#3056] opened 2022-02-21 08:40 UTC
Math symbols are so many and overwhelming, can we have at least a suggestions menu that pops up when we press tab after typing "\\" for example. 
A small icon of the symbol would be great but I think just a suggestions menu would help a lot.

**Comment by YalandHong** [comment] 2022-02-24 00:22
Duplicate of #724

**Closed** 2022-02-24 11:05 UTC
