### ISSUE TITLE
Improve performance for large files

### ISSUE THREAD

**Issue by littlecatheart** [marktext/marktext#2092] opened 2020-05-01 15:32 UTC
When I open a file (1000-5000 lines) with about 50% code; the editing becomes very slow if I insert text in the first line. However, when I edit it inTypora, it's very fast. Do we have plan to optimize the performance?

**Comment by littlecatheart** [comment] 2020-05-01 15:38
I think the render algorithm is different. Does TextMart render the whole page even I just change one line? To improve performance, could we just cache the views of other blocks and only update the current block?

**Comment by fxha** [comment] 2020-05-21 10:57
Thank you for reporting the issue. We noticed that this is a duplicate of #511 and #1648. You may want to subscribe there for further updates.

**Closed by fxha** 2020-05-21 10:57 UTC
