### ISSUE TITLE
Support CriticMarkup

### ISSUE THREAD

**Issue by xgouchet** [marktext/marktext#1965] opened 2020-03-05 16:14 UTC
### Describe your feature request

Add support for the CriticMarkup syntax.

#### Syntax

```markdown
You can insert {++addition++} suggestions, or suggest {--unnecessary--} removals. 
The syntax also supports 
 - {~~substitions~>substitutions~~}, 
 - {==highlighting a portion of the text==}, 
 - or simply adding a comment {>>remind me to update this<<}.
```

### What problem does this feature solve?

CriticMarkup allows providing edit/comments when reviewing a Markdown document. 

### Additional context [optional]

The Addition, removal and substitution syntax is even handled by GitHub ;)

**Comment by fxha** [comment] 2020-06-07 00:44
Thank you for taking the time to report this issue. We noticed that this might be a duplicate of #954 (inline diff) but currently don't plan to implement this feature. We may reopen it on demand.

**Closed by fxha** 2020-06-07 00:44 UTC

**Comment by Mpic** [comment] 2020-06-09 15:43
GFM would help, but it is not the same as CriticMarkup (which is made for document reviewing). I am interested in support of this markup :-)
