### ISSUE TITLE
The last few lines of the page may be lost when exporting to pdf, 导出为pdf时可能会丢失页面底端内容

### ISSUE THREAD

**Issue by iquykumo** [marktext/marktext#3593] opened 2023-03-10 08:35 UTC
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. This is my source code
  
  ```markag-0-1gr59h3suag-1-1gr59h3su
  ## 数值分析 作业1
  
  ##### 习题
  
  **P13. 4.** 设$x\gt 0$，$x$的相对误差是$\delta$，求$lnx$的绝对误差。
  
  > $$
  > \begin{aligned}
  > & \because x > 0,  e_r(x)=\delta=
  > { x - x^* \over x }=1-{x^*\over x} \\
  > & \therefore e(lnx) = lnx-(lnx)^*=lnx-ln(x^*)=ln({x\over x^*})
  >  = ln({1\over 1-\delta})
  > \end{aligned}
  > $$
  
  **P13. 7.** 正方形的边长为$100cm$，问测量边长时误差应多大，才能保证给面积达误差不超过$1cm^2$？
  
  > $$
  > \begin{aligned}
  > & \because S(x)=x^2, e(S)=S'(x^*)\cdot e(x^*)=
  > 2x^*\cdot e(x^*)  \\
  > & \therefore 要使得S(x)\le1, 即e(x^*)=
  > { S(x) \over 2x^* }\le{1\over200} \\
  > \end{aligned}
  > $$
  
  **P13. 9.** 设$s={1\over 2}gt^2$，假定g是准确的，而对t的测量有$\pm0.1s$的误差，试证明当t增大时，s的绝对误差增大而相对误差减小。
  
  > $$
  > \begin{aligned}
  > & \because e(S)=S'(t^*)\cdot e(t^*) = 0.1gt^*, 
  > e_r(S) = {e(S)\over S^*} = {0.1gt^*\over {1\over 2}gt^{*2}}
  > ={0.2g \over t^*} \\
  > & \therefore 当t增加时，S的绝对误差增大，相对误差减小 \\
  > \end{aligned}
  > $$
  
  **P13. 10.** 已知$\sqrt{783} \approx 27.983$有5位有效数字，试求方程$x^2-56x+1=0$的两个根，使它们至少有四位有效数字。
  
  > $$
  > \begin{aligned}
  > & 由求根公式得，x={ 56\pm \sqrt{56^2-4} \over 2}=28-\sqrt{783}\\
  > & 代入\sqrt{783}\approx27.983，并保留4位有效数字得\\
  > & x_1=28+\sqrt{783}=55.98, \\
  > & x_2=28-\sqrt{783}={28^2-(\sqrt{783})^2 \over 28+\sqrt{783}}
  >  = {1\over28+\sqrt{783}}=0.01786\\
  > \end{aligned}
  > $$
  
  **P13. 12.** 试改变下列表达式，使计算结果比较精确：
  
  $(1)\ {1\over 1+2x}-{1-x \over 1+x},|x|\ll 1\\ $
  $(2)\ sqrt{x+{1\over x}}-\sqrt{x-{1\over x}},|x|\gg 1$
  $(3)\ {tanx-sinx\over x^2},|x|\ll1且x\ne0$
  
  > $$
  > \begin{aligned}
  > & (1){1\over 1+2x}-{1-x \over 1+x} ={(1+x)-(1-x)(1+2x)\over(1+x)(1+2x)}
  > ={2x^2\over (1+2x)(1+x)}\\
  > & (2)\sqrt{x+{1\over x}}-\sqrt{x-{1\over x}}=
  > \sqrt{x^2+1\over x}-\sqrt{x^2-1\over x}=
  > {\sqrt{x^2+1}-\sqrt{x^2-1}\over \sqrt x}\\
  > & \qquad= {2 \over \sqrt x (\sqrt{x^2+1}+\sqrt{x^2-1})} \\
  > & (3){tanx-sinx\over x^2}=
  > {sinx(1-cosx)\over cosx\cdot x^2 } = { tanx({sin^2{x\over 2 }+
  > {cos^2{x\over 2 }}-(2{cos^2{x\over2}-1})}) \over x^2 } \\
  > & \qquad = {{sinx(sin^2{x\over 2}+1-cos^2{x\over 2})}\over x^2}
  > ={2tanx\cdot sin^2{x\over 2}\over x^2}  \\
  > \end{aligned}
  > $$
  ```

2. and this is my real view in the marktext
    <img width="638" alt="屏幕截图 2023-03-10 163117" src="https://user-images.githubusercontent.com/47783503/224265054-6c511457-a348-46b5-9976-51a7ddc5c501.png">

3. and this is my exporting pdf ( use default exporting settings ), you can see that it loses a line at the end of the first page. 
    <img width="664" alt="屏幕截图 2023-03-10 163244" src="https://user-images.githubusercontent.com/47783503/224264976-f9326a4f-1eb7-4719-85ed-09885c6f2cd7.png">

### Versions

- MarkText version: v0.17.1
- Operating system: win 11 22H2

**Comment by CarrotDLaw** [comment] 2023-03-28 18:03
MarkText does not correctly render a line break if you only press shift+return key for once. Put **two spaces** at the end of a line then **shift+return** to create a line break while keeping lines in the same paragraph; or press **return** key to open a new paragraph.

 The images show the results of valid line breaks. 

<img width="755" alt="SCR-20230329-2md" src="https://user-images.githubusercontent.com/52628857/228326420-33adc418-5f16-4dd4-8aff-8a8cdf80cc65.png">
View in MarkText. Notice there are return indicators at the end of (1) and (2), where two spaces were put at the end.

 <br> 
 <br> 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/52628857/228329870-75afdde0-30ec-449f-badb-edaff03936d0.png">
View in output PDF. (the '\\' at the end of (1) was deleted for a more decent output.)

**Comment by iquykumo** [comment] 2023-04-08 01:26
Thank you for the solution you suggested in your reply !

**Comment by CarrotDLaw** [comment] 2023-04-08 05:15
No problem! I have updated the reply as I made some confusion. The correct way to add a line break should be **shift+return** after two sapces. 

If this is not a bug, you may want to close this issue.

**Closed as completed** 2023-04-08 05:45 UTC
