### ISSUE TITLE
Issue with high DPI scaling

### ISSUE THREAD

**Issue by Yournished** [marktext/marktext#1058] opened 2019-06-01 23:04 UTC
I have a high DPI screen so I use DPI scaling. Header font is way too large for my screen - the top level header takes up 1/10th of my vertical space! Adjusting font size only changes the body text.

I'd like to add a compact theme that has smaller headers. Where are the theme CSS files? I'm using the flatpak on Linux.

**Comment by fxha** [comment] 2019-06-02 20:23
Currently there is no option to edit the theme without rebuilding Mark Text. I think #1029 may help with this issue. Could you please upload an image from Mark Text with some text?

**Comment by fxha** [comment] 2019-06-07 13:20
Closing this issue as no further information has been provided.

**Comment by Yournished** [comment] 2019-06-13 04:06
@fxha Please reopen issue.

>Currently there is no option to edit the theme without rebuilding Mark Text. I think #1029 may help with this issue.

That issue is about adding zoom. The zoom is not the problem. Body text size is fine. Header is too big. If I zoomed out, now the body text would be too small. The problem is that the ratio of header text/body text size is too large.

>Could you please upload an image from Mark Text with some text?

![headers](https://user-images.githubusercontent.com/12552668/59403033-d5c98080-8d55-11e9-9592-b8c5c2580bb2.png)

>Closing this issue as no further information has been provided.

For real? You only waited 4 days, dude.

**Comment by fxha** [comment] 2019-06-13 16:14
I don't know how to reproduce this issue but seems to be an upstream issue (electron/electron#10862), potential workaround: https://github.com/electron/electron/issues/6571#issuecomment-326865765.

**Comment by Yournished** [comment] 2019-06-14 03:02
The renaming is wrong. The issue is that more control is needed over theming. The problem with DPI scaling is only a particularly egregious special case of this problem. If you merely add some DPI scaling option, this would still leave other symptoms of hardcoded theming - such as inability to alter contrast, colors or font. Really, the ability to have custom themes has been a standard feature of most GUI programs for several decades now, I feel silly having to explain the necessity for it. The correct solution is to allow users to specify their own themes.

**Comment by fxha** [comment] 2019-06-14 09:37
> Currently there is no option to edit the theme without rebuilding Mark Text.

Please see my first comment. I guess v0.16.0 should become user themes but I don't know @Jocs planing there. Mark Text is still in active development and I would considered it as alpha software. Our priority is to fix bug and improve the overall experience. Meaning custom themes or other feature may or are less important than other things, especially when we have no stable APIs nor stable GUI elements or CSS paths. This means that we'll add user themes some day but today is not that day and even then themes may be broken after updates before v1.0.0.

If I understood your reply correctly, DPI scaling is not an issue/not the topic of this issue and then is this issue a duplicate of #174 and can be closed, right? If you like, you can subscribe there for further updates.

**Closed** 2019-06-22 10:38 UTC
Labels: 🦞 resolved/duplicate
