### ISSUE TITLE
Can't run on latest CentOS 7

### ISSUE THREAD

**Issue by jadupl2** [marktext/marktext#1992] opened 2020-03-21 17:32 UTC
### Description
Can't run marktext on CentOS 7 Latest

Can't run it, see example below
jacques@holmes:~/Downloads $ uname -a
Linux holmes.maison.ca 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
jacques@holmes:~/Downloads $ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.7.1908 (Core)
Release:	7.7.1908
Codename:	Core
jacques@holmes:~/Downloads $ 

### Steps to reproduce
$ /opt/marktext/marktext-0.15.1-x86_64.AppImage 
[11574:0321/131319.077084:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_markteZBSdQc/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

$ ls -l /opt/marktext/marktext-0.15.1-x86_64.AppImage 
-rwxr-xr-x 1 root root 94640300 Mar 21 12:53 /opt/marktext/marktext-0.15.1-x86_64.AppImage

$ sudo chmod 4755 /opt/marktext/marktext-0.15.1-x86_64.AppImage
sudo chmod 4755 /opt/marktext/marktext-0.15.1-x86_64.AppImage

$ ls -l /opt/marktext/marktext-0.15.1-x86_64.AppImage 
-rwsr-xr-x 1 root root 94640300 Mar 21 12:53 /opt/marktext/marktext-0.15.1-x86_64.AppImage

$ /opt/marktext/marktext-0.15.1-x86_64.AppImage 
open dir error: Permission denied
$ 
1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**
need to run 

**Actual behavior:**

$ /opt/marktext/marktext-0.15.1-x86_64.AppImage 
[11574:0321/131319.077084:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_markteZBSdQc/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

$ ls -l /opt/marktext/marktext-0.15.1-x86_64.AppImage 
-rwxr-xr-x 1 root root 94640300 Mar 21 12:53 /opt/marktext/marktext-0.15.1-x86_64.AppImage

$ sudo chmod 4755 /opt/marktext/marktext-0.15.1-x86_64.AppImage
sudo chmod 4755 /opt/marktext/marktext-0.15.1-x86_64.AppImage

$ ls -l /opt/marktext/marktext-0.15.1-x86_64.AppImage 
-rwsr-xr-x 1 root root 94640300 Mar 21 12:53 /opt/marktext/marktext-0.15.1-x86_64.AppImage

$ /opt/marktext/marktext-0.15.1-x86_64.AppImage 
open dir error: Permission denied
$ 
**Link to an example: [optional]**

### Versions

- Mark Text:
- Operating system:

**Comment by fxha** [comment] 2020-03-24 16:50
Thank you for reporting the issue. We noticed that this is a duplicate of [#1236](https://github.com/marktext/marktext/issues/1236#issuecomment-533674753).

**Closed by fxha** 2020-03-24 16:50 UTC
