### ISSUE TITLE
App crashing on I/O functions

### ISSUE THREAD

**Issue by mock** [marktext/marktext#2388] opened 2020-11-10 11:47 UTC
### Description

The application will crash when attempting to open a file or saving a new file.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open the app
2. From the menu, choose Open File...
3. App crashes

**Expected behavior:**

**Actual behavior:**
Expecting a file selection/browser dialog.

Core dumped.

**Link to an example: [optional]**

### Versions

- Mark Text version: 0.16.2
- Operating system: Fedora 33 (Linux 5.8.18-300.fc33.x86_64 #1 SMP Mon Nov 2 19:09:05 UTC 2020 x86_64)

From the **journalctl** when attempting to Open File:
```
Nov 10 06:35:21 ******* systemd-coredump[84414]: [🡕] Process 84316 (marktext) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 2:
                                                  #0  0x00007f42f5dd2775 n/a (/usr/lib/x86_64-linux-gnu/libc-2.31.so + 0x39775)
░░ Subject: Process 84316 (marktext) dumped core
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)
░░ 
░░ Process 84316 (marktext) crashed and dumped core.
░░ 
░░ This usually indicates a programming error in the crashing program and
░░ should be reported to its vendor as a bug.
Nov 10 06:35:21 ******* systemd[1]: systemd-coredump@4-84411-0.service: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit systemd-coredump@4-84411-0.service has successfully entered the 'dead' state.
Nov 10 06:35:21 21 ******* audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@4-84411-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Nov 10 06:35:21 ******* systemd[1]: systemd-coredump@4-84411-0.service: Consumed 1.180s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit systemd-coredump@4-84411-0.service completed and consumed the indicated resources.
```

**Comment by fxha** [comment] 2020-11-13 12:34
Thank you for taking the time to report this issue. I think this is a system issue with GNOME (`libc`) based on the stack trace. Could you please update your system and try again because I'm running Fedora 33 too without any issues. Please provide more details (stack trace etc) if the issue is still present. There was a similar issue with GNOME file picker a year ago but that was fixed by GNOME team.

**Comment by mock** [comment] 2020-11-13 13:26
I just updated the system. I appear to be running `glibc 2.32-1`.

```
$ dnf list glibc*
Last metadata expiration check: 0:54:02 ago on Fri 13 Nov 2020 07:23:03 AM EST.
Installed Packages
glibc.x86_64                                                             2.32-1.fc33                                            @fedora
glibc-all-langpacks.x86_64                                               2.32-1.fc33                                            @fedora
glibc-common.x86_64                                                      2.32-1.fc33                                            @fedora
glibc-devel.x86_64                                                       2.32-1.fc33                                            @fedora
glibc-headers-x86.noarch                                                 2.32-1.fc33                                            @fedora
glibc-langpack-en.x86_64                                                 2.32-1.fc33                                            @fedora
```

Yet I still am having trouble:
```
Nov 13 08:16:06 djibouti systemd-coredump[4323]: [🡕] Process 4243 (marktext) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 2:
                                                 #0  0x00007f2aa83a1775 n/a (/usr/lib/x86_64-linux-gnu/libc-2.31.so + 0x39775)
░░ Subject: Process 4243 (marktext) dumped core
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)
░░ 
░░ Process 4243 (marktext) crashed and dumped core.
```

I don't seem to have a `libc` module (without the `g`) available in the repos for my system. Right now, I am:
```
Linux ****** 5.8.18-300.fc33.x86_64 #1 SMP Mon Nov 2 19:09:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mock** [comment] 2020-11-13 13:42
Here are a few more details:

**var_log_messages**:
```
User Logs:
--Nov 13 08:35:36 djibouti com.github.marktext.marktext.desktop[10061]: (node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
Nov 13 08:35:36 djibouti com.github.marktext.marktext.desktop[10061]: (node:2) DeprecationWarning: init() is deprecated and will be removed in v5.
Nov 13 08:35:36 djibouti marktext[10061]: Failed to load module "canberra-gtk-module"
Nov 13 08:35:36 djibouti marktext[10061]: Failed to load module "pk-gtk-module"
Nov 13 08:35:36 djibouti marktext[10061]: Failed to load module "canberra-gtk-module"
Nov 13 08:35:36 djibouti marktext[10061]: Failed to load module "pk-gtk-module"
Nov 13 08:35:36 djibouti com.github.marktext.marktext.desktop[10061]: (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
Nov 13 08:35:37 djibouti com.github.marktext.marktext.desktop[10111]: (node:48) Electron: Loading non-context-aware native module in renderer: '/app/marktext/resources/app.asar.unpacked/node_modules/@hfelix/spellchecker/build/Release/spellchecker.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
Nov 13 08:35:37 djibouti com.github.marktext.marktext.desktop[10111]: (node:48) Electron: Loading non-context-aware native module in renderer: '/app/marktext/resources/app.asar.unpacked/node_modules/fontmanager-redux/build/Release/fontmanager.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
Nov 13 08:35:37 djibouti com.github.marktext.marktext.desktop[10111]: (node:48) DeprecationWarning: file property is deprecated and will be removed in v5.
Nov 13 08:35:37 djibouti com.github.marktext.marktext.desktop[10111]: (node:48) DeprecationWarning: init() is deprecated and will be removed in v5.
Nov 13 08:35:41 djibouti marktext[10061]: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
Nov 13 08:35:41 djibouti com.github.marktext.marktext.desktop[10061]: **
Nov 13 08:35:41 djibouti com.github.marktext.marktext.desktop[10061]: Gtk:ERROR:../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: Error opening file /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: No such file or directory (g-io-error-quark, 1)
Nov 13 08:35:41 djibouti com.github.marktext.marktext.desktop[10061]: Bail out! Gtk:ERROR:../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: Error opening file /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: No such file or directory (g-io-error-quark, 1)
Nov 13 08:35:41 djibouti com.github.marktext.marktext.desktop[10061]: Failed to generate minidump.
--
```

**dso_list**:
```
/usr/share/icons/hicolor/icon-theme.cache hicolor-icon-theme-0.17-9.fc33.noarch (Fedora Project) 1603882013
/usr/lib/locale/en_US.utf8/LC_COLLATE glibc-langpack-en-2.32-1.fc33.x86_64 (Fedora Project) 1603882008
/usr/share/locale/en/LC_MESSAGES/gtk30.mo gtk3-3.24.23-1.fc33.x86_64 (Fedora Project) 1603882381
/usr/lib/locale/en_US.utf8/LC_CTYPE glibc-langpack-en-2.32-1.fc33.x86_64 (Fedora Project) 1603882008
```

Is this helpful?

**Comment by mock** [comment] 2020-11-13 13:48
You know what? It's crashing on a missing icon size. This and a few other apps are missing a scalable icon in my icon theme, so they just crash.

```
$ flatpak run com.github.marktext.marktext
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:2) DeprecationWarning: init() is deprecated and will be removed in v5.
Gtk-Message: 08:45:47.030: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:45:47.030: Failed to load module "pk-gtk-module"
Gtk-Message: 08:45:47.030: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:45:47.030: Failed to load module "pk-gtk-module"
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

(marktext:2): Gtk-WARNING **: 08:45:56.309: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: Error opening file /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: No such file or directory (g-io-error-quark, 1)
Bail out! Gtk:ERROR:../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: Error opening file /run/host/share/icons/Flat-Remix-Blue-Dark/status/scalable/512/image-missing.svg: No such file or directory (g-io-error-quark, 1)
Failed to generate minidump.[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
```

**Comment by fxha** [comment] 2020-11-13 14:34
That's a very strange error without any fallback handling :smile:  You should report this to the GNOME GitLab or, as you use Flatpak, to [freedesktop-sdk](https://gitlab.com/freedesktop-sdk). I think there's nothing we can do about it.

Before doing so, please run `flatpak update` to get the latest SDK (Flatpak has it's own GNOME SDK).

**Comment by mock** [comment] 2020-11-13 16:21
I ran the `flatpak update` before trying things again this morning. I am not that tied to an icon set to need to keep using it. It's possible I need to pull an update from gnome-look.org. I just switched to one with the desired icon and things are working.

**Closed** 2020-11-15 11:54 UTC
Labels: :beetle: pri/major, :penguin: platform/linux, 🐟  blocked/upstream
