### ISSUE TITLE
Updater Script, Tray Icon.

### ISSUE THREAD

**Issue by RebelCoderRU** [marktext/marktext#1258] opened 2019-08-10 15:22 UTC
Hello.

This is amazing notes app. Any plans to add auto-updater so we don;t have to go to Github/website all the time to download latest AppImage ?

And adding a tray Icon and running it in the background would be awesome.

**Comment by fxha** [comment] 2019-08-10 16:01
There is already a manual updater when you are using AppImage, DMG or NSIS setup. You can find this under `Mark Text -> Check for updates` on macOS or `Help -> Check for updates` otherwise. I guess the auto updater feature is a duplicate of #211 and #1245. Please subscribe there for further updates.

> And adding a tray Icon and running it in the background would be awesome.

What are the benefits of using a system tray icon? We don't use any background task or other services. I think waiting 1-2 seconds to open is fine because we may consume a lot of memory at the moment, so sitting in the background may not the best idea.

**Comment by Jocs** [comment] 2019-10-07 15:56
>And adding a tray Icon and running it in the background would be awesome.

Do you use Mark Text on macOS system? What features or functions do you want in the tray icon?

**Comment by CAtoDC** [comment] 2019-10-21 12:15
The benefits of a system tray icon (if I'm understanding this correctly) is to be able to add it to Favorites (usually a right-click on the icon).  This isn't possible currently.

**Comment by Jocs** [comment] 2019-10-21 13:35
@CAtoDC Mark Text is not a NOTE app, it only a markdown editor, so no need to `add it to favorites`?

**Comment by CAtoDC** [comment] 2019-10-22 13:10
I understand that MarkText is a markdown editor. I use it all the time for various purposes. I'd just like to see the MarkText **icon** and be able to open it that way (or save it as a favorite).  In Ubuntu Mate 19.10, I can't seem to do that. All I see is the generic icon with "marktext-0.15.1-x86_64.AppImage".

**Comment by Jocs** [comment] 2019-10-22 14:00
@fxha What's your opinion?

**Comment by fxha** [comment] 2019-10-22 18:47
> I'd just like to see the MarkText icon and be able to open it that way (or save it as a favorite). In Ubuntu Mate 19.10, I can't seem to do that. All I see is the generic icon with "marktext-0.15.1-x86_64.AppImage".

AppImage is only a binary file that is extracted at runtime without system integration. On Linux you need a "desktop" file, so the application is listed in the application list. You can integrate the AppImage via AppImageLauncher into to system or copy and modify [this](https://github.com/marktext/marktext/blob/develop/resources/linux/marktext.desktop) desktop file to `~/.local/share/applications/marktext.desktop`. Whereas `marktext` in `Exec=marktext %F` should point to the AppImage.

> What's your opinion?

I still think a tray is not needed or if you like to add it, it should be disabled by default because not all desktop environments support system tray icons (e.g. GNOME that is also used on Ubuntu - AFAIK) and so the application runs in background without interaction possible.

**Comment by adrienbeau** [comment] 2019-10-28 09:50
Having AppImage Launcher (simply installing that package) before installing Mark Text is all that is needed to have a proper application icon in the appropriate launcher menu. After that all the usual desktop environment features (shortcuts, favorites) are available. Maybe the installation instructions should be updated to mention that.

**Comment by fxha** [comment] 2019-12-20 21:41
Automatically updates are currently not planned but supported by a few packages. Closing this as duplicate of #211 of update notifications.

**Closed by fxha** 2019-12-20 21:41 UTC
Labels: :unicorn: feature request
