### ISSUE TITLE
Unexpected error: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by dumplingsMing** [marktext/marktext#1131] opened 2019-07-02 01:56 UTC
### Description

An unexpected error occurred in the renderer process when pressed 'tab' button at the header line (like pressing "##\<space\>lalala\<tab\>", then this error occured).

### Stack Trace

```
TypeError: Cannot read property 'type' of null
    at A.type [as isIndentableListItem] (file:///tmp/.mount_markteTTrpCD/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/tabCtrl.js:76:16)
    at A.isIndentableListItem [as tabHandler] (file:///tmp/.mount_markteTTrpCD/resources/app.asar/dist/electron/webpack:/src/muya/lib/contentState/tabCtrl.js:272:14)
    at HTMLDivElement.tabHandler (file:///tmp/.mount_markteTTrpCD/resources/app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/keyboard.js:137:24)
```

### Version

Mark Text: v0.14.0 (e54731f)
Operating system: linux

**Comment by fxha** [comment] 2019-07-02 19:24
Thanks for reporting this issue. This can be reproduced with v0.14.0 but not with the latest development branch.

@Jocs But there is another issue on the latest development branch when setting the cursor in the next line. This also applies to heading that ends with spaces. I think that this could be related to this issue.

```
index.js:416 Uncaught TypeError: Cannot read property 'nodeType' of null
    at nodeType (./app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:416)
    at Object.getNodeAndOffset [as setCursorRange] (./app.asar/dist/electron/webpack:/src/muya/lib/selection/index.js:475)
    at hs.setCursorRange [as setCursor] (./app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:159)
    at hs.setCursor [as partialRender] (./app.asar/dist/electron/webpack:/src/muya/lib/contentState/index.js:208)
    at hs.partialRender [as clickHandler] (./app.asar/dist/electron/webpack:/src/muya/lib/contentState/clickCtrl.js:39)
    at HTMLDivElement.clickHandler (./app.asar/dist/electron/webpack:/src/muya/lib/eventHandler/clickEvent.js:140)
```

Example:

```
# foo<cursor>

asd
```

--->

```
# foo<tab|spaces>

as<cursor>d
```

**Comment by Jocs** [comment] 2019-07-03 03:28
@fxha I can not reproduce this issue what you described. I write `markdown` bellow.

```md
# foo<cursor>

bar
```

And press <kbd>tab</kbd>

it works well, and insert 4 spaces after `foo`, and no error happened?

is there any wrong when I reproduce this issue?

**Comment by fxha** [comment] 2019-07-03 18:41
@Jocs The exception doesn't always occur, just try a few times with different cursor position or write some text and try again.

**Comment by fxha** [comment] 2019-09-23 15:29
Closing this issue because it's not reproducible with the latest version.

**Closed by fxha** 2019-09-23 15:29 UTC
Labels: :question: confirmation needed, 🐛 bug
