### ISSUE TITLE
Unexpected error: Cannot read property '1' of null

### ISSUE THREAD

**Issue by JosephaGK** [marktext/marktext#1129] opened 2019-07-01 13:28 UTC
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError: Cannot read property '1' of null
    at matches (D:\Mark Text\resources\app.asar\dist\electron\webpack:\src\main\utils\index.js:31:14)
    at Array.map (<anonymous>)
    at map (D:\Mark Text\resources\app.asar\dist\electron\webpack:\src\main\utils\index.js:28:24)
    at EventEmitter.getRecommendTitle (D:\Mark Text\resources\app.asar\dist\electron\webpack:\src\main\actions\file.js:74:27)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (D:\Mark Text\resources\electron.asar\browser\api\web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)
```

### Version

Mark Text: v0.14.0
Operating system: win32

**Comment by fxha** [comment] 2019-07-01 18:39
Thanks for reporting this issue. We noticed that this is a duplicate of #1128. You may want to subscribe there for further updates.

**Closed by fxha** 2019-07-01 18:39 UTC
