### ISSUE TITLE
Exporting to PDF with "Dark" theme produces an unreadable document

### ISSUE THREAD

**Issue by dartheian** [marktext/marktext#780] opened 2019-03-19 22:06 UTC
### Description

Exporting to PDF with "Dark" theme produces an unreadable document.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]

Change the theme to "dark"

2. [Second step]

Export the file to PDF

**Expected behavior:**

A readable PDF document with black characters on a white background (or the converse).

**Actual behavior:**

An unreadable PDF document with black characters on a black background.

### Versions

- Mark Text: 0.13.65
- Operating system: Arch Linux

**Comment by fxha** [comment] 2019-03-21 12:24
Duplicate of #583

**Closed by fxha** 2019-03-21 12:24 UTC
