### ISSUE TITLE
 0.16.1.2025 doesn't start on Windows 10

### ISSUE THREAD

**Issue by Hoffenbar** [marktext/marktext#2021] opened 2020-03-29 13:51 UTC
### Description

Program starts with an error message, see screenshot.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Doubleklick mark text.exe

**Expected behavior:**

Program dialogue should appear

**Actual behavior:**

Error message appears, see screenshot.

### Versions

- Mark Text: 0.16.1.2025
- Operating system: Windows 10 1909 (Build 18363.720)
![2020-03-29 15_50_36-Window](https://user-images.githubusercontent.com/46227007/77850792-1905ba80-71d5-11ea-96b8-e00ec63c262f.jpg)

**Comment by fxha** [comment] 2020-03-31 14:35
Thank you for taking the time to report this issue. Unfortunately, we cannot reproduce the exception with the latest release package. What architecture (32-bit or 64-bit) are you using and have you installed an official or third-party package? Have you tried to uninstall and install Mark Text again?

**Comment by Hoffenbar** [comment] 2020-03-31 15:07
Hello,I used the 64bit portable.-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 31.03.20, 16:35 schrieb "Felix Häusler" <notifications@github.com>:

   
  Thank you for taking the time to report this issue. Unfortunately, we cannot reproduce the exception with the latest release package. What architecture (32-bit or 64-bit) are you using and have you installed an official or third-party package? Have you tried to uninstall and install Mark Text again?

**Comment by fxha** [comment] 2020-06-07 00:35
I'm closing this issue as we cannot reproduce it and no further information has been provided. It's may an issue with your OS.

**Closed by fxha** 2020-06-07 00:35 UTC
Labels: :baby_chick: blocked/need info, :hamster: platform/windows
