### ISSUE TITLE
In source code mode, contents do not change when switching between tabs

### ISSUE THREAD

**Issue by maxloh** [marktext/marktext#637] opened 2019-01-06 14:52 UTC
### Description

In source code view, contents do not change when switching between tabs

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create two files, a.md and b.md
2. Type something in both files
3. Toggle source code view in a.md
4. Switch to b.md

**Expected behavior:**

marktext display source code of b.md after switching tabs

**Actual behavior:**

marktext remains displaying source code of a.md

![capture](https://user-images.githubusercontent.com/35831069/50737566-df2e4a00-1205-11e9-843f-6eeacc1a177e.PNG)

### Versions

- Mark Text: v 0.13.65
- Operating system: Windows 10 17763.195

**Comment by fxha** [comment] 2019-01-06 16:31
Duplicate of #606

**Closed by fxha** 2019-01-06 16:31 UTC
