### ISSUE TITLE
Alt gr problem on other keyboard layouts

### ISSUE THREAD

**Issue by cervthecoder** [marktext/marktext#2720] opened 2021-12-01 22:30 UTC
https://github.com/marktext/marktext/blob/cb8b031753290e84c0da7db80b971934ccb56032/src/main/keyboard/shortcutHandler.js#L109

I think that this make the issue with alt gr and number keys that are binded with @#$~&*{} etc.

**Comment by YalandHong** [comment] 2021-12-02 02:06
Duplicate of #2225

Some people have reported such issues there. ([comment1](https://github.com/marktext/marktext/issues/2225#issuecomment-828321507), [comment2](https://github.com/marktext/marktext/issues/2225#issuecomment-983447421))

**Comment by cervthecoder** [comment] 2021-12-02 15:03
I've fixed by installing version 15.1

čt 2. 12. 2021 v 3:06 odesílatel YalandHong ***@***.***>
napsal:

**Comment by csingewald** [comment] 2021-12-16 08:27
This problem is caused by the key bindings used for switching tabs Alt+1,...., Alt+0.
To solve this temporary use custom key bindings

```json 
{
  "tabs.switch-to-first": "Ctrl+1",
  "tabs.switch-to-second": "Ctrl+2",
  "tabs.switch-to-third": "Ctrl+3",
  "tabs.switch-to-fourth": "Ctrl+4",
  "tabs.switch-to-fifth": "Ctrl+5",
  "tabs.switch-to-sixth": "Ctrl+6",
  "tabs.switch-to-seventh": "Ctrl+7",
  "tabs.switch-to-eighth": "Ctrl+8",
  "tabs.switch-to-ninth": "Ctrl+9",
  "tabs.switch-to-tenth": "Ctrl+0"
}
```

https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md

**Comment by fxha** [comment] 2021-12-16 21:47
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2235. You may want to subscribe there for further updates.

**Closed by fxha** 2021-12-16 21:47 UTC
