### ISSUE TITLE
Table of Content Wrong level

### ISSUE THREAD

**Issue by xfzka** [marktext/marktext#1027] opened 2019-05-14 08:02 UTC
### Description

Table of Content Wrong level

- [x] Can you reproduce the issue? 

### Steps to reproduce

save this to md file and open you will see.

```markdown
# 测试

123123123

## TTT

顺1123测试

### 123afds

12312312

## TT

1测试

## 阿道夫骄傲是的

12312阿斯顿发的

## TTT

1231阿迪深纺大厦
```

**Expected behavior:**

- 测试
  - TTT
    - 123afds
  - TT
  - 阿道夫骄傲是的
  - TTT

**Actual behavior:**

![image](https://user-images.githubusercontent.com/24959175/57681059-82ceb180-7661-11e9-9920-05af38126a40.png)

![image](https://user-images.githubusercontent.com/24959175/57681550-7e56c880-7662-11e9-9b71-ea478100d044.png)

![image](https://user-images.githubusercontent.com/24959175/57681577-8a428a80-7662-11e9-9ab0-e156f1dbf162.png)

### Versions

- Mark Text: v0.14.0
- Operating system: macOS Mojave

**Comment by fxha** [comment] 2019-05-15 18:14
Duplicate of #966

**Closed by fxha** 2019-05-15 18:14 UTC
