### ISSUE TITLE
Relative Path Images do not appear

### ISSUE THREAD

**Issue by CedricBonjour** [marktext/marktext#815] opened 2019-03-26 15:54 UTC
### Description

Relative Path Images do not appear.
It seems the path is broken.

- [x] Can you reproduce the issue? 
Constant 

### Steps to reproduce

1.  in file add line:
```
![example_image](img/example_image.png)
```
2. File -> Export -> PDF

**Expected behavior:**
the image appears in both the editor and the exported pdf

**Actual behavior:**
the image appears in neither the editor nor the pdf 

**Note**
the equivalent with the absolute path works perfectly.
Adding the image selecting  ' Edit->Insert Image ->Relative Path ' just inserts the absolute path

### Versions

- Mark Text: v 0.13.65
- Operating system: OSX 10.14.3

**Comment by fxha** [comment] 2019-03-26 16:35
Duplicate of #678 and #782.

> Adding the image selecting ' Edit->Insert Image ->Relative Path ' just inserts the absolute path

The absolute path is inserted if the file has not been saved yet.

**Closed by fxha** 2019-03-26 16:35 UTC

**Comment by CedricBonjour** [comment] 2019-03-26 16:38
Yes indeed, I just realised.

Although the file was saved but only  after the editor was opened.

I had to close and reopen the editor for the relative path to function properly.

This is an issue if you edit pictures as you edit your markdown.
