### ISSUE TITLE
Dropdown summary is not properly rendered.

### ISSUE THREAD

**Issue by AliTajelsir** [marktext/marktext#2041] opened 2020-04-12 05:41 UTC
### Description
 Dropdown summary is not properly rendered.

- [x] Can you reproduce the issue? 

### Steps to reproduce
1.  Create a dropdown summary using: 
- 1st ex.:
```
<details>
    <summary>Test</summary>

- Test 1
- Test 2

</details>
```
- 2nd ex.:
```
<details>
    <summary>Test</summary>
<br>
- Test 1
- Test 2
</details>

```

**Expected behavior:**
- In the 1st ex:
<details>
    <summary>Test</summary>

- Test 1
- Test 2
</details>

- In the 2nd ex.:

<details>
    <summary>Test</summary>
<br>
- Test 1
- Test 2
</details>

**Actual behavior:**
- In the 1st ex. the contents are not considered part of the summary 
![Screenshot](https://user-images.githubusercontent.com/26362874/79061245-53b82a00-7c8e-11ea-896a-44dbe6bd010f.png)

- In the 2nd ex. it's rendered proberly and matched the expected behavior but with that I lose  the checklist
![ScreenShot](https://user-images.githubusercontent.com/26362874/79061466-d6da7f80-7c90-11ea-957d-4b882f887bb2.png)

### Versions

- Mark Text: 0.16.1
- Operating system: 
```
Operating System: EndeavourOS 
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.14.2
Kernel Version: 5.6.3-2-clear
OS Type: 64-bit
```

**Comment by fxha** [comment] 2020-06-06 23:39
Thank you for reporting the issue. We noticed that this is a duplicate of #2034. You may want to subscribe there for further updates.

**Closed by fxha** 2020-06-06 23:39 UTC
