### ISSUE TITLE
CTRL+Z not working

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#311] opened 2018-05-31 09:37 UTC
### Description

Pressing `CTRL+Z` doesn't do anything.

### Steps to reproduce

1. Type some text
2. Delete some text
3. `CTRL+Z`

**Expected behavior:** That the deleting text gets undone

**Actual behavior:** Nothing happens

### Versions

- Mark Text: v 0.11.42
- OS: Windows 10

**Comment by Jocs** [comment] 2018-05-31 09:52
@stefnotch Mark Text will generate a `history` after you stop typing for 2 seconds.

```javascript
// for saving memory and improve Mark Text performance
this.historyTimer = setTimeout(handler, 2000)
```

So when you type some text, but you delete them immediately! it will not generate a history in Mark Text, it caused `CTRL + Z` doesn't do anything.

**Comment by stefnotch** [comment] 2018-05-31 09:54
@Jocs I tried waiting a while, however, `CTRL+Z` still doesn't work. 
But `File --> Undo` does work.

**Comment by Jocs** [comment] 2018-05-31 10:01
That's strange, @fxha can you help test this issue on you windows computer? I test it on Mac, and it works well.

@stefnotch can you update this issue description and give more details? gif is preferred. thank you.

**Comment by stefnotch** [comment] 2018-05-31 10:07
![2018-05-31_12-04-36](https://user-images.githubusercontent.com/10220080/40776365-d51a0f9c-64ca-11e8-8867-49359278b93f.gif)

So, here is a GIF where I'm doing the following things
1) typing some text
2) using the `File->Undo` and `File->Redo` options
3) pressing `CTRL+Z`
4) using `File->Undo` which doesn't appear to do anything at all
5) using `File->Undo` which does undo the typing

I think that the issue is that `CTRL+Z` is interpreted as me typing some text instead of as a shortcut.

**Comment by fxha** [comment] 2018-05-31 10:37
Yeah, I can later.

**Comment by fxha** [comment] 2018-05-31 11:38
OK, did a quick check and I think `Ctrl+Z` is a duplicate of https://github.com/marktext/marktext/issues/216 because I can press `Ctrl+Super+Z` to undo on Linux. And I can confirm the double menu undo bug if the cursor is not at the end of the line. If the cursor is at the end of the line everything is OK.

**Comment by rgomez90** [comment] 2018-07-04 15:07
I recently installed **MarkTest** and I'm having this issue, not being able to undo via shortcut. It does not matter how long I wait or/and type, undo via shortcut never works.

**Comment by dibyadas** [comment] 2018-07-04 15:47
Same here. In Linux, `CTRL+Z` doesn't undo no matter what. But `CTRL+Super+Z` seems to work. And then again, `CTRL+Shift+Z` doesn't redo at all. It's strange to see these very commonly used functions not working as expected.  

P.S, : Great work on MarkText! Straight off one of the best looking markdown editor I've ever used. Felt like a gift from heaven when I found this while searching for .md editors. :heart:

**Comment by fxha** [comment] 2018-11-04 17:08
@stefnotch @rgomez90 @dibyadas

I'm happy to announce that we solved the keybinding issue. Could you please check whether everything is ok on your machine. Maybe we have to improve the solution, particularly relating non US-keyboards. Prebuilt binaries for Linux and Windows are available [here](https://github.com/marktext/marktext/releases/tag/KeybindingFixes). Please see PR #543 for more information.

Thanks!

**Comment by clrh** [comment] 2018-11-15 11:15
Hi,

It's not ok in my computer. When I do Ctrl + Z I got a message that told me that changes will lost if I do not save them.

Keyboard: azerty (french)

Regards.

**Comment by stefnotch** [comment] 2018-11-15 11:37
I just tested it (Windows 10) and can confirm this issue with the French keyboard layout.

It's probably because `w` <--> `z` (`qwerty` <--> `azerty`)

**Comment by fxha** [comment] 2018-11-15 12:21
Thanks @clrh and @stefnotch, I can confirm the issue on Linux and Windows and we'll fix the issue as soon as possible.

@clrh Which operating system do you use?

**Comment by fxha** [comment] 2018-11-15 16:38
Unfortunately, it's a problem in a third-party library dependency (`keyboardevent-from-electron-accelerator`) with wrong virtual key mapping and it's also a little bit inconsistent. E.g.

**France keyboard:** `Ctrl+W` and  `Ctrl+Z`:

`Cltr+W`

```
raw accelerator (correct accelerator):
{ code: 'KeyZ', // virtual key
    key: 'w',   // actual key
    altKey: false,
    shiftKey: false,
    metaKey: false,
    ctrlKey: true }

we receive:
{ ctrlKey: true, key: 'w', code: 'KeyW' }
```

`Cltr+Z`

```
raw accelerator (correct accelerator):
 { code: 'KeyW',
    key: 'z',
    altKey: false,
    shiftKey: false,
    metaKey: false,
    ctrlKey: true }

we receive:
{ ctrlKey: true, key: 'w', code: 'KeyW' }
```

**German keyboard:** Both `Ctrl+Z` and  `Ctrl+Y` are interpreted as  `Ctrl+Z` .

The good part of this is that we already forked the library and we could just change the virtual keys at runtime. Well, let me see...

**Comment by fxha** [comment] 2018-11-15 17:05
When we strict match shortcuts (actual key only and ignore vkeys), that means that we remove [this line](https://github.com/parro-it/keyboardevents-areequal/blob/6054558bc03ba3d866a0e914908270f09eb41317/main.js#L26), then everything works fine but I don't know whether we break other keyboard layouts. Normally it should work because we don't use virtual keys.

@Jocs  Can you please send me `marktext --dump-keyboard-layout` output for German and/or France keyboard layout of macOS per email?

**Closed** 2018-11-16 00:59 UTC
Labels: In progress, bug, linux, windows

**Comment by DocBrown101** [comment] 2020-09-04 08:35
Is there soon a way to fix the error. With version 0.16.2 it still occurs!
Is there a workaround for it?

**Comment by mguhlin** [comment] 2024-07-19 15:44
This problem is still happening on GNU/Linux Mint installation of Marktext. I lost 30 minutes of writing. What a disappointment. I've apt purged Marktext from my machine in a fit of rage (joke) but I wanted to let someone know this is happening.

I won't repeat all the nice things others have said about Marktext, except to point out that I was sad about losing data. Anyways, now you know.

**Comment by vdias38** [comment] 2026-01-09 11:56
This pb is still happening on Windows 11, PT Keyboard

https://github.com/user-attachments/assets/1743d66a-52ee-4d90-a7c0-28b618568b6c

**Comment by jmalmsten** [comment] 2026-04-30 08:26
Can report that it's happening on my dell laptop running fedora 44 as well. I have installed it through the gnome software manager, if that helps. 

And to add to the info. I can use ctrl+e to enter and exit edit mode, so ctrl works. And I can type z in text form so the z button works as well.
