### ISSUE TITLE
[FEATURE REQUEST]: Numbering of headers in sidebar and in editor

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1379] opened 2019-09-26 15:50 UTC
### Describe your feature request

When the sidebar is shown, there is a tree in the sidebar which shows the headers and subheaders.
The 1st H1 header is shown in the tree with number 1.
If below that 1st H1 header there is an H2 header, that one is shown and numbered 1.2
If below H2 there is an H3 header, that one is shown and numbered 1.3
And so on.

The next H1 header is shown in the tree with number 2.
If below that 2nd H1 header there is an H2 header, that one is shown and numbered 2.2
And so on.

This should also apply to the editor.

See also #1375

### What problem does this feature solve? [optional]

It makes reading and navigating a document, especially a long one, much easier.

### Additional context [optional]

This can be tackled with a css file.

**Comment by fxha** [comment] 2019-09-26 15:58
Duplicate of #1275 and #1276.

**Closed by fxha** 2019-09-26 15:58 UTC
