### ISSUE TITLE
Mark Text freezes

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1273] opened 2019-08-16 05:39 UTC
### Description

 From time to time MT freezes, which means the cursor does not work anymore, one cannot move the scroll bar, MT itself can only closed by terminating it in the Task Manager.

- [x] Can you reproduce the issue? 

### Steps to reproduce
It cannot be reproduced, it happens at random, but regularly. It can happen when 1 document is open, or 2 or 3 or ....
Edit: I found that it happens when the PageUp or PageDown key is used.

**Expected behavior:**
 Not to freeze
<!
**Actual behavior:**
 A document is open, <strike>and either before I can even start to edit it, or after editing it, MT freezes and has to be closed and reopened.</strike> and I can edit it, but as soon as the PGUp or PgDn key is used, MT freezes.

### Versions

- Mark Text: 0.15.0
- Operating system: Linux |Mint 19.2 XFCE

**Comment by fxha** [comment] 2019-08-16 15:44
Duplicate of #655.

**Closed by fxha** 2019-08-16 15:44 UTC

**Comment by DutchPete** [comment] 2019-08-16 16:03
In issue 655 you said:
> We should disable page down/up key until this is resolved or we implemented custom scrolling for these two keys.

Disabling the keys is fine as a workaround, but what is not fine is to have the whole app freezing when those keys are used.

Why are this issue and #655 closed?

**Comment by fxha** [comment] 2019-08-16 16:16
#655 is not closed but we don't really know where the error is located. I think, as a workaround we'll disable page down/up until we find the error.

The core problem is that I don't know how to debug the frozen application. In languages like C++/Rust you can use hardware debugging to step through the code but in JS/Node, a code block is executed by V8 (JS interpreter) and the application freeze without interaction possible. Help is really welcome if you or another person know how to debug this. I guess we need control over V8 to step through the code until the application freezes.

**Comment by DutchPete** [comment] 2019-08-16 16:33
OK, I understand now. Unfortunately I am not a coder, I am just an enthusiastic user who is happy to have discovered Mark Text yesterday. I believe MT has great potential: one of its big competitors is Typora, one of the best in class, if not *the* best at the moment, but I believe that with a few tweaks and additional features MT can overtake Typora. Hence my enthusiastic participation with bringing things to your attention, and requesting specific features that I know will lift MT to that higher level.

**Comment by Jocs** [comment] 2019-08-17 01:05
@DutchPete Thank you very much for your use and for your valuable comments.
