### ISSUE TITLE
Default zoom setting in preferences

### ISSUE THREAD

**Issue by lyndhurst** [marktext/marktext#2070] opened 2020-04-26 09:14 UTC
### Describe your feature request

An additional setting for a default zoom on application start up in 'preferences'.

### What problem does this feature solve? 

Fonts and menu are so tiny by default, it makes the app unpleasant to use. The absence of keyboard shortcut for zooming in/out makes it even less convenient.

### Additional context [optional]

I am using Kubuntu, and, all electron apps appear this way by default for me; it is not Mark Text specific. I had the same issue with KeeWeb for example, the developer later added a zoom setting; that solved the problem )

Thank you for your time.

**Comment by fxha** [comment] 2020-06-11 22:08
Thank you for reporting the issue. We noticed that this is a duplicate of #1906. You may want to subscribe there for further updates.

**Closed by fxha** 2020-06-11 22:08 UTC
