### ISSUE TITLE
open links

### ISSUE THREAD

**Issue by ericszimmermann** [marktext/marktext#575] opened 2018-11-26 10:53 UTC
### Description

Feature: I would like to be able to open links to urls and local documents by clicking on it
(or at list by clicking on with with Ctrl hold down).

### Steps to reproduce

1. Make a link like [Test Page for opening urls](http://www.test-page.com)
2. Clicking on it and nothing happens.

**Expected behavior:**

With click on the link, the Webpage opens, with Ctrl or Shift pressed going to edit line.
(Thats my preference, opening the Webpage by pressing Ctrl and editing otherwise, would also be ok.)

### Versions

- Mark Text: v0.13.50
- Operating system: On Windows and Linux

**Comment by fxha** [comment] 2018-11-26 18:46
Duplicate of #425.

**Closed by fxha** 2018-11-26 18:46 UTC
