### ISSUE TITLE
Relative image folder in the location as the .md file

### ISSUE THREAD

**Issue by CapaoAzul** [marktext/marktext#2528] opened 2021-03-15 11:30 UTC
### Describe your feature request

One thing that is critical for me and prevents me to use Marktext instead of typora is the way that the image folder is created. In typora when I paste an image, it automatically creates an asset folder in the same location as the .md file. In Marktext the asset folder is created inside the root main folder, independently where I am working on.

At the moment Marktext does this:
![image](https://user-images.githubusercontent.com/2741917/111146812-c4905200-8581-11eb-9525-e3fc7effde2e.png)

I would like to an option to do this:
![image](https://user-images.githubusercontent.com/2741917/111146110-f9e87000-8580-11eb-9f77-d5338d050554.png)

**Comment by FernandoBasso** [comment] 2021-08-11 17:23
There are a few related issues already:

- [https://github.com/marktext/marktext/issues/2560](https://github.com/marktext/marktext/issues/2560)
- [https://github.com/marktext/marktext/issues/2561](https://github.com/marktext/marktext/issues/2561) This one has my comment with tree output example.
- [https://github.com/marktext/marktext/issues/2556](https://github.com/marktext/marktext/issues/2556)

**Comment by YalandHong** [comment] 2021-11-30 02:59
Duplicate of #2559, if you want MarkText to automatically save the images in `./${filename}.assets` like Typora does.

**Closed** 2021-12-22 16:20 UTC
