### ISSUE TITLE
Custom image upload

### ISSUE THREAD

**Issue by XRSec** [marktext/marktext#2848] opened 2022-01-05 02:51 UTC
### Custom image upload

[typora + dogedoge.py](https://github.com/XRSec/typora-dogedoge/blob/main/typora%2Bdogedoge.py)

### What problem does this feature solve? [optional]
- Custom post data interface
- Picture rename
- Add download transfer function

```bash
datetime.datetime.now().strftime("%Y%m%d%H%M%S%f") + "." + imghdr.what(sys.argv[i]) 
imghdr.what(sys.argv[i])

new_name = datetime.datetime.now().strftime("%Y%m%d%H%M%S%f") + "." + imghdr.what(None, urllib3.PoolManager().urlopen('GET', sys.argv[i]).data)
                    file_path = path_tmp + new_name
                    with open(file_path, "wb") as temp:
                        temp.write((requests.get(sys.argv[i], timeout=5, verify=False)).content)
```

**Comment by YalandHong** [comment] 2022-01-06 00:58
Duplicate of #2737

**Closed** 2022-01-06 16:33 UTC
