### ISSUE TITLE
Cursor bug: Ctrl + right arrow key behaves odd

### ISSUE THREAD

**Issue by AamerShareef** [marktext/marktext#1251] opened 2019-08-08 12:32 UTC
### Description
Hi Team,
Found a bug related to cursor moving right using `ctrl+right key`.
The `ctrl+left key` works fine. 

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Have multiple lines of data with each line having multiple words.
2. Use ctrl+ right arrow key to move the cursor to different words.
3. Repeat until you reach the end of line and watch the cursor disappear to the bottom of the page.

**Expected behavior:**
ctrl+right should move one word right and when it reaches the end of a line, should move to the next line.

**Actual behavior:**
ctrl+right  moves one word right and when it reaches the end of a line, it does not move to the next line but jumps to the bottom of the page.

![bug2](https://user-images.githubusercontent.com/16585597/62703176-82d01a80-b9e0-11e9-9fc1-2981a2fd8855.gif)

**Link to an example: [optional]**

### Versions

- Mark Text: 0.15.0
- Operating system: Windows

**Comment by adrienbeau** [comment] 2019-08-08 15:34
Actually, the problem occurs when the document contains a **list with checkboxes**.

Without checkboxes, Ctrl-Right works fine throughout titles, paragraphs, lists, tables, etc.

However, when the cursor is at the start of the last word *before* a checkbox list, Ctrl-Right skips over the list and goes straight to the end of the document.

Similarly, as described by AamerShareef, when the cursor is at the start of the last word of a checkbox list item, Ctrl-Right goes straight to the end of the document.

If the cursor is positioned after the checkbox list, Ctrl-Right works fine again.

**Comment by fxha** [comment] 2019-08-09 18:29
I'll mark this issue as bug but it need further investigation because I can only reproduce this issue with task list text ending with a dot.

**Comment by Jocs** [comment] 2019-08-17 00:24
@fxha Me too, the cursor will go to the end of document when the checkbox ends with `.`.

**Comment by Jocs** [comment] 2019-09-27 07:11
@fxha I can not reproduce this issue any more, can you confirm this, if this issue is no longer existed, we can close it.

**Closed** 2019-09-27 10:57 UTC
Labels: 🐛 bug, 🦏  list block
