### ISSUE TITLE
Italic bold (***xxx***) not recognized

### ISSUE THREAD

**Issue by chmike** [marktext/marktext#512] opened 2018-10-16 13:18 UTC
### Description

[Description of the bug or feature]

### Steps to reproduce

Type \*\*\*bla bla*** 

**Expected behavior:** [What you expected to happen]
Should display ***bla bla*** as in github.

**Actual behavior:** [What actually happened]
Display \*\*\*bla bla*** 

### Versions

- Mark Text: 0.12.25
- OS: Ubuntu 18.04

**Comment by fxha** [comment] 2018-10-16 14:52
This has been already fixed and is a duplicate of #370.

**Closed by fxha** 2018-10-16 14:52 UTC
