### ISSUE TITLE
[Question] How to retain a blank line

### ISSUE THREAD

**Issue by LosikiS** [marktext/marktext#1786] opened 2019-12-03 04:57 UTC
### Question description

I want to retain a blank line, But it will be formatted automatically when I switch to another file.
Was it designed this way specially?
![b](https://user-images.githubusercontent.com/33153388/70021523-f9b2a400-15cb-11ea-8f10-13810c9936c0.gif)
What should I do to retain a blank line?
Thank you!

**Comment by kureus** [comment] 2019-12-06 15:17
Yes, this behaviour is currently intentional. Consecutive empty lines are removed by the markdown parser. See the discussion on this here https://github.com/marktext/marktext/issues/1354

**Comment by fxha** [comment] 2019-12-07 22:00
@LosikiS You can insert `<br>` to force a line break and I guess non-breaking spaces should also work.

**Comment by fxha** [comment] 2019-12-07 22:37
Closing this as duplicate of #1354.

**Closed by fxha** 2019-12-07 22:37 UTC
