### ISSUE TITLE
Right Alt/"Alt gr" doesn't work on macOS

### ISSUE THREAD

**Issue by 12people** [marktext/marktext#2645] opened 2021-10-04 12:49 UTC
### Description

I use a Czech keyboard configuration on macOS. I use the right Alt key (sometimes referred to as "alt gr") to write certain symbols. For example, the hashtag key (#) for titles, which I get using this key + 3. Or the * symbol, which I get using this Alt + 8.

This works for me in **every** other app that I've tried, and I'm using these shortcuts right now as I write this bug report.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Switch macOS keyboard layout to Czech. 
2. Open up Mark Text.
3. Type Right alt + 3.

**Expected behavior:**
The line type should switch to heading mode, as it would when typing #.

**Actual behavior:**
Nothing happens.

### Versions

- Mark Text version: 0.16.3
- Operating system: macOS Big Sur 11.6

**Comment by ninpnin** [comment] 2021-11-10 12:35
I am having the same issue. Same Mark Text version, Swedish keyboard, M1 mac, Big Sur 11.5.

**Comment by Xample** [comment] 2021-11-23 12:03
Same issue here Swiss French keyboard, Big Sur 11.6.1

**Comment by cervthecoder** [comment] 2021-12-01 20:36
It doesn't work for me either

**Comment by DYH-Hong** [comment] 2021-12-17 00:51
Duplicate of #2235

A PR has been linked to that issue, so please report your problems and check the discussion there.

**Closed** 2022-01-29 14:14 UTC
