### ISSUE TITLE
Build fails with Nodejs 13

### ISSUE THREAD

**Issue by alerque** [marktext/marktext#2061] opened 2020-04-23 12:03 UTC
Building 0.16.1 dies completely with Node > 12. 12 works fine but 13 is a no go.

```
$ node .electron-vue/build.js && electron-builder --dir
 ___              __                        __                       ___       __
/\_ \       __   /\ \__     ____           /\ \       __  __   __   /\_ \     /\ \
\//\ \    / ,.`\ \ \ ,_\   / ,__\  _______ \ \ \____ /\ \/\ \ /\_\  \//\ \    \_\ \
  \_\ \_ /\  __/  \ \ \/  /\__, `\/\______\ \ \  ,. \\ \ \_\ \\/\ \   \_\ \_ /\ ,. \
  /\____\\ \____\  \ \ \_ \/\____/\/______/  \ \____/ \ \____/ \ \ \  /\____\\ \____\
  \/____/ \/____/   \ \__\ \/___/             \/___/   \/___/   \/_/  \/____/ \/___ /
                     \/__/
  \ building main process
  \ building renderer process

   ERROR  failed to build main process

    Hash: b71b177045158b3bd1b0
    Version: webpack 4.42.0
    Time: 4910ms
    Built at: 04/23/2020 2:52:51 PM
          Asset     Size  Chunks         Chunk Names
        main.js  3.9 KiB       0         main
    main.js.map  1.6 KiB       0  [dev]  main
    Entrypoint main = main.js main.js.map
    [0] ./src/main/index.js 2.94 KiB {0} [built] [failed] [1 error]

    ERROR in ./src/main/index.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: /home/caleb/projects/aur/marktext/src/marktext-0.16.1/babel.config.js: Error while loading config - Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
    Require stack:
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/@babel/preset-env/lib/index.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/babel.config.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/@babel/core/lib/config/files/module-types.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/@babel/core/lib/config/files/configuration.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/@babel/core/lib/config/files/index.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/@babel/core/lib/index.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/babel-loader/lib/index.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/loader-runner/lib/loadLoader.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/loader-runner/lib/LoaderRunner.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/webpack/lib/NormalModule.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/webpack/lib/NormalModuleFactory.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/webpack/lib/Compiler.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/webpack/lib/webpack.js
    - /home/caleb/projects/aur/marktext/src/marktext-0.16.1/.electron-vue/build.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
        at Function.Module._load (internal/modules/cjs/loader.js:835:27)
        at Module.require (internal/modules/cjs/loader.js:1012:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at Object.<anonymous> (/home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
        at Module._compile (internal/modules/cjs/loader.js:1123:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
        at Module.load (internal/modules/cjs/loader.js:972:32)
        at Function.Module._load (internal/modules/cjs/loader.js:872:14)
        at Module.require (internal/modules/cjs/loader.js:1012:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at Object.<anonymous> (/home/caleb/projects/aur/marktext/src/marktext-0.16.1/node_modules/@babel/preset-env/lib/index.js:29:44)
        at Module._compile (internal/modules/cjs/loader.js:1123:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
        at Module.load (internal/modules/cjs/loader.js:972:32)
        at Function.Module._load (internal/modules/cjs/loader.js:872:14)
```

**Comment by fxha** [comment] 2020-04-23 19:41
Duplicate of #2056.

**Closed by fxha** 2020-04-23 19:41 UTC
