### ISSUE TITLE
Open with last opened projects, close all tabs and open URL links

### ISSUE THREAD

**Issue by pp611** [marktext/marktext#437] opened 2018-07-24 02:35 UTC
Really excited to find this app. Really want to replace Evernote with it.  Had a few questions.

### Description
 I am trying to do the following things but could not figure out the way to do so
1. Every time when the app is opened, open the last opened projects with the same size and locations on the screen
2. A menu item and shortcut to close all tabs (or all tabs except the current edited one)
3. Open URL links in the default browser

Are these features available? If not can them be some feature requests?

Also ran into some problems which may or may not be bugs.
a. The content does not change when I click different tab.
b. When the file is changed outside, could not find a way to refresh the content window

### Steps to reproduce

Issue a) seems be fixed when restarting the app. b) can be reproduced by having another editor editing and saving the changes.

### Versions

- Mark Text:
- OS: MacOS 10.13.6

**Comment by Jocs** [comment] 2018-07-24 02:43
>Every time when the app is opened, open the last opened projects with the same size and locations on the screen

We have not this feature now, #386 

>A menu item and shortcut to close all tabs (or all tabs except the current edited one)

You can find this function in sidebar, `close all` and `save all` icons.

>Open URL links in the default browser

Same as #425 

>a. The content does not change when I click different tab.

This maybe a bug, but we need more information about it, you can submit a issue about this, and give more info and gif picture.

>b. When the file is changed outside, could not find a way to refresh the content window

Yes, this maybe a new feature that we have not implemented.

**Comment by pp611** [comment] 2018-07-24 03:46
> a. The content does not change when I click different tab.
This maybe a bug, but we need more information about it, you can submit a issue about this, and give more info and gif picture.

For example, open `file_1.md`, the content window shows the content of `file_1.md`, then open `file_2.md`, a new tab `file_2.md` is added at the top bar, but the content window still shows the content of `file_1.md`. Clicking between `file_1.md` and `file_2.md`, the content window does not change. 

The problem goes away when the app is restarted. However, I could not reproduce the problem in recent sessions so no pictures can be attached.

<img width="567" alt="screen shot 2018-07-23 at 20 38 33" src="https://user-images.githubusercontent.com/12554834/43115394-8f42170e-8eb8-11e8-955f-f729b24ccbe6.png">

#Another issue:# My usages is to open an existing project every time I open the app. Most of the time I view and edit the files in the project. Even new file is created within the project. However an untitled new file is always created and the app pops up a dialog to prompt if the file needs to be saved every time the app is closed, even though the file is never edited.

**Comment by fxha** [comment] 2018-07-24 08:55
> The problem goes away when the app is restarted. However, I could not reproduce the problem in recent sessions so no pictures can be attached.

I cannot reproduce the issue too.

> Another issue: My usages is to open an existing project every time I open the app. Most of the time I view and edit the files in the project. Even new file is created within the project. However an untitled new file is always created and the app pops up a dialog to prompt if the file needs to be saved every time the app is closed, even though the file is never edited.

Duplicate of #387 and #422

**Comment by pp611** [comment] 2018-07-24 21:16
The problem re-appeared today. Here are the screen captures:

<img width="815" alt="screen shot 2018-07-24 at 11 19 24" src="https://user-images.githubusercontent.com/12554834/43166503-9101806e-8f4b-11e8-9274-6f0750e9b6a1.png">
<img width="855" alt="screen shot 2018-07-24 at 11 19 45" src="https://user-images.githubusercontent.com/12554834/43166510-947691c6-8f4b-11e8-9197-2a9fa7c8c8f6.png">

As you can see I click different tab, but the same content. 

But restarting the app did not solve the problem this time, all files opened display empty when the app was restarted. This happened with several restart before the content was displayed right

<img width="706" alt="screen shot 2018-07-24 at 11 35 18" src="https://user-images.githubusercontent.com/12554834/43166656-fba01de0-8f4b-11e8-8138-949b936403f9.png">

**Comment by Jocs** [comment] 2018-07-25 02:31
Maybe we need a minimal use case that can reproduce the problem so that we can solve the problem faster.

**Comment by fxha** [comment] 2019-05-25 14:31
Closing this issue in favour of #988. The problems above are already fixed in v0.14.0.

**Closed by fxha** 2019-05-25 14:31 UTC
