### ISSUE TITLE
Find and replace doesn't work in source code mode

### ISSUE THREAD

**Issue by theoryshaw** [marktext/marktext#2122] opened 2020-05-19 18:42 UTC
### Description

Find and replace doesn't work in source code mode.
Video shows the apparent bug
https://www.dropbox.com/s/a0zyjfcyctilolv/ijT9jOAlV2.mp4?dl=0

- [x] Can you reproduce the issue? 

### Steps to reproduce

See video 

### Versions

- Mark Text: 0.16.1
- Operating system: Windows 10

**Comment by fxha** [comment] 2020-05-21 10:56
Related: #1431 #1329 #1140 #781

**Comment by fxha** [comment] 2020-06-07 00:06
Thank you for reporting the issue. We noticed that this is a duplicate of #1864. You may want to subscribe there for further updates.

**Closed by fxha** 2020-06-07 00:06 UTC
Labels: :beetle: pri/low, :unicorn: feature request
