### ISSUE TITLE
How can I setting the marktext  "show sidebar "when opening it,I dont want to set this item everytime I use it. thanks a lot!

### ISSUE THREAD

**Issue by xj20305** [marktext/marktext#2900] opened 2022-01-18 08:52 UTC

**Comment by YalandHong** [comment] 2022-01-19 01:44
Duplicate of #2378, which has been merged into #1274

**Comment by fxha** [comment] 2022-01-21 16:01
We haven't currently support for view state, but you can enable this by default via [hidden settings](https://github.com/marktext/marktext/blob/master/docs/PREFERENCES.md#view) that may be removed later. This feature should be added with our workspaces design later this year.

**Closed by fxha** 2022-01-21 16:01 UTC
