### ISSUE TITLE
Unexpected error: Cannot destructure property `windowId` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by akavel** [marktext/marktext#1520] opened 2019-10-23 18:43 UTC
### Description

An unexpected error occurred in the main process.

I woke my computer from sleep, and was greeted with a window with the message like below. Please note that a file on a Keybase virtual disk (KBFS) is open in the file — I guess this might potentially be relevant given that there's "FS" in the exception message. 

### Stack Trace

```
TypeError: Cannot destructure property `windowId` of 'undefined' or 'null'.
    at bn._shouldIgnoreEvent (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:328872)
    at FSWatcher.<anonymous> (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:327267)
    at FSWatcher.emit (events.js:194:13)
    at FSWatcher.emitWithAll (C:\Program Files\Mark Text\resources\app.asar\node_modules\chokidar\index.js:487:8)
    at awfEmit (C:\Program Files\Mark Text\resources\app.asar\node_modules\chokidar\index.js:552:14)
    at C:\Program Files\Mark Text\resources\app.asar\node_modules\chokidar\index.js:674:9
    at FSReqCallback.oncomplete (fs.js:164:5)
```

### Version

Mark Text: v0.15.0
Operating system: Windows_NT x64 10.0.18362 (win32)

**Comment by fxha** [comment] 2019-10-23 20:27
Please update to version 0.15.1 to solve this issue. Duplicate of #1284.

**Closed by fxha** 2019-10-23 20:27 UTC
