### ISSUE TITLE
Has to drag images to the edit area

### ISSUE THREAD

**Issue by SuperAllenYao** [marktext/marktext#1207] opened 2019-07-31 01:47 UTC
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step] open a file
2. [Second step] drag an image to Mark Text window
3. [and so on...] 

**Expected behavior:** image inserted

**Actual behavior:** image not inserted

**Link to an example: [optional]** 
It has to drag the images to the editor area, and then images successfully insert into the file.

### Versions

- Mark Text: 0.15.0-rc2
- Operating system: macOS 10.14.6

**Comment by liziqiang** [comment] 2019-07-31 02:17
expect this feature too~

**Comment by Jocs** [comment] 2019-07-31 02:54
@liziqiang The new version will support drag and insert image before/after paragraph.

**Comment by fxha** [comment] 2019-07-31 15:45
The problem with "just" insert an image is the position we should insert the image. The current solution as of v0.15.x is to allow the user to select a paragraph to insert to while dropping. Another option would be the last cursor position but inline images are currently not supported (#1094). I think the current solution is currently sufficient?

**Comment by Jocs** [comment] 2019-07-31 16:06
> Another option would be the last cursor position but inline images are currently not supported (#1094). I think the current solution is currently sufficient?

At present, it is enough, because we now have the image on `block` display instead of `inline`. After adding the inline image, add the drag and drop to insert it into the specified cursor.

**Comment by fxha** [comment] 2019-08-10 15:52
What's the status of this issue. Dragging the image to an undefined position is undefined and so this is the expected behavior?! @SuperAllenYao Could you please explain what you expect when dragging the image outside the editor area?

**Comment by SuperAllenYao** [comment] 2019-08-10 17:38
When I dragging an image to Mark-text’s window, I’ll expect the image insert into the cursor’s location.But the actual behavior is I have to drag the image to the editor area.

**Comment by fxha** [comment] 2019-08-12 19:09
Blocked due #1094.

**Comment by fxha** [comment] 2019-10-26 19:10
Closing the issue because you can insert the image before or after a paragraph in v0.16.0.

**Closed by fxha** 2019-10-26 19:10 UTC
Labels: :unicorn: feature request
