### ISSUE TITLE
Some Latex code can't be valid.

### ISSUE THREAD

**Issue by SouthernWolf123** [marktext/marktext#2868] opened 2022-01-11 04:59 UTC
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. type $$, and enter. so that I can type latex.
2. type 
```latex
\begin{align} 
& 1+2+3 \\
=&3+3 \\
=&6
\end{align}
```
3. then it says invaild

**Expected behavior:**

 1+2+3
=3+3
=6
**Actual behavior:**

\<Invalid Mathematical Formula\>

### Versions

- MarkText version:0.16.3
- Operating system:win10 LTSC

**Comment by DYH-Hong** [comment] 2022-01-11 10:28
Dup of #2573

**Comment by fxha** [comment] 2022-01-11 20:52
Closing as I cannot reproduce this issue with our latest develop version (we updated KaTeX in December).

**Closed by fxha** 2022-01-11 20:52 UTC
