### ISSUE TITLE
Markdown syntax inside HTML tags (CommonMark spec)

### ISSUE THREAD

**Issue by barro350** [marktext/marktext#2308] opened 2020-08-19 00:01 UTC
### Describe your feature request

[CommonMark spec](https://spec.commonmark.org/0.29/#example-122) prescribes that one may use Markdown syntax inside a HTML tag by separating Markdown paragraphs with the HTML tags by newlines:

```markdown
<div style="color:red;">

*Markdown*

</div>
```

This should be rendered in HTML to:

```html
<div style="color:red;">
<p><em>Markdown</em></p>
</div>
```

It would be great if Mark Text can handle this case so that the WYSIWIG mode supports CommonMark in a more faithful way.

**Comment by wundrweapon** [comment] 2020-08-31 23:16
Perhaps Mark Text can depend on an existing CommonMark-compliant renderer

**Comment by DYH-Hong** [comment] 2021-12-20 02:52
Duplicate of #1764

**Closed** 2021-12-29 04:00 UTC
