### ISSUE TITLE
Code formatting/indentation not maintained while pasting 

### ISSUE THREAD

**Issue by prash-kr-meena** [marktext/marktext#1963] opened 2020-03-05 14:36 UTC
### Description
- [ x] Can you reproduce the issue? 

### Steps to reproduce

1. Create a `.md` file and then create a code block in it, i am using the `java` language.
2. Now paste [this code](https://www.cs.utexas.edu/~scottm/cs307/javacode/codeSamples/FilterExample.java) in the code block
3. Now you will see that the code is correctly pasted in the code block, but the issue is when you copy the cod in this code-block and try to paste it anywhere. 
4. You will find after pasting it doesn't have any formatting at all.

**Expected behavior:**
It should have pasted what it looks like in the code block

**Actual behavior:**
pasting without any formatting/indentation

### Versions

- Mark Text: **v0.15.1**
- Operating system: **10.15.3**

**Comment by fxha** [comment] 2020-03-10 21:46
Thank you for reporting the issue. We noticed that this is a duplicate of #942 that is already fixed in our latest release candidate. You can download the latest release candidate from Github releases.

**Closed by fxha** 2020-03-10 21:46 UTC
