### ISSUE TITLE
Feature Request: Separate font options for Headings and Paragraphs

### ISSUE THREAD

**Issue by ctjlewis** [marktext/marktext#2362] opened 2020-10-15 21:27 UTC
### Describe your feature request
The font options as they exist now are very useful, but it would be extremely nice to have separate font settings for headings and paragraphs.

A big thanks to all maintainers - this is one of the nicest FOSS editors I've seen so far, it's an absolute delight to use.

**Comment by brainchild0** [comment] 2020-10-24 15:30
Probably related to (or perhaps duplicate of) #174.

**Closed** 2022-01-23 08:20 UTC
