### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by wang93wei** [marktext/marktext#2017] opened 2020-03-28 18:22 UTC
### Describe your feature request

Hope to support multiple languages

### What problem does this feature solve? [optional]

Can help non-native English speakers get started using it faster.

**Comment by fxha** [comment] 2020-03-29 12:06
Thank you for reporting the issue. We noticed that this is a duplicate of #138. You may want to subscribe there for further updates.

**Closed by fxha** 2020-03-29 12:06 UTC
