### ISSUE TITLE
Change Delete to Discard in dialogue box

### ISSUE THREAD

**Issue by sahil48** [marktext/marktext#469] opened 2018-08-16 18:14 UTC
### Description

When I exit out of marktext, and marktext asks me if I want to save a file, the last option says "Delete", which to me, means that the app would delete the file rather than not save the changes made since the file was last saved. Change the dialogue box to match similar apps like visual studio code.

**Expected behavior:**
When asked "Do you want to save the changes you made to ______, I want the button options to be:

Save    Don't Save/Discard     Cancel

**Actual behavior:**

I see the options

Save    Cancel    Delete

**Comment by fxha** [comment] 2018-08-18 14:05
Duplicate of #388 and already fixed but not released. The button text has been amended to `Don't save`.

**Closed by fxha** 2018-08-18 14:05 UTC
