### ISSUE TITLE
Control-P fast file open dialog

### ISSUE THREAD

**Issue by dessalines** [marktext/marktext#646] opened 2019-01-14 08:49 UTC
### Describe your feature request

It'd nice to have a fast open dialog like typora, vscode or sublime, using control-P . This could draw a list of files from recently opened, and the current folder.

Control-P for print isn't too useful nowadays.

**Comment by fxha** [comment] 2019-01-14 17:08
Duplicate of #581

**Closed by fxha** 2019-01-14 17:08 UTC
