### ISSUE TITLE
An error occurred after changing the shortcut key

### ISSUE THREAD

**Issue by iamdzk** [marktext/marktext#3102] opened 2022-03-06 14:21 UTC
### Description

An error occurred after changing the shortcut key.
The modified `keybinding.json` file contains the following contents: 
```json
{
  "tabs.switch-to-tenth": "",
  "tabs.switch-to-first": "",
  "tabs.switch-to-second": "",
  "tabs.switch-to-third": "",
  "tabs.switch-to-fourth": "",
  "tabs.switch-to-fifth": "",
  "tabs.switch-to-sixth": "",
  "tabs.switch-to-seventh": "",
  "tabs.switch-to-eighth": "",
  "tabs.switch-to-ninth": "",
  "paragraph.heading-1": "ctrl+1",
  "paragraph.heading-2": "ctrl+2",
  "paragraph.heading-3": "ctrl+3",
  "paragraph.heading-4": "ctrl+4",
  "paragraph.heading-5": "ctrl+5",
  "paragraph.heading-6": "ctrl+6"
}
```

### Stack Trace

```
Error: Invalid state: all arguments must be non-null.
    at Object.register (D:\app\marktext\resources\app.asar\node_modules\@hfelix\electron-localshortcut\src\electron-localshortcut.js:167:11)
    at Object.registerKeyHandlers (D:\app\marktext\resources\app.asar\dist\electron\main.js:2:288839)
    at Object.addEditorMenu (D:\app\marktext\resources\app.asar\dist\electron\main.js:2:295113)
    at Xt.createWindow (D:\app\marktext\resources\app.asar\dist\electron\main.js:2:254198)
    at Object._createEditorWindow (D:\app\marktext\resources\app.asar\dist\electron\main.js:2:302982)
    at App.<anonymous> (D:\app\marktext\resources\app.asar\dist\electron\main.js:2:300927)
    at App.emit (node:events:394:28)
```

### Version

MarkText: v0.17.0
Operating system: Windows_NT x64 10.0.19044 (win32)

**Comment by fxha** [comment] 2022-03-06 21:34
Duplicate of https://github.com/marktext/marktext/issues/3074.

**Closed by fxha** 2022-03-06 21:34 UTC
