### ISSUE TITLE
Windows portable package ?

### ISSUE THREAD

**Issue by Laezylion** [marktext/marktext#369] opened 2018-06-19 05:35 UTC
### Description

A windows portable package, enabling users to use MarkText without installing

### Steps to reproduce

Non applicable.

**Expected behavior:** being able to download a zip file, decompress it, and launch marktext.exe directly from there.

**Actual behavior:** Not able to install on a company computer, but still have plenty of documentation to write ...

**Link to an example:** www.portableapps.com

### Versions

- Mark Text: latest please :D
- OS: Windows

**Comment by fxha** [comment] 2018-06-19 15:01
Thanks @Laezylion for the suggestion. I'm assuming you mean a zip file which you can extract and just run?

At the moment you can extract the setup and execute the binaries but it use the appdata to save user configuration and the application crashes if you check for updates.

**Comment by Laezylion** [comment] 2018-06-20 06:51
Hello Felix !

Yes, that's exactly the aim.
I'll give a shot to the extraction, but I'm almost sure the company policy
will block it ...
Worst case I'll make the extraction at home, and take it to work with a usb
stick.
I'll deactivate the update feature just to be sure ...

But I guess most of people using marktext are not sysadmins and able to do
all of this, and that's why I opened an issue ...
Let me know if you plan to add it or not ...

Thanks !





Oudin Manuel
+33 06 28 83 30 40

5 Avenue Emile Haquin
54180 Heillecourt

2018-06-19 17:02 GMT+02:00 Felix Häusler <notifications@github.com>:

**Comment by fxha** [comment] 2018-06-20 18:17
@Laezylion The issue is already marked as a feature request but I don't have time right now to implement the following:

- disable update menu item if `resources/app-update.yml` not exists
- functionality to load settings from a custom folder
  - CLI option to load settings from a custom folder
  - if `.portable` file exists load settings from a local folder

**Comment by fxha** [comment] 2018-10-14 12:50
@Laezylion We added a portable Windows application in your latest pre-release. Available under releases with the filename `marktext-0.13.43.exe`. It's a single executable which can run on both 32- and 64-bit Windows.

**Closed** 2018-10-25 04:05 UTC
Labels: feature request, fixed but not released, need discuss, windows
