### ISSUE TITLE
Always need to be saved

### ISSUE THREAD

**Issue by gxyzjs** [marktext/marktext#912] opened 2019-04-11 02:30 UTC
### Description

Open a file, then close it without change, the app asks you to save and notices that the file changed. In v0.13.65, this problem doesn't occur. BTW, `preference.md` of marktext doesn't have this problem.
- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
open a file.
2. [Second step]
close it without change.
3. [and so on...]

**Expected behavior:**
The file will be closed directly.

**Actual behavior:**
A dialog asks you to save.

**Link to an example: [optional]**

### Versions

- Mark Text: v0.14.0-rc.1
- Operating system: macOS Majave 10.14.4

**Comment by fxha** [comment] 2019-04-11 19:38
Yes that may be possibly because we format the markdown document. Could you please open the file and save it as separate file and check the differences?

**Comment by gxyzjs** [comment] 2019-04-11 22:47
@fxha If there is a blank line at the end of the document, it won't do anything, otherwise it will insert a blank line.

**Comment by Jocs** [comment] 2019-10-30 15:12
>If there is a blank line at the end of the document, it won't do anything, otherwise it will insert a blank line.

Do you mean no need the last blank line?

**Comment by gxyzjs** [comment] 2019-10-31 00:07
All right, the last blank does't matter.

**Comment by fxha** [comment] 2019-11-01 16:15
@Jocs We could add an option to always add an ending newline or that no newline should exist.

**Comment by Jocs** [comment] 2019-11-01 16:37
>We could add an option to always add an ending newline or that no newline should exist.

I think this is not the problem, as you already mentioned, because we format the markdown when we open the markdown file. so it marked as changed. I have fixed this problem in #1564 , but it will also format/beautify the opened file, when continue  edit this file.

I prefer to remove this last empty ending line.

**Comment by fxha** [comment] 2019-11-02 14:37
@Jocs I think, however, that the new line is the core issue here because we always add a newline at the ending. Adding an option to analyse this or manually set a preferred option would solve the issue. Another problem is that cursor changes are also recognized as file change. Disabling automatically formation is currently a won't fix and #1570 feels not right because it defers the problem. If I have some time tomorrow I'll implement a basic check for this.

**Comment by Jocs** [comment] 2019-11-02 15:18
>I think, however, that the new line is the core issue here because we always add a newline at the ending. Adding an option to analyse this or manually set a preferred option would solve the issue.

I prefer not to add the last blank line, no need to add a setting option.

>Another problem is that cursor changes are also recognized as file change. 

Yes, I also found this, but it's difficult to distinguish which click will modify the content states(blocks), so I emit changes every time after click.

>. If I have some time tomorrow I'll implement a basic check for this.

Ok, :+1:

**Comment by Jocs** [comment] 2019-11-03 16:59
@fxha This problem is not only caused by the last blank line, but also by some blank lines in the middle of the text.

For example:

we'll format markdown bellow:

```md
foo
### heading 3
```

to

```md
foo

### heading 3
```

we'll also format the content, if user open a non standard markdown file.

**Comment by adrienbeau** [comment] 2019-11-04 09:43
Whether files should end-up with a "blank line" is a very old debate.

It depends on whether you consider the "end-of-line" character as a *separator* between lines, or if you consider a file as a collection of strings that are *finished* by the "end-of-line" character.

In the first case, it looks like having the "end-of-line" character at the end of the file is a mistake (there is a "final blank line" because of the last separator). In the second case, it looks like *not* having the "end-of-line" character is a mistake (the final line in the file is "incomplete").

This debate can notably be seen between Windows (which is more for the "end-of-line" separator) and Unix (which is firmly for the "end-of-line" at the end of every line).

I think this should be a setting in Mark Text. In particular, not having a final "end-of-line" character at the end of my `.md` files is going to be a bother with my other text tools.

**Comment by fxha** [comment] 2019-11-04 19:00
> I think this should be a setting in Mark Text.

@adrienbeau I already added an option for this to ensure a single final newline, none or allow multiple ones.

> This problem is not only caused by the last blank line, but also by some blank lines in the middle of the text.

That's at least for now a won't fix for me because it's doesn't follow the official specification and is pure esthetic. We could improve this of tables but not fixing wrong syntax makes no sense to me.

**Closed** 2019-11-06 17:52 UTC
Labels: 🦋 optimization

**Comment by bencooling** [comment] 2022-05-01 22:29
0.71.1 still has this problem
