### ISSUE TITLE
Save image to custom relative directory

### ISSUE THREAD

**Issue by jonejkim** [marktext/marktext#2317] opened 2020-08-27 06:34 UTC
### Describe your feature request

I would like to request a feature that allows automatically saving pasted/inserted images into a designated relative path to the current file being edited. So far it doesn't look like MarkText supports this feature.

For example, while editing `myfile.md`, if i inserted some image from clipboard into this file, i would get the image automatically saved into a relative path `./.imgs/` to that of `myfile.md`. Saved image would be at `./.imgs/pasted_img.jpg`.
```
.
├── .imgs
│   └── pasted_img.jpg
└── myfile.md
```

### What problem does this feature solve? [optional]

Typora supports this feature. While MarkText looks like a very good alternative, this was a feature that blocked me from migrating over.

### Additional context [optional]

Image Preference Settings in Typora:
![Image Preference Settings in Typora](https://user-images.githubusercontent.com/31741114/91400388-7f713080-e87a-11ea-941a-6e55e025c4de.png)

**Comment by brainchild0** [comment] 2020-08-27 23:07
Is this request the same as in #549?

**Comment by fxha** [comment] 2020-08-28 11:42
Thank you for reporting the issue. We noticed that this is a duplicate of #549. You may want to subscribe there for further updates.

**Closed by fxha** 2020-08-28 11:42 UTC
