### ISSUE TITLE
Copy/paste problem with quote in a Terminal

### ISSUE THREAD

**Issue by Camiyo** [marktext/marktext#2214] opened 2020-06-11 09:51 UTC
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
When I copy some command from Marktext :
![image](https://user-images.githubusercontent.com/11633117/84369005-8d49da80-abd6-11ea-9354-f500dce074fa.png)

2. [Second step]
And I want to paste it (here in a Terminator but I got the same behavior in a classic Terminal)
![image](https://user-images.githubusercontent.com/11633117/84369739-96877700-abd7-11ea-8088-313ecc883f5f.png)

**Expected behavior:**
I can copy the command without the special characters like this in my case 
`git config --global credential.helper "store"`

**Actual behavior:**
When I paste I got 
`git config --global credential.helper &quot;store&quot;`

### Versions

- Mark Text: v0.16.1
- Operating system: Ubuntu 20.04 LTS

**Comment by fxha** [comment] 2020-06-11 21:51
Duplicate of #1821.

**Closed by fxha** 2020-06-11 21:51 UTC
