### ISSUE TITLE
When you click on a title in [TOC], does not go down to the title

### ISSUE THREAD

**Issue by lindXdeep** [marktext/marktext#2668] opened 2021-11-06 12:37 UTC
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. click on title in [TOC]
2. should go down to the title
3. but it moves in place

**Expected behavior:**

i expect it to take me down to the headline

**Actual behavior:**

but it moves in place

**Link to an example: [optional]**

[gif](https://s9.gifyu.com/images/simplescreenrecorder-2021-11-06_14.47.22.gif)

### Versions

- Mark Text version: v0.16.3
- Operating system: ubuntu 20.04

**Comment by YalandHong** [comment] 2021-11-09 02:17
Possible dup of #2261, which is also a dup of #1775

This issue is probably caused by fractional zooming in high DPI. ([comment](https://github.com/marktext/marktext/issues/2261#issuecomment-955628957))

The problem also seems to appear when you search the document, i.e. using Ctrl+F.

*Please close this issue if it helps*. There're way too many duplicate issues in this repo. Thanks!

**Closed** 2021-12-29 04:32 UTC
