### ISSUE TITLE
Ctrl+Z does Ctrl+W, but Ctrl+W does Ctrl+W also

### ISSUE THREAD

**Issue by edi0th** [marktext/marktext#675] opened 2019-02-04 22:20 UTC
Hi !
Im currently using MT v 0.13.65 on Debian 9, and an AZERTY keyboard.
Everytime I press CTRL+Z, it ask me if i'm sure I want to close the document without saving. I'm having stroke attack every time : D

I thought that maybe, the binding were exchange with CTRL+W since i'm on a AZERTY Keyboard, but nope,  CTRL+W also ask me if I want to close the document.

Any ideas why ? : )

**Comment by fxha** [comment] 2019-02-05 13:15
Thanks @edi0th, we had multiple problems with non-US keyboards recently and also an [AZERTY layout issue](https://github.com/marktext/marktext/issues/311#issuecomment-439005822) which has been fixed. Could you please tell us more information about your environment like:

- `setxkbmap -print` and `setxkbmap -query`
- `cd into-marktext-directory && ./marktext --dump-keyboard-layout`

I guess it's a problem with your keyboard language. E.g. I had problems as well with my clean Fedora/GNOME setup because my keyboard language is `de-DE` (also in GNOME settings) but the system (`setxkbmap -query`) reports `en-US`. So I had to manually change the Xorg configuration.

**Comment by edi0th** [comment] 2019-02-05 14:47
Thanks for the answer !

Here is the result of setxkbmap :
```
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(azerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+fr(latin9)+inet(evdev)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

Here is the response for setxkbmap -query :
```
rules:      evdev
model:      pc105
layout:     fr
variant:    latin9
```

Here is for localectl :
```
 System Locale: LANG=fr_FR.UTF-8
       VC Keymap: n/a
      X11 Layout: fr
       X11 Model: pc105
     X11 Variant: latin9
```

And the last one : 
```
Layout: fr,latin9 [0]
Language: fr,latin9 [0]

{
  "KeyA": {
    "unmodified": "q",
    "withShift": "Q"
  },
  "KeyB": {
    "unmodified": "b",
    "withShift": "B"
  },
  "KeyC": {
    "unmodified": "c",
    "withShift": "C"
  },
  "KeyD": {
    "unmodified": "d",
    "withShift": "D"
  },
  "KeyE": {
    "unmodified": "e",
    "withShift": "E"
  },
  "KeyF": {
    "unmodified": "f",
    "withShift": "F"
  },
  "KeyG": {
    "unmodified": "g",
    "withShift": "G"
  },
  "KeyH": {
    "unmodified": "h",
    "withShift": "H"
  },
  "KeyI": {
    "unmodified": "i",
    "withShift": "I"
  },
  "KeyJ": {
    "unmodified": "j",
    "withShift": "J"
  },
  "KeyK": {
    "unmodified": "k",
    "withShift": "K"
  },
  "KeyL": {
    "unmodified": "l",
    "withShift": "L"
  },
  "KeyM": {
    "unmodified": ",",
    "withShift": "?"
  },
  "KeyN": {
    "unmodified": "n",
    "withShift": "N"
  },
  "KeyO": {
    "unmodified": "o",
    "withShift": "O"
  },
  "KeyP": {
    "unmodified": "p",
    "withShift": "P"
  },
  "KeyQ": {
    "unmodified": "a",
    "withShift": "A"
  },
  "KeyR": {
    "unmodified": "r",
    "withShift": "R"
  },
  "KeyS": {
    "unmodified": "s",
    "withShift": "S"
  },
  "KeyT": {
    "unmodified": "t",
    "withShift": "T"
  },
  "KeyU": {
    "unmodified": "u",
    "withShift": "U"
  },
  "KeyV": {
    "unmodified": "v",
    "withShift": "V"
  },
  "KeyW": {
    "unmodified": "z",
    "withShift": "Z"
  },
  "KeyX": {
    "unmodified": "x",
    "withShift": "X"
  },
  "KeyY": {
    "unmodified": "y",
    "withShift": "Y"
  },
  "KeyZ": {
    "unmodified": "w",
    "withShift": "W"
  },
  "Digit1": {
    "unmodified": "&",
    "withShift": "1"
  },
  "Digit2": {
    "unmodified": "é",
    "withShift": "2"
  },
  "Digit3": {
    "unmodified": "\"",
    "withShift": "3"
  },
  "Digit4": {
    "unmodified": "'",
    "withShift": "4"
  },
  "Digit5": {
    "unmodified": "(",
    "withShift": "5"
  },
  "Digit6": {
    "unmodified": "-",
    "withShift": "6"
  },
  "Digit7": {
    "unmodified": "è",
    "withShift": "7"
  },
  "Digit8": {
    "unmodified": "_",
    "withShift": "8"
  },
  "Digit9": {
    "unmodified": "ç",
    "withShift": "9"
  },
  "Digit0": {
    "unmodified": "à",
    "withShift": "0"
  },
  "Space": {
    "unmodified": " ",
    "withShift": " "
  },
  "Minus": {
    "unmodified": ")",
    "withShift": "°"
  },
  "Equal": {
    "unmodified": "=",
    "withShift": "+"
  },
  "BracketRight": {
    "unmodified": "$",
    "withShift": "£"
  },
  "Backslash": {
    "unmodified": "*",
    "withShift": "µ"
  },
  "Semicolon": {
    "unmodified": "m",
    "withShift": "M"
  },
  "Quote": {
    "unmodified": "ù",
    "withShift": "%"
  },
  "Backquote": {
    "unmodified": "œ",
    "withShift": "Œ"
  },
  "Comma": {
    "unmodified": ";",
    "withShift": "."
  },
  "Period": {
    "unmodified": ":",
    "withShift": "/"
  },
  "Slash": {
    "unmodified": "!",
    "withShift": "§"
  },
  "NumpadDivide": {
    "unmodified": "/",
    "withShift": "/"
  },
  "NumpadMultiply": {
    "unmodified": "*",
    "withShift": "*"
  },
  "NumpadSubtract": {
    "unmodified": "-",
    "withShift": "-"
  },
  "NumpadAdd": {
    "unmodified": "+",
    "withShift": "+"
  },
  "Numpad1": {
    "unmodified": null,
    "withShift": "1"
  },
  "Numpad2": {
    "unmodified": null,
    "withShift": "2"
  },
  "Numpad3": {
    "unmodified": null,
    "withShift": "3"
  },
  "Numpad4": {
    "unmodified": null,
    "withShift": "4"
  },
  "Numpad5": {
    "unmodified": null,
    "withShift": "5"
  },
  "Numpad6": {
    "unmodified": null,
    "withShift": "6"
  },
  "Numpad7": {
    "unmodified": null,
    "withShift": "7"
  },
  "Numpad8": {
    "unmodified": null,
    "withShift": "8"
  },
  "Numpad9": {
    "unmodified": null,
    "withShift": "9"
  },
  "Numpad0": {
    "unmodified": null,
    "withShift": "0"
  },
  "NumpadDecimal": {
    "unmodified": null,
    "withShift": "."
  },
  "IntlBackslash": {
    "unmodified": "<",
    "withShift": ">"
  },
  "NumpadEqual": {
    "unmodified": "=",
    "withShift": "="
  },
  "NumpadComma": {
    "unmodified": ".",
    "withShift": "."
  },
  "NumpadParenLeft": {
    "unmodified": "(",
    "withShift": "("
  },
  "NumpadParenRight": {
    "unmodified": ")",
    "withShift": ")"
  }
}


```

**Comment by fxha** [comment] 2019-02-05 16:30
Yes, that looks good. My problem is that I cannot reproduce the issue, not even with `fr,latin9` layout. Are you using a [official binary](https://github.com/marktext/marktext/releases/tag/v0.13.65) or git build? Can you please give `marktext --safe` a try.

**Comment by fxha** [comment] 2019-03-05 15:51
Closing this issue as no further information has been provided. Please reopen if you can give more information.

**Closed by fxha** 2019-03-05 15:51 UTC
