### ISSUE TITLE
Support relative image directory

### ISSUE THREAD

**Issue by ti** [marktext/marktext#549] opened 2018-11-08 10:34 UTC
### drop  image insert by copy it to local  .${filename}.assets/  support
the current version of the marktext is upload to cloud, but in this opensource project,  upload cloud is a danger tings, the new feature of copy it to local  .${filename}.assets/  would be make a greate process

**Comment by Jocs** [comment] 2018-11-08 12:39
We'll add an image manager to manage to local image and uploaded image in the future. User can choose use local image or uploaded image.

User can also use `image upload plugin` when the plugin system supported.

**Comment by fxha** [comment] 2019-08-10 15:58
Please see #1232 when implementing this feature to allow both, a resource directory per markdown file and per directory, controlled by a settings option.

**Comment by HannanAkbar** [comment] 2019-08-17 03:29
I would add that creating a resource directory should be optional, not forced upon.
Maybe show a dialog with `<Move>` `<Move to directory>'.

Slightly cleaner and easier this way. #1279

**Comment by HannanAkbar** [comment] 2019-08-17 03:31
A quick suggestion:

Avoid messing with files/folders as much as possible. That kills the spirit of an editor and ends up in a proprietary format notepad. The best way is to give extensions for any feature which is out of scope, extra, or changes the structure, format, etc.

**Comment by GregHilston** [comment] 2020-02-05 19:08
This is the only feature I think Mark Text is missing to be competitive with VS Code extensions or even Notion.

I'll try to dig through and see if I can be of any assistance, as having this would allow the "self hosting" note takes the ability to easily control their notes.

**Comment by Yichen-Dou** [comment] 2020-03-18 17:48
Please add the feature to save images to the [opend directory]/assets/. For users using private cloud or Git to manage their projects or resources, saving images to a temp folder is such a pain. Thanks

**Comment by redoxmatlab** [comment] 2020-05-06 05:44
Is there any updates on this issue?
I am not sure what "move image to special folder" does?

Thanks

**Comment by elvis-wenhao-wu** [comment] 2020-07-11 15:33
+1. Add image path variable similar to that in Typora, or at least relative path to marktext. This is the only concern that drives me not to change from Typora to marktext at the moment. Once marktext has this feature, then basically it defeats Typora.

**Comment by aifusenno1** [comment] 2020-08-07 09:49
Just curious, even if relative path is supported for image insertion, how do you guys view notes on mobile devices? From my experience with Typora and multiple iOS apps (Pretext, MDNotes and MWeb), storing the entire file tree in iCloud still does not solve the issue. Images are not able to be found with relative path. See [this issue in Typora](https://github.com/typora/typora-issues/issues/3767#issue-674092782) for a little more detail.

**Comment by brainchild0** [comment] 2020-08-27 23:09
I suggest pinning this issue, since duplicates repeatedly are being added.

**Comment by ytianxia6** [comment] 2020-09-16 03:40
Has this problem been solved? I am considering migrating from typora to mark text, but if this problem cannot be solved, I may not be able to migrate.
I often use to edit the wiki library of gitlab. Pictures can only be saved in relative paths.

**Comment by mikewizc** [comment] 2020-09-25 08:59
hi guys, any update of this feature? Such a **Highest-rated** feature is really important.

**Comment by mimavox** [comment] 2020-12-08 19:36
> Just curious, even if relative path is supported for image insertion, how do you guys view notes on mobile devices? From my experience with Typora and multiple iOS apps (Pretext, MDNotes and MWeb), storing the entire file tree in iCloud still does not solve the issue. Images are not able to be found with relative path. See [this issue in Typora](https://github.com/typora/typora-issues/issues/3767#issue-674092782) for a little more detail.

Using MWeb on mobile with Typora on desktop works flawlessly if you set Typora custom folder to` ./media` (which MWeb uses). That way each image is stored in a media subfolder of the current directory and a correct relative path is added to the document.

**Closed** 2020-12-23 22:24 UTC
Labels: :unicorn: feature request

**Comment by fgimian** [comment] 2021-01-08 01:48
Really appreciate the effort on this, but the current implementation is still not quite as good as Typora for the following reasons:

* Mark Text only offers the ability to store all images for multiple Markdown files in a relative directory (e.g. assets), unlike Typora which allows you to create one directory per document (e.g. ./${filename}.assets).  I much prefer the latter approach as it keeps each individual article separate with its own dedicated directory for images.  If you had for example 20 Markdown files, and each had images, these would all be put into a single folder with Mark Text, which makes it harder to move pages to a different location and also leads to a messier filesystem.
* Typora has an option "Use relative path if possible" which is critical.  It will insert a relative path to the file instead of an absolute path.  This means that if you move the document and its images to a different location, images continue to work.  Mark Text only seems to insert absolute paths which makes it very hard to move things around.

Any chance you can improve this feature further to support the points above please?

Thank you so much!
Fotis

**Comment by Merrit** [comment] 2021-01-08 15:36
@fgimian _Exactly_ the points I haven't had time to write up about. Also a big issue for me.

**Comment by fxha** [comment] 2021-01-25 19:58
> Mark Text only offers the ability to store all images for multiple Markdown files in a relative directory

This should be very easy to implement, but it doesn't make things easier - UX wise. My core idea was to implement such features per directory (project) via a custom configuration file, like VSCode, and a session management (#988). Many core features, such as sessions, are blocked because we need to optimize the core engine and due to financially support. Currently, there isn't an active maintainer to solve these issues or take care about new issues. We published two bug fix releases in 2020 with some outstanding features in a few weeks but there was no overall progress on the project. On the pro side, we have a partially working engine internally that should be flexible enough to solve further issues and features, but without any progress in the last year. To sum up, we need some old stuff fixed before continuing on new features, but without any financially support there will only be a few changes in the further. Mark Text was always a community maintained project and for the time being, I'm done from maintaining open-source for free and hope we can continue this awesome project somehow.

> Mark Text only seems to insert absolute paths which makes it very hard to move things around.

A relative path should be used if the file is persistent on disk. Please open an issue with detailed steps to reproduce.

> The editor should really prompt you to save a file if unsaved and an image is dropped rather than defaulting to a central directory. It's so easy for images to get lost with the current system imho and it's an easy thing to miss.

I think you're right, the image management need some overall improvements.

---

@fgimian Could you please open separate issues to address these problems, thanks!

**Comment by fgimian** [comment] 2021-04-16 11:28
Apologies that I kinda forgot about this issue.  I've just created separate issues for each point above.
