### ISSUE TITLE
Failed to install on MAC 0.17.0-rc.1

### ISSUE THREAD

**Issue by ruanhailiang** [marktext/marktext#2963] opened 2022-01-30 11:56 UTC
### Question description

Uncaught Exception:
Error: dlopen(/Applications/MarkText.app/Contents/Resources/app.asar.unpacked/node_modules/keytar/build/Release/keytar.node, 0x0001): tried: '/Applications/MarkText.app/Contents/Resources/app.asar.unpacked/node_modules/keytar/build/Release/keytar.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h')), '/usr/local/lib/keytar.node' (no such file), '/usr/lib/keytar.node' (no such file)
at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1170:18)
at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2027)
at Module.load (node:internal/modules/cjs/loader:982:32)
at Module._load (node:internal/modules/cjs/loader:823:12)
at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
at Module.require (node:internal/modules/cjs/loader:1006:19)
at require (node:internal/modules/cjs/helpers:93:18)
at Object.<anonymous> (/Applications/MarkText.app/Contents/Resources/app.asar/node_modules/keytar/lib/keytar.js:1:14)
at Module._compile (node:internal/modules/cjs/loader:1110:14)

**Comment by YalandHong** [comment] 2022-01-30 13:43
Duplicate of #2953

**Closed** 2022-01-30 14:30 UTC
