### ISSUE TITLE
[feature]  support saving to relative directory when insert image

### ISSUE THREAD

**Issue by Honghe** [marktext/marktext#1794] opened 2019-12-05 12:57 UTC
### Describe your feature request
Add a option which allow saving to relative directory when insert images, like Typora or other editors.
**Marktext**:
![image](https://user-images.githubusercontent.com/1092722/70237359-f7a23e00-17a1-11ea-9763-4c5ad9b1a58c.png)

**Typora**:
![image](https://user-images.githubusercontent.com/1092722/70237503-54055d80-17a2-11ea-9af7-7efd835cc308.png)

### What problem does this feature solve? [optional]
Easy to move texts.

**Comment by fxha** [comment] 2019-12-14 16:25
Thank you for reporting the issue. We noticed that this is a duplicate of #549. You may want to subscribe there for further updates.

**Closed by fxha** 2019-12-14 16:25 UTC
