### ISSUE TITLE
New page 

### ISSUE THREAD

**Issue by BenTearzz** [marktext/marktext#866] opened 2019-04-04 12:49 UTC
### Describe your feature request

Since I really like Mark Text, I think I could use it really well for school. I got really happy when I saw that you exported to .PDF, but it would be nice if you could put a page break. Perhaps this could be done with a regular line break but where it consists of dots or something so that you can tell it apart in the markdown editor.

### What problem does this feature solve? [optional]

Creating documents with content split onto certain pages, useful for school.

**Comment by fxha** [comment] 2019-04-04 14:11
Duplicate of #355.

**Closed by fxha** 2019-04-04 14:11 UTC

**Comment by BenTearzz** [comment] 2019-04-04 14:16
Oh sorry, thought I had looked through the issues but apparently not :/

**Comment by BenTearzz** [comment] 2019-04-04 19:59
I've looked at the duplicate issue, I'm not quite sure if page breaks exists or not after reading that. @fxha

**Comment by fxha** [comment] 2019-04-04 20:16
You can insert HTML/CSS to produce a page break: `<div style="page-break-before: always;"></div>`.

- `page-break-after`
- `page-break-before`

**Comment by CluelessD3v** [comment] 2021-02-10 22:12
> You can insert HTML/CSS to produce a page break: `<div style="page-break-before: always;"></div>`.
> 
> * `page-break-after`
> * `page-break-before`

Sorry necro, but I get an "Empty Html block" when I use that code, any idea?
