### ISSUE TITLE
macOS M1 chip install fail

### ISSUE THREAD

**Issue by zjslqshqz** [marktext/marktext#3180] opened 2022-04-02 00:40 UTC
The arm version cannot be opened after installation, and the x86 version can be used normally. do not know why.

### Versions

- MarkText version:v.0.17.1 [marktext-arm64.dmg](https://github.com/marktext/marktext/releases/download/v0.17.1/marktext-arm64.dmg)
- Operating system: 11.6.4

**Comment by saowu** [comment] 2022-04-07 02:41
I also had the same problem

**Comment by YalandHong** [comment] 2022-04-09 01:04
More info is needed. Please provide screenshot, video or describe how to reproduce your problem.

----

你的问题描述很不详细。请提供更多信息，比如截图、录屏或者具体操作的步骤。

**Comment by YalandHong** [comment] 2022-04-13 01:09
> <img alt="image" width="390" src="https://user-images.githubusercontent.com/42688937/162908362-39e6c7d1-f620-4338-97bc-4ff743e48435.png">
> 
> Same error as mine. I used both .zip and .dmg file to install but they were failed.

Dup of #2983.

From Big Sur 11, macOS prevents you from running untrusted program. Any executable must be codesigned. I believe this issue should affect a lot of programs on macOS, not only MarkText.

**Comment by slaveofcode** [comment] 2022-04-27 09:37
Same problem here on M1 Monterey 12.3.1

**Comment by FlorianLoch** [comment] 2022-06-27 22:59
As mentioned, see https://github.com/marktext/marktext/issues/2983.

Just to also have this here: The binary isn't broken, it's just not signed. Run `xattr -r -d com.apple.quarantine /Applications/MarkText.app` to have macOS not put it in quarantine.

**Comment by Tangroo** [comment] 2022-06-30 14:29
I have the same problem，my macOS is Big Sur 11.2.3 and M1.
But the marktext-x64.dmg is available to me！

**Comment by FlorianLoch** [comment] 2022-06-30 15:32
Everyone will have the same problem because it's nothing about your machine, it's about the binary not being signed. 

For how to circumvent this please see the issue referenced by me above. :)

With x64 Apple applies different rules, that's why this one is working for you.

**Comment by fxha** [comment] 2022-07-02 15:21
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2983. You may want to subscribe there for further updates.

**Closed by fxha** 2022-07-02 15:21 UTC
