### ISSUE TITLE
Unexpected error: Invalid state: all arguments must be non-null.

### ISSUE THREAD

**Issue by yzouag** [marktext/marktext#3093] opened 2022-03-02 12:07 UTC
### Description

An unexpected error occurred in the main process.

The bug comes up when I change the shortcut settings. I set a bunch of short cuts in preference and click save. Then I close marktext and restart it. The program crashes with this error.

### Stack Trace

```
Error: Invalid state: all arguments must be non-null.
    at Object.register (C:\Program Files\MarkText\resources\app.asar\node_modules\@hfelix\electron-localshortcut\src\electron-localshortcut.js:167:11)
    at Object.registerKeyHandlers (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:288839)
    at Object.addEditorMenu (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:295113)
    at Xt.createWindow (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:254198)
    at Object._createEditorWindow (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:302982)
    at Object._openPathList (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:304520)
    at Object._openFilesToOpen (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:303313)
    at App.<anonymous> (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:300903)
    at App.emit (node:events:394:28)
```

### Version

MarkText: v0.17.0
Operating system: Windows_NT x64 10.0.19044 (win32)

**Comment by fxha** [comment] 2022-03-02 20:48
Duplicate of #3083.

**Closed by fxha** 2022-03-02 20:48 UTC
