### ISSUE TITLE
App throws an unexpected error and freezes after I modified a few key bindings in options

### ISSUE THREAD

**Issue by idontwantagirlfriend** [marktext/marktext#3106] opened 2022-03-07 05:25 UTC
### Description

```
An unexpected error occurred in the main process.
```

The app crashed on starting, after I modified a few key bindings in options. 

I saved them correctly and tried them, only to notice that they didn't take effects immediately. As I decided to relaunch the app, it crashed. It hasn't been launching successfully since then. Restarting the app / the pc didn't help. 

- The error screen: 
![error](https://user-images.githubusercontent.com/34613980/156972708-b56f9d34-b837-4490-a1d9-573b9d5fa6e8.png)

- After entering the main screen, it freezes: (Calling preference palette by shortcut didn't work either)
![after](https://user-images.githubusercontent.com/34613980/156972706-6410edd6-c2d7-42e1-8c3c-74b8d695849b.png)

### Stack Trace

```
Error: Invalid state: all arguments must be non-null.
    at Object.register (C:\Program Files\MarkText\resources\app.asar\node_modules\@hfelix\electron-localshortcut\src\electron-localshortcut.js:167:11)
    at Object.registerKeyHandlers (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:288839)
    at Object.addEditorMenu (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:295113)
    at Xt.createWindow (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:254198)
    at Object._createEditorWindow (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:302982)
    at App.<anonymous> (C:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:300927)
    at App.emit (node:events:394:28)
```

### Version

MarkText: v0.17.0
Operating system: Windows_NT x64 10.0.19043 (win32)

**Comment by fxha** [comment] 2022-03-07 16:19
Duplicate of https://github.com/marktext/marktext/issues/3074.

**Closed by fxha** 2022-03-07 16:19 UTC
