### ISSUE TITLE
Import - Pandoc Warning with Pandoc Installed

### ISSUE THREAD

**Issue by briandconnolly** [marktext/marktext#2400] opened 2020-11-23 23:10 UTC
Fedora 33. Pandoc installed.  Import yields a pandoc warning.

?

**Comment by briandconnolly** [comment] 2020-11-27 12:49
Above "pandoc warning" was after a Flathub install.  Via RPM works great.

**Comment by fxha** [comment] 2020-12-29 12:30
Thank you for reporting the issue. We noticed that this is a duplicate of  #2343.

**Closed by fxha** 2020-12-29 12:30 UTC
