### ISSUE TITLE
Unable to Export file containing emojis and formatting. 

### ISSUE THREAD

**Issue by prash-kr-meena** [marktext/marktext#1961] opened 2020-03-04 04:38 UTC
- [x] Can you reproduce the issue?                              

### Steps to reproduce

1. Create a `.md` file open it in source code mode and put my code in it.
2. You have to open it in source code mode then only it can copy other wise you will not be able to even copy the content of the file 
3. After that just go to `files -> export -> HTML/PDF`
4. You will not see any dialogue box  for exporting or saving it as an `.html` or `.pdf` file

[Link to my code](https://pastebin.com/Lp3sJ1pH)

[Kind of similar issue #1748](https://github.com/marktext/marktext/issues/1748)

**Expected behavior:**
It should export it in HTML or PDF, but it does not work with this specific file. 
I have checked other file having emojis and they are exported easily, i don't know what is the issue with this.

**Actual behavior:**
Its not exporting my document in either of `.html` and `.pdf`

### Versions

- Mark Text: `v0.15.1`
- Operating system: **Os Catalina** `10.15.3`

**Comment by fxha** [comment] 2020-03-10 21:49
Thank you for reporting the issue. We noticed that this is a duplicate of #1738 that is already fixed in our latest release candidate. You can download the latest release candidate from Github releases.

**Closed by fxha** 2020-03-10 21:49 UTC
