### ISSUE TITLE
Scrolling does not work with PgUp, PgDn, Arrow Up, Arrow Down keys

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1277] opened 2019-08-16 12:32 UTC
### Description

 Pressing those keys does not activate the scrolling.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open a document
2. Try to use one of those keys

**Expected behavior:**

 The page to scroll up or down
>
**Actual behavior:**

 When using the up or down arrow the cursor just disappears off the screen without the page scrolling.
When using the PageUp or PageDown key MT freezes --> I opened a separate issue for that.

### Versions

- Mark Text: 0.15.0
- Operating system: Linux Mint 19.1 XFCE

**Comment by fxha** [comment] 2019-08-16 15:57
Duplicate of #1119 and #655.

**Closed by fxha** 2019-08-16 15:57 UTC
