### ISSUE TITLE
Enable relative paths for Image folder (imageFolderPath)

### ISSUE THREAD

**Issue by bzass** [marktext/marktext#1891] opened 2020-02-03 23:22 UTC
It would be nice if imageFolderPath setting accepted relative paths (eg. "./Images") so that when user pastes image from the clipboard, it's being automatically copied to the folder relative to edited Markdown file.

Currently, after setting imageFolderPath manually by editing dataCenter.json, images are not copied and  loaded correctly.

**Comment by adrienbeau** [comment] 2020-02-04 14:28
This is a duplicate of #549.

**Closed** 2020-02-06 08:25 UTC
