### ISSUE TITLE
Undo not working

### ISSUE THREAD

**Issue by gfm-r** [marktext/marktext#440] opened 2018-07-25 15:31 UTC
### Description
there is no Undo functionality in the app, I can't Undo anything.

### Versions

- Mark Text:v 0.12.25
- OS:Fedora 28

**Comment by fxha** [comment] 2018-07-25 17:37
Thanks @gfm-r, to undo a action please open the `Edit` menu and click on `Undo`. At the moment the undo shortcut `ctrl+z` is not working on Linux and Windows (see #311). You give not much information about  the issue but I guess it's a duplicate of #311.

Maybe you can give more information about the issue because I do not experience any problems with  undo via menu on Fedora 27.

**Comment by gfm-r** [comment] 2018-07-25 23:50
I found Ctrl+Super+Z works for me as you mentioned here #311.

**Closed** 2018-07-25 23:50 UTC
