### ISSUE TITLE
Can you add more bed support or custom bed support (such as calling Pic-go)

### ISSUE THREAD

**Issue by aiwush** [marktext/marktext#2996] opened 2022-02-09 09:53 UTC
Can you add more bed support or custom bed support (such as calling Pic-go)

**Comment by YalandHong** [comment] 2022-02-09 13:14
FYI, PicGo support (#2890) has been added in 0.17.0

**Comment by Kuronekoo** [comment] 2022-02-15 09:41
> > 仅供参考，自定义图像上传器 ( #2100 ) 和 PicGo 支持 ( #2890 ) 已在 0.17.0 中添加。
> 
> 我不知道发生了什么,我的偏好设置里面显示我没有安装 plcgo,但是我已经在电脑中运行了 picgo。我尝试了分别运行indows和 Macos的两台电脑,都能够复现这个问题.

I have the same problem too


![image](https://user-images.githubusercontent.com/26434287/154035332-dfebe3cd-17cd-47af-b4ff-2dcd7bc13eed.png)

**Comment by fxha** [comment] 2022-03-31 20:38
Thank you for taking the time to report this issue. Based on the stack trace, we'll go ahead and close as a duplicate of #3118.

**Closed by fxha** 2022-03-31 20:38 UTC
