### ISSUE TITLE
Pelican Static Site Gen Image Images support

### ISSUE THREAD

**Issue by VegaDeftwing** [marktext/marktext#1950] opened 2020-03-01 15:46 UTC
### Pelican Static Site Generator Image Support

Pelican (docs.getpelican.com) pages are often made in a modified Markdown. In many cases tags like

```
![Alt Text]({static}/images/whatever.jpg)
```
are used. Documentation for this can be found here:
https://docs.getpelican.com/en/stable/content.html#mixed-content-in-the-same-directory

It would be great if Marktext could recognize these paths and display the images

Currently switching from Typora to Marktext for https://opinionatedguide.github.io/OpinionatedEngineering.html
which uses Pelican and this would make that much easier.

**Comment by fxha** [comment] 2020-06-06 23:48
Thank you for reporting the issue. We noticed that this is a duplicate of #2126 that is more general. You may want to subscribe there for further updates.

**Closed by fxha** 2020-06-06 23:48 UTC
