### ISSUE TITLE
[Question] What is the proper way to add the application icon to desktop file?

### ISSUE THREAD

**Issue by s1291** [marktext/marktext#1650] opened 2019-11-08 00:28 UTC
### Question description
Hello, 
I've downloaded marktext `Appimage` for Ubuntu 18.04. I would like to create a desktop file to launch the application from desktop. But what is the proper way to specify the icon for the app?
Do I have to download manually the logo image and point to it?
```
[Desktop Entry]
Version=0.15.1
Type=Application
Terminal=false
Exec=~/Downloads/marktext/marktext/marktext-0.15.1-x86_64.AppImage
Icon=what should I put here? <<<<<<<<<<<<<<<<<<<<
Name=MarkText
Comment=MarkText yet another Markdown editor
```

**Comment by fxha** [comment] 2019-11-08 14:29
Duplicate of #1291. You can use a `.png` icon from [here](https://github.com/marktext/marktext/tree/develop/resources/icons).

**Closed by fxha** 2019-11-08 14:29 UTC
Labels: :penguin: platform/linux
