### ISSUE TITLE
Github badges not shown after export to html

### ISSUE THREAD

**Issue by Gurran** [marktext/marktext#1017] opened 2019-05-09 05:43 UTC
### Description

When exporting a markdown file containing badges, the badges don't show after export to a .html file.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Take a README.md containing badges (I used [this one](https://raw.githubusercontent.com/microsoft/vscode/master/README.md))
2. Paste into Mark Text
3. Export as .html, then as .pdf

**Expected behavior:**

The output of .html and .pdf should both  contain badges

**Actual behavior:**

Only the .pdf file contains badges

### Versions
- Date: 2019-05-06
- Mark Text: v0.14.0
- Operating system: Windows_NT x64 10.0.17134

**Comment by fxha** [comment] 2019-05-09 16:48
I cannot reproduce this issue. The only issue is that one image cannot be loaded because of a bad request (405 Method Not Allowed):

![mt_badges](https://user-images.githubusercontent.com/22716132/57471047-9907f680-728a-11e9-9748-fc53920f9446.png)

The image shows the exported HTML document and Mark Text.

**Comment by Gurran** [comment] 2019-05-15 06:13
The badges where shown on the PDF file?

**Comment by fxha** [comment] 2019-05-15 18:12
Yes, that's right but you will need an active internet connection during exporting because the image are loaded again.

**Comment by Gurran** [comment] 2019-05-22 06:06
Will give update later today. (12h)

**Comment by fxha** [comment] 2019-08-10 15:43
Closing this issue as no further information has been provided. Please feel free to reopen with more information.

**Closed by fxha** 2019-08-10 15:43 UTC
Labels: :baby_chick: blocked/need info
