### ISSUE TITLE
Images not rendering in pdf images

### ISSUE THREAD

**Issue by RandomAccountt** [marktext/marktext#2219] opened 2020-06-14 14:55 UTC
Hi, it seems that when I paste an image and export a file as PDF, images don't appear in the PDF. Anything I can do about this?

**Comment by JolyonJostar** [comment] 2020-06-14 16:13
me too

**Comment by brainchild0** [comment] 2020-06-16 02:31
The call to `pandoc` may need to be augmented with an option `--resource-path` followed by the name of the directory containing the Markdown file, in order for the call to resolve image paths relative to the document path, as normally desired.

Pandoc has specific semantics oriented around certain complex project structures, but that are sometimes counterintuitive in basic cases.

**Comment by fxha** [comment] 2020-06-16 10:16
Duplicate of #1997.

**Closed by fxha** 2020-06-16 10:16 UTC
