### ISSUE TITLE
Mermaid renders some labels out of their boxes

### ISSUE THREAD

**Issue by afpineda** [marktext/marktext#2606] opened 2021-06-21 17:02 UTC
### Description

When rendering a flow chart with mermaid, some labels lands out of their boxes. See attached image.

- [x] Can you reproduce the issue? yes: `[x]`

### Steps to reproduce

1.  Enter this mermaid fenced code:

```mermaid
graph LR
    rule(" ")
    openpar["("]
    closedpar[")"]
    num("integer_number")
    endr(" ")
    rule --> Y & M & D & HH & SS & MS & MM & WD & MD --> openpar --> num --> closedpar --> endr
    rule --> FOREVER & NEVER & EASTER --> endr
```
2. Let Mark Text render the graph

**Expected behavior:**

All text in a graph's node should fall *inside* it's box

**Actual behavior:**

Part of the text in a graph's node falls *outside* it's box.
Changing zoom size does not fix the issue.
Moving to another theme does not fix the issue.
Changing source mode back and forth does not fix the issue.

![mt_mermaid_bug](https://user-images.githubusercontent.com/74291754/122798266-acd31300-d2c0-11eb-8c35-4855d9dda06a.png)

### Versions

- Mark Text version: 0.16.3
- Operating system: MS Windows 10 Pro,  build 19041.1052

**Comment by csc-chicken** [comment] 2021-06-24 03:40
same as me . i also face this problem ,it's ok to render in typora but not here
![image](https://user-images.githubusercontent.com/66060998/123199108-d36f9480-d4e0-11eb-93dd-957c73fcd7ab.png)

**Comment by QazCetelic** [comment] 2021-12-01 15:15
I also have the same issue
![image](https://user-images.githubusercontent.com/51381523/144260889-8cbf4e01-55cb-49bf-9897-7e43cb8fc672.png)

**Comment by Jocs** [comment] 2022-01-04 16:53
@fxha I can not reproduct this on macOS, can you help test it on Windows.

**Comment by kiyoka** [comment] 2022-02-20 08:33
The problem was reproduced only in Mark Text v0.16.3.
The following results were run on the same machine.
Platform: Windows 10 Pro 21H2 (OS build 19044.1526)

- v0.16.3
![v0 16 3](https://user-images.githubusercontent.com/80378/154834780-861a0e20-036a-41db-929c-09550816d26c.png)

- v0.17.0-rc1
![v0 17 0-rc1](https://user-images.githubusercontent.com/80378/154834799-797f5f81-7818-454a-8eb7-64168e4d76b8.png)

**Comment by fxha** [comment] 2022-02-20 11:37
Most likely an bug in mermaid that was fixed by updating dependencies.

**Closed by fxha** 2022-02-20 11:37 UTC
Labels: 🐛 bug, :whale: help wanted
