### ISSUE TITLE
can't upload the picture from clipper

### ISSUE THREAD

**Issue by bluesatchel** [marktext/marktext#3326] opened 2022-06-21 17:24 UTC
### when i want to upload the picture from clipper using picgo ,i have to save it as a .jpg file before,and the markText can upload it.
i hope that markText can  achieve this function like Typora on this aspect.
thanks for your contribution

best wishs

**Comment by YalandHong** [comment] 2022-07-07 00:38
Duplicate of #2915

**Closed** 2022-08-25 07:11 UTC

**Comment by bluesatchel** [comment] 2022-08-25 07:12
期待下一个版本
Looking forward to the next version

**Comment by beierzhijin** [comment] 2022-09-22 05:10
> 期待下一个版本 Looking forward to the next version

I have rebuilt the fixed version from [@Jakentop](https://github.com/Jakentop)-fix Failure when uploading clipboard images with PicGo https://github.com/marktext/marktext/issues/3360.
download from my fork: https://github.com/beierzhijin/marktext/releases/tag/v0.17.1
