### ISSUE TITLE
The mac release can not work on 10.15.3

### ISSUE THREAD

**Issue by moriwang** [marktext/marktext#1982] opened 2020-03-16 08:17 UTC
### Description
The release ends with .zip is not working on Mac. Tried both 0.15.1 and 0.16-rc3. The alert showed "can not open the application Mark text". The binary file in "Mark text.app/Contents/MacOS" is not executable. I googled this error and found the file lost permission, so I tried chmod +x on it, then the application could open but crashed immediately.

But the dmg one works totally fine. I spent an hour to install marktext, it's so sad.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. download the release for Mac ends with zip
2. unarchive it
3. move to applications folder
4. right click - open

**Actual behavior:**

Shows the alert with can not open application mark text.

### Versions

- Mark Text: 0.15.1 and 0.16-rc3
- Operating system: macOS 10.15.3

**Comment by fxha** [comment] 2020-06-07 00:31
Maybe duplicate of #1991?

**Comment by jsejcksn** [comment] 2020-07-19 22:52
https://github.com/marktext/marktext/issues/1991#issuecomment-640133343

> > Any plans to sign the app with a verified developer cert?
> 
> That is the plan for later versions when Mark Text is more stable as the certificate cost around 100$/y. But this is currently not planned for Windows as the certification costs are too high.
> 
> /cc @Jocs

Is there any plan in regard to qualifying what "later versions" and "more stable" mean? [It looks like you have a few platinum sponsors at this point.](https://opencollective.com/marktext/transactions)

I think there are people who want to try this software, but are not willing to run unsigned binaries...

**Comment by moriwang** [comment] 2020-07-26 07:31
> Maybe duplicate of #1991?

It's different. Same in 0.16.2。

The image below translate in English is 'can not open the application Mark text' which is not the same alert in #1991 
![Jietu20200726-152708](https://user-images.githubusercontent.com/9151525/88473902-7a0b8800-cf54-11ea-980f-43edbe71ff9e.jpg)

And I think the reason is the binary file is broken, since it has a blank icon. It's different in the dmg version. 

<img width="825" alt="image" src="https://user-images.githubusercontent.com/9151525/88473946-f4d4a300-cf54-11ea-8d45-81dce24ff899.png">

**Closed** 2022-01-16 16:48 UTC
Labels: :question: confirmation needed
