### ISSUE TITLE
Normal function cannot be used 

### ISSUE THREAD

**Issue by kurobanekid** [marktext/marktext#292] opened 2018-05-22 04:11 UTC
### Description
After installation, the normal function cannot be used. I have tried many time to reinstalled it, but it let me down again and again. Everytime I reinstalled it, i have completely cleared the data.

### Steps to reproduce

1. After installation completed, I changed the theme from `Light` to `Dark`
2. Then it could successfully opened one of my markdown files
3. I closed the window. Then I opened it again, it can't open any markdown file, it newed a window and the content is an untitled file.

**Expected behavior:**  normal funciton can be used

**Actual behavior:**  normal funciton can't be used

### Versions

- Mark Text: v 0.10.21
- OS: Windows10 1803

**Comment by fxha** [comment] 2018-05-22 07:29
Thanks @kurobanekid,

I think this is a duplicate of #265 or #217. In v0.10.21 you cannot open files when Mark Text is started maximized or in full-screen mode. Also ensure you type in `light` and `dark` in lower case.

```
[...]
"theme": "light",
[...]
```

or

```
[...]
"theme": "dark",
[...]
```

**Comment by kurobanekid** [comment] 2018-05-22 08:14
Thanks, I'm happy to use it now😀

**Closed** 2018-05-23 05:27 UTC
Labels: fixed but not released
