### ISSUE TITLE
Auto completion for LaTeX syntax

### ISSUE THREAD

**Issue by WXGopher** [marktext/marktext#1016] opened 2019-05-08 23:44 UTC
### Describe your feature request

It would be nice to have auto completion for LaTeX syntax (like mordern TeX editors, TeX studio for example). The LaTeX auto completion mechanism is only triggered in math mode.

### Additional context [optional]

A really nice auto completion from a heavy TeX user:

> \fra -> \frac{}{}

Note: I can help a bit to sort out a bunch of frequently used TeX syntax.

**Comment by fxha** [comment] 2019-05-09 16:49
Duplicate of #658 and #724

**Closed by fxha** 2019-05-09 16:49 UTC
