### ISSUE TITLE
Copy paste from marktext in terminal create &quot; insted of "

### ISSUE THREAD

**Issue by yodatak** [marktext/marktext#2210] opened 2020-06-09 22:04 UTC
### Description
When i want to use marktext to make a documentation i paste some thing from internet 
and then when i copy paste in the terminal i got &quot; 

### Steps to reproduce
Just copy text with " in a terminal ( i use tilix maybe its tilix the problem) and i got &quot; 
 inted of " 

**Expected behavior:**

have " and not &quot; 
Maybe it can be usefull to have a copy mode to have just text only and not web quotes

### Versions

- Mark Text: v0.16.1
- Operating system: Fedora 32

**Comment by fxha** [comment] 2020-06-10 23:07
Duplicate of #1821.

**Closed by fxha** 2020-06-10 23:07 UTC
