### ISSUE TITLE
Offer the ability to create relative references to image files

### ISSUE THREAD

**Issue by fgimian** [marktext/marktext#2560] opened 2021-04-16 11:24 UTC
### Describe your feature request

Continuing on from the discussion in #549

Typora has an option "Use relative path if possible" which is critical. It will insert a relative path to the file instead of an absolute path when it is stored in a relative path such as "assets". This means that if you move the document and its images to a different location, images continue to work. Mark Text only seems to insert absolute paths which makes it very hard to move things around.

### What problem does this feature solve? [optional]

It makes it possible to easily move and share documents with their related images.

### Additional context [optional]

You can see the related option in Typora title "Use relative path if possible" below:

![image](https://user-images.githubusercontent.com/1811813/115017451-ea4ea500-9ef9-11eb-99c9-6d0e2a13029f.png)

With this setup, if I were to paste a screenshot into an example document, it would render:

```markdown
![Screenshot (1)](Testing.assets/Screenshot (1).png)
```

Meanwhile Mark Text would render something like:

```markdown
![Screenshot (1).png](C:\Users\Fots\Documents\Wiki\assets\b5a959a24be0f855c0e7e64ba3fa213d76e2ccbe.png)
```

**Comment by wernerdaehn** [comment] 2021-04-23 04:25
Yes, huge problem. You paste an image into the document (relative path is "./assets/"), then push it to github and the image cannot  be found as the server does not know the absolute path for sure.

**Comment by teopost** [comment] 2021-05-05 11:52
+1

**Comment by carmolim** [comment] 2021-05-13 18:58
+1

**Comment by carmolim** [comment] 2021-05-13 19:15
+1

**Comment by Lulu300** [comment] 2021-06-04 07:45
+1

**Comment by ytianxia6** [comment] 2021-11-30 03:07
+1
So is there a plan to solve this problem?

**Comment by YalandHong** [comment] 2021-11-30 03:35
It's strange. The developer said:
> A relative path should be used if the file is persistent on disk.

But I can't figure out how to do so. MarkText always uses absolute path.

**Comment by YalandHong** [comment] 2021-11-30 04:05
> +1 So is there a plan to solve this problem?

Unfortunately I don't think there's any explicit plan to implement this feature. So, currently it may be quite a pain, especially for Typora users, if you want to insert a bunch of images in your documents.

**Comment by ytianxia6** [comment] 2021-11-30 05:22
I think that even if it is not possible to support the automatic use of relative paths, it should support the resolution of relative paths, or at least manually change them to relative paths.
But now when you manually change to a relative path, the picture cannot be displayed.

**Comment by YalandHong** [comment] 2021-12-02 02:42
Also related to #2652

**Comment by fxha** [comment] 2021-12-22 16:27
You can select this behavior via `Settings -> Image`. Select "Move to designated local folder" and activate "Prefer relative assets folder". But I think the current stable version has a bug that this may fail that was already fixed on develop.

Relative to file is duplicate of #2559.

**Closed by fxha** 2021-12-22 16:27 UTC

**Comment by fgimian** [comment] 2022-01-19 04:16
I can confirm this works perfectly in the latest develop version, thanks!

**Comment by gimmi** [comment] 2022-01-25 07:56
Is it possible to have a pre release available for download?
