### ISSUE TITLE
Can't Open Links To Local Files

### ISSUE THREAD

**Issue by r4hulCorleone** [marktext/marktext#1969] opened 2020-03-09 09:20 UTC
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Put a pdf file to same directory as the md file exists. For example, I put "A.pdf" in directory, and create a link in my markdown document like:    [link to A file](A.pdf)

**Expected behavior:**
By Ctrl+Click  on link , i expect to open A.pdf file like when I use double click to open files in windows.

**Actual behavior:**
Nothing happens and A.pdf file will not open.

- Mark Text: 0.15
- Operating system: Windows 10 64

**Comment by fxha** [comment] 2020-03-10 21:43
Thank you for reporting the issue. We noticed that this is a duplicate of #1688. You may want to subscribe there for further updates.

**Closed by fxha** 2020-03-10 21:43 UTC

**Comment by r4hulCorleone** [comment] 2020-03-13 19:17
tnx.
