### ISSUE TITLE
Cannot chang fonts?

### ISSUE THREAD

**Issue by quanee** [marktext/marktext#1846] opened 2019-12-31 01:16 UTC
### Description

Cannot change font('editor' & 'code block')

- [x] Can you reproduce the issue? 
- [x] yes

### Steps to reproduce

1. [First step] click 'File'
2. [Second step]  click 'Preferences'
3. [third step] click 'Editor'
4. [fourth step] click 'The used font in the editor'
5. [fifth step] select different font

**Expected behavior:**

display selected font

**Actual behavior:**

no happened

**Link to an example: [optional]**

### Versions

- Mark Text: v0.16.0-rc.2 (marktext-x64-win.zip)
- Operating system:windows 10 1909

**Comment by adrienbeau** [comment] 2020-01-06 14:38
**Could not reproduce**, using Mark Text v0.16.0-rc2 under Windows 7. Fonts are changed in real time as I select them in the Preferences, both the regular font and the fixed-width code block font.

**Comment by fxha** [comment] 2020-01-13 22:58
Thank you for taking the time to report this issue. @quanee Please provide the font family name, this maybe a duplicate of #1773.

**Comment by Jocs** [comment] 2020-02-16 11:13
closed due to not active.

**Closed by Jocs** 2020-02-16 11:13 UTC
