### ISSUE TITLE
Opening file goes straight to the bottom

### ISSUE THREAD

**Issue by steelropes** [marktext/marktext#2770] opened 2021-12-16 09:11 UTC
When I open my files with marktext, they immediately go to the bottom of the file (scroll bar all the way down).

How can I make it so it opens like a normal document? I've looked in preferences. Thanks.

**Comment by DYH-Hong** [comment] 2021-12-20 02:47
Possible duplicate of #1407

**Closed** 2021-12-23 18:23 UTC
