### ISSUE TITLE
Code copied from the code block appears to be quoted unexpectedly

### ISSUE THREAD

**Issue by frapples** [marktext/marktext#2044] opened 2020-04-14 07:05 UTC
### Description

Code copied from the code block appears to be quoted unexpectedly
- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open Marktext(version v0.16.1, windows 10)
2. Input code block，the language is C++, eg:
```c++
std::map<int, int> map;
```

3. Copy those code, Use the mouse to select and press Ctrl-c instead of clicking the copy button,  and paste to notepad.

**Expected behavior:**
The content on the notepad is `std::map<int, int> map;`

**Actual behavior:**
The content on the notepad is `std::map&lt;int, int&gt; map;`

**Link to an example: [optional]**

### Versions

- Mark Text: v0.16.1
- Operating system: windows 10

**Comment by gabrielegiammatteo** [comment] 2020-04-20 12:23
It's happening also outside code blocks for me (v. 0.16.1 on Linux).

![Peek 2020-04-20 14-14](https://user-images.githubusercontent.com/4500049/79751014-2c0e3500-8312-11ea-9261-dcda30a3a90d.gif)

It's really annoying because often I save bash commands with Marktext and I'd like to copy and paste them in the terminal directly.
I tried to fix this issue here https://github.com/gabrielegiammatteo/marktext/commit/3960f429ced4182a84e06e862e281c14b5eee7a3 by removing the invocation to `escapeHtml()`. It seems to work, but I don't know if this is the best way to fix it and which side effects it might have.

**Comment by gitvishy** [comment] 2020-04-29 21:07
I'm seeing the same problem (v. 0.16.1 on Mac OS 10.14.6). Copy as plain text + pasting
`grep "query" file.txt` from a code block renders as

`grep &quot;query&quot; file.txt`

If I do the same in source code mode, it works as expected. But toggling back and forth between preview and source code mode is not ideal.

**Comment by xgdgsc** [comment] 2020-05-27 01:22
I also see this. `export CENV_PATH="/n1/env/"` becomes  `export CENV_PATH=&quot;/n1/env/&quot;`

**Comment by fxha** [comment] 2020-06-06 23:57
Thank you for reporting the issue. We noticed that this is a duplicate of #1821. You may want to subscribe there for further updates.

**Closed by fxha** 2020-06-06 23:57 UTC
