### ISSUE TITLE
Vim-like mode

### ISSUE THREAD

**Issue by Shatonly** [marktext/marktext#2438] opened 2020-12-18 17:46 UTC
### Describe your feature request

Hello, I humbly suggest to add a vim-like mode that has the main vim behaviors and keybindings. I’m not a dev (not yet…), so I don’t know if it’s achievable, but it would be very great because both softwares are the best, and combining their advantages would be better.

Many thanks for this huge editor!

**Comment by fxha** [comment] 2020-12-18 22:26
Thank you for reporting the issue. We noticed that this is a duplicate of #596. You may want to subscribe there for further updates.

**Closed by fxha** 2020-12-18 22:26 UTC
