### ISSUE TITLE
Unexpected error: Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by thsheep** [marktext/marktext#578] opened 2018-11-28 07:52 UTC
### Description

An unexpected error occurred in the renderer process

### Stack Trace

```
TypeError: Cannot read property 'nodeType' of null
    at A (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3009263)
    at A.value (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3009487)
    at A.value (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3148163)
    at A.value (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3149223)
    at A.Xt.A.inputHandler (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3140962)
    at HTMLDivElement.<anonymous> (file:///Applications/Mark%20Text.app/Contents/Resources/app.asar/dist/electron/renderer.js:13:3161579)
```

### Version

Mark Text: ~~0.13.65~~ master 6a96a46 (darwin)

**Comment by Jocs** [comment] 2018-11-28 08:13
Is there anything wrong with the UI?

**Comment by stefnotch** [comment] 2018-11-28 14:54
@thsheep How do I reproduce that error?

**Comment by fxha** [comment] 2018-11-28 17:06
> @thsheep How do I reproduce that error?

Thanks @thsheep, can you please give us some information, how the error occurred. It's hard to solve the issue without more information.

**Comment by fxha** [comment] 2019-01-02 16:20
@thsheep Can you please use the latest master and/or give us instruction how to reproduce the issue.  I'm closing the issue because we cannot reproduce the error.

**Closed by fxha** 2019-01-02 16:20 UTC
Labels: more detail
