### ISSUE TITLE
Table of contents in sidebar doesn't work

### ISSUE THREAD

**Issue by gotjek** [marktext/marktext#1916] opened 2020-02-17 23:03 UTC
### Description

When I click on an item of the table of contents, nothing happens: the view doesn't go to the title clicked.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Type titles and text in a blank file.
2. Open sidebar.
3. Click on a title in the table of contents.

**Expected behavior:**

The view should go at the right title.

**Actual behavior:**

View does nothing.

**Link to an example:**

![Bug Marktext](https://user-images.githubusercontent.com/31245682/74691111-c9999b00-51e1-11ea-838f-8af354200396.gif)

### Versions

- Mark Text: 0.16 rc3
- Operating system: Windows 10 v1909

### Thank you

I love MarkText!

**Comment by YalandHong** [comment] 2020-02-19 03:53
Duplicate of #1775

**Comment by fxha** [comment] 2020-02-21 14:48
@gotjek  Thank you for reporting the issue. As @YalandHong already noticed, this is a duplicate of #1775. You may want to subscribe there for further updates. Could you please provide a document to reproduce the issue?

**Closed by fxha** 2020-02-21 14:48 UTC
