### ISSUE TITLE
Switch tabs during Source Code Mode does not update content

### ISSUE THREAD

**Issue by mupchrch** [marktext/marktext#748] opened 2019-03-11 14:02 UTC
### Description

If I am in Source Code Mode and I switch tabs, the content of the tab still shows the source of the previous tab.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Have two tabs open.
2. View > Source Code Mode
3. Switch to other tab
4. Notice the source of the tab is still displaying the source of the previous tab.

**Expected behavior:**

The content of the tab should update to show the source of the current tab.

**Actual behavior:**

The content of the tab shows the source of the tab that you originally viewed the source of.

### Versions

- Mark Text: v0.13.65
- Operating system: MacOS v10.12.6

**Comment by fxha** [comment] 2019-03-11 14:53
Duplicate of #606

**Closed by fxha** 2019-03-11 14:53 UTC
