### ISSUE TITLE
[FEATURE REQUEST]: Foot notes

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1272] opened 2019-08-16 05:31 UTC
### Describe your feature request

 Support for foot notes, which is a standard Markdown feature.

### What problem does this feature solve? [optional]

 The add ancillary info to a separate section at the bottom of a page, rather than have it in among the main text.

**Comment by stefnotch** [comment] 2019-08-16 09:59
Duplicate of https://github.com/marktext/marktext/issues/193

**Closed** 2019-08-16 15:52 UTC
