### ISSUE TITLE
[FEATURE REQUEST]: keyboard shortcut CTRL+PgDn/PgUp

### ISSUE THREAD

**Issue by DutchPete** [marktext/marktext#1288] opened 2019-08-18 16:41 UTC
### Describe your feature request

 I use keyboard shortcuts a lot, and one I use regulrarly is <kbd>CTRL+PgUp</kbd> and <kbd>CTRL+PgDn</kbd> to change from 1 tab to another.
I know the PgUp and PgDn issue has to be fixed 1st.
>
BTW, is there a keyboard shortcut to open the menu?

### What problem does this feature solve? [optional]

 work flow efficiency.

**Comment by fxha** [comment] 2019-08-18 19:19
Duplicate of #1124.

**Closed by fxha** 2019-08-18 19:19 UTC
