### ISSUE TITLE
PDF exports without images

### ISSUE THREAD

**Issue by cloo** [marktext/marktext#2167] opened 2020-06-02 19:08 UTC
### Description

When you have a .md document with images, your exported pdf's appear without images.
 
### Steps to reproduce

1. Create an .md file with images
2. Export .pdf, any style
3. .pdf is without images

**Expected behavior:**

Images should be in the .pdf file, as they are in .md file. If there are problems with image paths, formats, or other (when they can be displayed, but cannot be exported), I would expect to get a notification, an error, or orther feedback, so I could fix it.

**Actual behavior:**

Images are not here :)

**Link to an example: [optional]**

 
![Mark_Text_TBs0609ikN](https://user-images.githubusercontent.com/651760/83559507-5ceea600-a51d-11ea-9559-775be3d5e979.png)
![SumatraPDF_5JjhTXfm1F](https://user-images.githubusercontent.com/651760/83559514-5fe99680-a51d-11ea-8223-0eb5dd52a80e.png)

### Versions

- Mark Text: v0.16.1
- Operating system: Windows 10

**Comment by fxha** [comment] 2020-06-03 23:55
Thank you for taking the time to report this issue! We noticed that this is a duplicate of #1997.

**Closed by fxha** 2020-06-03 23:55 UTC
