### ISSUE TITLE
[Feature suggestion] About identify `$\ce{}$` in a formula

### ISSUE THREAD

**Issue by boxie123** [marktext/marktext#2725] opened 2021-12-02 07:00 UTC
### Describe your feature request

The `\ce{}` provides a lot of conveniences when I type some **chemical language**. It can convert some characters to superscripts and subscripts automatically.

For example, `$\ce{CO2 ->[\Delta] C + O2 ^}$` will obtain the same result as `$CO_2 \xrightarrow{\Delta} C + O_2\uparrow$` .

Typora and Zettlr both support the function. However, Mark Text doesn't.

Thank you very much if you can add this function.

### What problem does this feature solve? [optional]

There are a large number of people in the world engaged in chemistry-related work. Adding this feature will make it more convenient for us to edit markdown documents through Mark Text!

-----------

### 描述您的功能请求

当我输入一些**化学语言**时，`\ce{}` 提供了很多便利。 它可以自动将某些字符转换为化学符号或者上下标。

例如，`$\ce{CO2 ->[\Delta] C + O2 ^}$` 将获得与 `$CO_2 \xrightarrow{\Delta} C + O_2\uparrow$` 相同的结果。

Typora 和 Zettlr 都支持该功能。 但遗憾的是，Mark Text 没有。

如果可以添加这个功能，非常感谢。

### 这个功能解决了什么问题？ [可选的]

世界上有庞大的人数在从事与化学有关的工作。 增加这个功能会让我们使用Mark Text编辑markdown文档更加方便！

![image](https://user-images.githubusercontent.com/80164656/144373485-f73d247e-383f-44c6-a88c-ae8cd2ec0a88.png)

**Comment by YalandHong** [comment] 2021-12-02 11:37
Duplicate of #2301 and #1909

KaTex supports `\ce` via [mhchem](https://github.com/KaTeX/KaTeX/tree/main/contrib/mhchem) extension. However MarkText doesn't seem to include it.

**Comment by fxha** [comment] 2021-12-23 17:05
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #1909. You may want to subscribe there for further updates.

**Closed by fxha** 2021-12-23 17:05 UTC
