### ISSUE TITLE
请求增加中文语言

### ISSUE THREAD

**Issue by verineliu** [marktext/marktext#3249] opened 2022-05-06 06:04 UTC

**Comment by BrogenWang** [comment] 2022-05-06 10:02
+1

**Comment by max-spaceman** [comment] 2022-05-07 01:26
Hope to add Chinese Language interface , and I am glad to do something about this. Tell me how to give my support, I am totally new with Github and programming.

**Comment by shaokuuipo** [comment] 2022-05-07 05:51
听说这是中国人开发的呀？为什么没有中文呢？What are you 弄啥呢？

**Comment by YalandHong** [comment] 2022-05-09 00:35
Duplicate of https://github.com/marktext/marktext/issues/138

**Comment by longjinxiang** [comment] 2022-05-30 01:49
mark

**Comment by shiyunjie45** [comment] 2022-06-17 17:14
+1

**Comment by yzh1255245824** [comment] 2022-07-09 04:58
I have browsed [#138](https://github.com/marktext/marktext/issues/138), but I did not find a solution. So I just want to know has the international version the author said two years ago been released? Or is there some method can solve this problem?

**Comment by YalandHong** [comment] 2022-07-20 02:02
> I have browsed [#138](https://github.com/marktext/marktext/issues/138), but I did not find a solution. So I just want to know has the international version the author said two years ago been released? Or is there some method can solve this problem?

Nope. Internalization is planned in the future version.

**Comment by 2003wxc** [comment] 2022-09-08 02:59
我也想要中文

**Closed** 2023-08-03 14:10 UTC
