### ISSUE TITLE
download new dictionaries for Hunspell failed

### ISSUE THREAD

**Issue by kosssi** [marktext/marktext#1936] opened 2020-02-26 15:01 UTC
### Description

It's not possible to download new dictionaries for Hunspell.

- [x] Can you reproduce the issue? ²

### Steps to reproduce

1. Go to Spelling preferences
2. Choose another language of "English (en-US)"
3. Click on add button

**Expected behavior:**

I would like download correctly the spelling file and use it on Mark Text.

**Actual behavior:**

This display an error: `Error while downloading: response.data.pipe is not a function`

**Link to an example: [optional]**

![Capture d’écran de 2020-02-26 15-25-38](https://user-images.githubusercontent.com/1135513/75356790-b3aa6b00-58b0-11ea-97f0-1c0b54f1c7d7.png)

This problem can be fixe [here](https://github.com/marktext/marktext/blame/184861f7b9ff4642656057e7deb5c3c43d6695e8/src/renderer/spellchecker/dictionaryDownloader.js#L26) maybe @fxha can explain it ;)

I'm download file directly for French and place it in the correctly directory ;)

### Versions

- Mark Text: 0.16.0-rc.3
- Operating system: Ubuntu

Thanks you for Mark Text :heart:

**Comment by fxha** [comment] 2020-03-10 21:57
Thank you for taking the time to report this issue! This seems to be a duplicate of [this](https://github.com/axios/axios/issues/552#issuecomment-267038885) issue in the http library which we use to download the dictionaries.

**Closed** 2020-03-21 01:02 UTC
Labels: :beetle: pri/major, :owl: pre-release, 🐛 bug
