### ISSUE TITLE
I hope the "Relative image folder name" to support variables, like Typora

### ISSUE THREAD

**Issue by Sean-214** [marktext/marktext#2683] opened 2021-11-28 03:44 UTC
### Describe your feature request

I hope the "Relative image folder name" to support variables, like Typora `./${filename}.assets` .

`${filename}` is the file name of the current document

**Comment by gynamics** [comment] 2021-11-28 08:23
I have got an idea. It seems there is a regex filter in `src/renderer/prefComponents/image` which disables script execution in that string:
```vue
 30      <text-box
 31         description="Relative image folder name"
 32         :input="imageRelativeDirectoryName"
 33         :regexValidator="/^(?:$|(?![a-zA-Z]:)[^\/\\].*$)/"
 34         :defaultValue="relativeDirectoryNamePlaceholder"
 35         :onChange="value => onSelectChange('imageRelativeDirectoryName', val    ue)"
 36       ></text-box>

```
Hook `onChange` method and add `state.editor.currentFile.filename` as a candidate, I am not sure if that works, unfortunately the network situation is bad for me to build the package, would someone have a try?

**Comment by YalandHong** [comment] 2021-11-30 02:56
Duplicate of #2559

**Closed** 2021-12-22 16:15 UTC
