### ISSUE TITLE
"Open the last window state" option greyed out

### ISSUE THREAD

**Issue by markojurkovic** [marktext/marktext#2068] opened 2020-04-24 17:41 UTC
## Description

In Preferences, the option "What Mark Text should do on startup" -> "Open the last window state" is greyed out for no apparent reason. The other two options are available (see attached screenshot).

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Open Mark Text Preferences
2. In the General section, look for the option "What Mark Text should do on startup"
3. Observe that the first choice, "Open the last window state" is greyed out, while the other two are available

**Expected behavior:**

The aforementioned choice/radio bar should be available.

**Actual behavior:**

The choice/selection is not available for no apparent reason

![image](https://user-images.githubusercontent.com/9203900/80241244-8cc7a580-8663-11ea-9d84-c94a392a2ae5.png)

### Versions

- Mark Text: 0.16.1
- Operating system: Windows 10 Enterprise Build 18363.778

**Comment by fxha** [comment] 2020-05-23 20:18
Thanks for opening the issue. We noticed that this is a duplicate of #2064. You may want to subscribe on issue #988 for further updates.

**Closed by fxha** 2020-05-23 20:18 UTC
