### ISSUE TITLE
Unexpected error: Cannot read property 'webContents' of undefined

### ISSUE THREAD

**Issue by gruenheit** [marktext/marktext#1981] opened 2020-03-15 08:06 UTC
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError: Cannot read property 'webContents' of undefined
    at $e (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:277776)
    at click (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:278778)
    at MenuItem.click (/Applications/Mark Text.app/Contents/Resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/Applications/Mark Text.app/Contents/Resources/electron.asar/browser/api/menu.js:31:13)
```

### Version

Mark Text: v0.15.1
Operating system: Darwin x64 19.3.0 (darwin)

**Comment by fxha** [comment] 2020-03-17 18:22
Thank you for reporting the issue. I think this is a duplicate of #961. If you want, you can try the latest testing version from Github releases (v0.16.0-rc.3).

**Closed by fxha** 2020-03-17 18:22 UTC
