### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by vadim-tch** [marktext/marktext#2888] opened 2022-01-14 22:57 UTC
### Description

MarkText crashes on startup

- [x] Can you reproduce the issue?

### Steps to reproduce

Download MarkText for Linux (AppImage or RPM version, doesn't matter) and launch it.

**Expected behavior:**

MarkText starts

**Actual behavior:**

MarkText briefly shows an empty dark-themed window and crashes on startup with the following output:

```(node:60460) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:60460) DeprecationWarning: init() is deprecated and will be removed in v5.
[60460:0115/014933.689486:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Failed to generate minidump.[1]    60460 illegal hardware instruction (core dumped)  marktext
```

### Versions

- MarkText version: latest | 0.16.3
- Operating system: 64-bit Fedora35 Workstation Edition @ Intel Core i5, Integrated Intel Graphics

**Comment by fxha** [comment] 2022-01-15 17:10
Duplicate of #2878. We should release testing versions at the end of this month.

**Closed by fxha** 2022-01-15 17:10 UTC
Labels: 🐛 bug, :penguin: platform/linux, 🐞 pri/critical
