### ISSUE TITLE
"Cycle Through Windows" Feature

### ISSUE THREAD

**Issue by battlesman** [marktext/marktext#1828] opened 2019-12-19 16:51 UTC
### Describe your feature request
If it's not currently possible to "Cycle Through Windows" like in another app, I would greatly appreciate this being added!

Here's what I mean. Pressing Command+` like in Finder or pretty much any other app so that you're cycling through the windows currently open.
### What problem does this feature solve? [optional]
Having to use your mouse to click to the other windows you have open.

### Additional context [optional]

<img width="127" alt="Screen Shot 2019-12-19 at 11 47 37 AM" src="https://user-images.githubusercontent.com/14978950/71192264-ee12de80-2255-11ea-9d38-3b1c32248cfc.png">

**Comment by fxha** [comment] 2019-12-19 21:17
@battlesman Thanks for your suggestion but shouldn't that be an operation system feature? Normally your can switch between windows with `Alt+Tab` on Linux and Windows.

**Comment by battlesman** [comment] 2019-12-19 23:37
I would think so, but Cycle Through Windows is not even listed as an option on MacOS like it is in other apps. It's typically Command+` but that's assigned to another keybinding in Mark Text.

**Comment by fxha** [comment] 2019-12-21 11:20
Thanks for your feedback. We noticed that this is a duplicate of #1713 and you may want to subscribe there for further updates.

**Closed by fxha** 2019-12-21 11:20 UTC
Labels: :baby_chick: blocked/need info, :green_apple: platform/macOS, :question: confirmation needed
