### ISSUE TITLE
Unexpected error: this.renderer.inlineMath is not a functionPlease report this to https://github.com/marktext/marktext/issues.

### ISSUE THREAD

**Issue by CeroProgramming** [marktext/marktext#1774] opened 2019-11-30 11:25 UTC
### Description

An unexpected error occurred in the renderer process.

The error occured while trying to copy selected markdown content. I was able to reduce it to the following snippet:
```md
$Qx:=\begin{pmatrix}a & b \\ c & d\end{pmatrix}x:=\Phi_Q(x)$

### 2.1.4 Struktur von $\mathbb{R}^2$
```

### Stack Trace

```
TypeError: this.renderer.inlineMath is not a function
Please report this to https://github.com/marktext/marktext/issues.
    at es.output (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3375134)
    at ss.tok (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3379222)
    at ss.parse (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3378615)
    at Bs (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3381199)
    at Ps.Es.A.getClipBoradData (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3392909)
    at Ps.Es.A.copyHandler (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3393007)
    at HTMLDivElement.i (file:///opt/Mark%20Text/resources/app.asar/dist/electron/renderer.js:20:3449010)
```

### Version

Mark Text: v0.15.1 (a32c2c0)
Operating system: Linux x64 5.3.11-1-ck (linux)

**Comment by fxha** [comment] 2019-12-01 16:49
Duplicate of #1522

**Closed by fxha** 2019-12-01 16:49 UTC
