### ISSUE TITLE
Cannot enter sqare brackets (“[” and “]”) in v0.16.2 

### ISSUE THREAD

**Issue by odkr** [marktext/marktext#2359] opened 2020-10-14 09:55 UTC
### Description

No character is entered when I press \<Alt\>+<5> ("[" on a German keyboard) or \<Alt\>+<6> ("]").

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open Mark Text.
2. Press \<Alt\>+<5> or \<Alt\>+<6> (on a German keyboard).

No character appears.

**Expected behavior:**

"[" or "]" respectively should be entered.

**Actual behavior:**

Neither "[" or "]" are entered.

### Versions

- Mark Text version: v0.16.2
- Operating system: macOS v10.14.6

**Comment by dhose** [comment] 2020-10-15 08:29
I have this problem as well, but on a Swedish keyboard. Alt+4 ("$") does not work for me either

### Versions
* Mark Text version: v0.16.2
* Operating system: macOS v10.15.6

**Comment by brainchild0** [comment] 2020-10-24 15:10
Probably duplicate of #2235.

**Comment by Rasmis** [comment] 2021-01-11 16:04
This issue affects Mac users in every language but American. It is a grave error. `Alt` and `shift` are always for typing. They can only be used for shortcuts when used with ctrl or cmd.

The issue can be mitigated by adding the file ```keybindings.json``` to ```~/Library/Application Support/marktext``` with this content:

```
{
    "tabs.switch-to-first": "",
    "tabs.switch-to-second": "",
    "tabs.switch-to-third": "",
    "tabs.switch-to-fourth": "",
    "tabs.switch-to-fifth": "",
    "tabs.switch-to-sixth": "",
    "tabs.switch-to-seventh": "",
    "tabs.switch-to-eighth": "",
    "tabs.switch-to-ninth": "",
    "tabs.switch-to-tenth": ""
}
```

The fastest way is to open terminal and type `nano "~/Library/Application Support/marktext/keybindings.json"`. Paste the text, press `[ctrl]+[o]`, `[ctrl]+[x]` to save and exit. Solution [copied from #2299](https://github.com/marktext/marktext/issues/2299#issuecomment-673654585)

Obviously a different shortcut can be supplied.

Same issue as #2235, #2299, #2376 and #2359.

**Comment by epeios-q37** [comment] 2021-01-11 16:27
Someone suggests that #2235 is related to  #2225. There is a workaround for #2225, which is to set `GTK_IM_MODULE` environment variable to `xim`. This workaround works under *Linux*, don't know if `GTK_IM_MODULE` environment variable is of some use on *macOS*…
See https://bugs.chromium.org/p/chromium/issues/detail?id=1129424

**Comment by brainchild0** [comment] 2021-01-11 16:29
Suggest closing in favor of #2235.

**Comment by brainchild0** [comment] 2021-01-11 16:31
Suggest closing in favor of #2235.

**Comment by fxha** [comment] 2021-12-16 21:48
Thank you for reporting the issue. We noticed that this is a duplicate and closing it in favor of #2235. You may want to subscribe there for further updates.

**Closed by fxha** 2021-12-16 21:48 UTC
