### ISSUE TITLE
Folder button takes no effect！

### ISSUE THREAD

**Issue by dingxianye** [marktext/marktext#773] opened 2019-03-17 12:47 UTC
![image](https://user-images.githubusercontent.com/19801767/54490977-9fff3200-48f5-11e9-801c-964cb8705d0d.png)

The black triangle left to folder(_posts) takes no effect when clicking.
I think I dont know how to open a folder correctly

**Comment by Jocs** [comment] 2019-03-17 12:58
Do you mean no animation or it didn't open this folder ?

**Comment by dingxianye** [comment] 2019-03-17 13:02
> Do you mean no animation or it didn't open this folder ?

No, I clicked, it didn't open. The triangle stayed unchanged no matter I clicked the folder TEXT or triangle ICON.

**Comment by dingxianye** [comment] 2019-03-17 13:12
Here is info of my Mac
![image](https://user-images.githubusercontent.com/19801767/54491367-fc178580-48f8-11e9-806c-18510ac13d8d.png)

I install Mark Text using cmd below:
![image](https://user-images.githubusercontent.com/19801767/54491393-400a8a80-48f9-11e9-9756-06ee860be672.png)
...
![image](https://user-images.githubusercontent.com/19801767/54491410-587aa500-48f9-11e9-8b45-9ae8fedba638.png)

**Comment by Jocs** [comment] 2019-03-17 13:13
@Do you have files in `_posts` folder?

**Comment by dingxianye** [comment] 2019-03-17 13:14
> @Do you have files in `_posts` folder?

Yes, I have some .md files under it.

**Comment by Jocs** [comment] 2019-03-17 13:19
Can you describe the detailed steps of how to open this folder? This way I can reproduce this problem.

**Comment by fxha** [comment] 2019-03-17 13:19
@Jocs @dingxianye The sidebar is cashed because of the default `Empty Project` view. I had experienced this in #764 multiple times.

**Comment by fxha** [comment] 2019-03-17 13:21
@dingxianye We already fixed multiple sidebar issues on master. Is it possible for you to build Mark Text from source and retry to open the folder?

**Comment by dingxianye** [comment] 2019-03-17 13:23
OK, I will try it in few days. Thanks.

**Comment by dingxianye** [comment] 2019-04-03 16:47
Sorry for late response
![image](https://user-images.githubusercontent.com/19801767/55497003-e59c5880-5672-11e9-8cf4-84c1e0bac937.png)
I think I find something interesting.... maybe fixed in newer version ( Im too busy to try it )

**Comment by dingxianye** [comment] 2019-04-03 16:51
My '_post' folder is under folder like 'xxx.github.xxx'
Maybe it's the reason why it can't work

**Comment by fxha** [comment] 2019-04-03 19:03
This issue seems to be fixed on master. We'll release a release candidate in a few day, please reopen if the issue still exists.

**Closed by fxha** 2019-04-03 19:03 UTC
Labels: bug
