### ISSUE TITLE
Text garbling Japanese Chars inside code block in exported pdf file.

### ISSUE THREAD

**Issue by izumiz-dev** [marktext/marktext#2206] opened 2020-06-09 01:41 UTC
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create a new file.
1. Add content that japanese charactors such a 日本語(means japanese) inside fenced code block.
1. PDF Export
1. See exported file.

**Expected behavior:**

It should be displayed 日本語.

**Actual behavior:**

But it is displayed 奈棒湖 in exported pdf file.

### Versions

- Mark Text: v0.16.1
- Operating system: MacOS 10.15.5

**Comment by fxha** [comment] 2020-06-10 23:09
Duplicate of #1142.

**Closed by fxha** 2020-06-10 23:09 UTC
