### ISSUE TITLE
Does not load 

### ISSUE THREAD

**Issue by johnnydvc** [marktext/marktext#1673] opened 2019-11-10 17:39 UTC
### Description

not starting
- [ x] Can you reproduce the issue? 

### Steps to reproduce

1. Start application, also via terminal

**Expected behavior:**

app starts

**Actual behavior:**

not starting, gives following error

> App threw an error during load
> Error: Module did not self-register.
>     at process.func (electron/js2c/asar.js:138:31)
>     at process.func [as dlopen] (electron/js2c/asar.js:138:31)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
>     at Object.func (electron/js2c/asar.js:138:31)
>     at Object.func [as .node] (electron/js2c/asar.js:147:18)
>     at Module.load (internal/modules/cjs/loader.js:735:32)
>     at Module._load (internal/modules/cjs/loader.js:648:12)
>     at Module._load (electron/js2c/asar.js:715:26)
>     at Function.Module._load (electron/js2c/asar.js:715:26)
>     at Module.require (internal/modules/cjs/loader.js:775:19)
> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: Module did not self-register.
>     at process.func (electron/js2c/asar.js:138:31)
>     at process.func [as dlopen] (electron/js2c/asar.js:138:31)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
>     at Object.func (electron/js2c/asar.js:138:31)
>     at Object.func [as .node] (electron/js2c/asar.js:147:18)
>     at Module.load (internal/modules/cjs/loader.js:735:32)
>     at Module._load (internal/modules/cjs/loader.js:648:12)
>     at Module._load (electron/js2c/asar.js:715:26)
>     at Function.Module._load (electron/js2c/asar.js:715:26)
>     at Module.require (internal/modules/cjs/loader.js:775:19)

**Link to an example: [optional]**

### Versions

- Mark Text: marktext  0.15.1-2
- Operating system:
 OS: Manjaro 18.1.2 Juhraya
 Kernel: x86_64 Linux 5.3.8-3-MANJARO
 Uptime: 36m
 Packages: 1629
 Shell: zsh 5.7.1
 Resolution: 2970x1680
 DE: GNOME 3.34.1
 WM: Mutter
 WM Theme: Adapta-Nokto-Eta-Breath
 GTK Theme: Adapta-Nokto-Eta-Maia [GTK2/3]
 Icon Theme: Papirus-Light
 Font: Cantarell 11
 Disk: 167G / 1,6T (12%)
 CPU: AMD Phenom II X6 1055T @ 6x 2.8GHz
 GPU: AMD PITCAIRN (DRM 2.50.0, 5.3.8-3-MANJARO, LLVM 9.0.0)
 RAM: 3267MiB / 7961MiB

**Comment by fxha** [comment] 2019-11-10 18:09
Thanks for reporting the issue. I'm closing the issue because we cannot reproduce the issue with the official binaries, `marktext 0.15.1-2` is not an official packages provided by us. Please open an issue in the corresponding package registry.

BTW, as you're using Arch and mostly installed it via AUR. I think there is an issue in the package because they dynamic link the wrong Electron version. `marktext --version` should return `Electron:  5.0.11`. If you/they using another Electron version, no support is given and Mark Text will fail at runtime.

**Closed by fxha** 2019-11-10 18:09 UTC

**Comment by moshpirit** [comment] 2021-04-25 22:31
I had the same error:

```
App threw an error during load
Error: Module did not self-register: '/usr/lib/marktext/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'.
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/marktext/app.asar/node_modules/keyboard-layout/lib/keyboard-layout.js:4:35)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module did not self-register: '/usr/lib/marktext/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node'.
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/marktext/app.asar/node_modules/keyboard-layout/lib/keyboard-layout.js:4:35)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
libva error: /usr/lib/dri/iHD_drv_video.so init failed
```

I'm using Manjaro too with electron v12.0.4. 

BTW, if I input `marktext --version` I get the same error as above. The thing is: I've been using MT for a month with no issues, but today I tried to use it and got this error.
