### ISSUE TITLE
Unexpected error: Invalid state: all arguments must be non-null.

### ISSUE THREAD

**Issue by aleksanderzagora** [marktext/marktext#3101] opened 2022-03-05 21:27 UTC
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: Invalid state: all arguments must be non-null.
    at Object.register (C:\Users\BuZZZard\AppData\Local\Programs\MarkText\resources\app.asar\node_modules\@hfelix\electron-localshortcut\src\electron-localshortcut.js:167:11)
    at Object.registerKeyHandlers (C:\Users\BuZZZard\AppData\Local\Programs\MarkText\resources\app.asar\dist\electron\main.js:2:288839)
    at Object.addEditorMenu (C:\Users\BuZZZard\AppData\Local\Programs\MarkText\resources\app.asar\dist\electron\main.js:2:295113)
    at Xt.createWindow (C:\Users\BuZZZard\AppData\Local\Programs\MarkText\resources\app.asar\dist\electron\main.js:2:254198)
    at Object._createEditorWindow (C:\Users\BuZZZard\AppData\Local\Programs\MarkText\resources\app.asar\dist\electron\main.js:2:302982)
    at Object._openPathList (C:\Users\BuZZZard\AppData\Local\Programs\MarkText\resources\app.asar\dist\electron\main.js:2:304609)
    at Object._openFilesToOpen (C:\Users\BuZZZard\AppData\Local\Programs\MarkText\resources\app.asar\dist\electron\main.js:2:303313)
    at App.<anonymous> (C:\Users\BuZZZard\AppData\Local\Programs\MarkText\resources\app.asar\dist\electron\main.js:2:300903)
    at App.emit (node:events:394:28)
```

### Version

MarkText: v0.17.0
Operating system: Windows_NT x64 10.0.19044 (win32)

**Comment by aleksanderzagora** [comment] 2022-03-05 21:43
This happens after cleaning Key Bindings
![2022-03-05_23-40-14](https://user-images.githubusercontent.com/14241127/156900822-b4333a78-ee95-49d2-9a4e-11e840967d20.png)

**Comment by YalandHong** [comment] 2022-03-06 00:45
Duplicate of #3074 and #3083

**Closed** 2022-03-06 21:33 UTC
