### ISSUE TITLE
ShortCut ctrl+1 2... is not work for header style

### ISSUE THREAD

**Issue by Stajo3** [marktext/marktext#3185] opened 2022-04-04 09:28 UTC
### Question description
ShortCut ctrl+1 2... is not work for header style, i wonder how to use shortcut to set header level

![image](https://user-images.githubusercontent.com/50604571/161515391-72c38f4d-de8d-458a-9129-c3ec7bb134f4.png)

**Comment by YalandHong** [comment] 2022-04-06 08:27
Duplicate of #3156

**Closed** 2022-04-14 20:07 UTC
