### ISSUE TITLE
Marktext does not (always) utilize the available screen space when pasting text

### ISSUE THREAD

**Issue by zocker-160** [marktext/marktext#2051] opened 2020-04-19 00:13 UTC
### Description
when pasting a long text, only a small part of the available space, gets used.

When I manually type something, it uses the space available, so it seems like when pasting a new line character get's added in a place, which doesn't respect the shown width setting (100%)

- [x] Can you reproduce the issue? 

### Steps to reproduce
- open a new page
- insert a long text from [here](https://de.lipsum.com/feed/html)

**Expected behavior:**
software should use the full width of the window, similar to other text editors

**Actual behavior:**
![Anmerkung 2020-04-19 000208](https://user-images.githubusercontent.com/36563538/79674304-27e2fa00-81e2-11ea-982f-a725ac3534cb.png)
### other text editors with the same text pasted:
![Anmerkung 2020-04-19 000831](https://user-images.githubusercontent.com/36563538/79674359-b22b5e00-81e2-11ea-9390-b758b9ad8c7e.png)

### Versions

- Mark Text: 0.16.1
- Operating system: both Ubuntu 18.04 and Windows

**Comment by fxha** [comment] 2020-06-07 00:02
Thank you for reporting the issue. Your example includes soft line breaks and is therefore a duplicate of #1849. You may want to subscribe there for further updates.

**Closed by fxha** 2020-06-07 00:02 UTC
