### ISSUE TITLE
Language request

### ISSUE THREAD

**Issue by Javi2004** [marktext/marktext#665] opened 2019-02-01 06:11 UTC
### Describe your feature request

This software is a good one. But It has onliy got English in it .

Is it all right to add Chinese languge support ?

### What problem does this feature solve? [optional]

International Support

**Comment by stefnotch** [comment] 2019-02-01 07:10
Duplicate of https://github.com/marktext/marktext/issues/138#issuecomment-380867653

**Closed** 2019-02-01 14:04 UTC
