### ISSUE TITLE
Copying code in code blocks will lose indentation

### ISSUE THREAD

**Issue by deathrush** [marktext/marktext#1264] opened 2019-08-13 03:26 UTC
### Description

- [ ] Can you reproduce the issue? 

### Steps to reproduce

markdown file content:

```bash
cd /opt/ansible/
cat > test.yml <<EOF
- hosts: top_rank
  roles:
    - game
  tasks:
    - debug:
        msg: "{{ hostvars[inventory]['ansible_default_ipv4']['address'] }}:{{ global_usc.server_port }}"

EOF

```

Copy the codes above in Mark Text code block to VS Code.

**Expected behavior:**

Indentation retention

**Actual behavior:**

Indentation lost

### Versions

- Mark Text: 0.15.0
- Operating system: Windows 7

**Comment by Jocs** [comment] 2019-08-14 03:03
能描述具体一点吗？从marktext 复制到其他地方？还是其他地方复制到 marktext？

**Comment by deathrush** [comment] 2019-08-15 01:36
从marktext 复制到其他地方

**Comment by fxha** [comment] 2019-08-17 12:33
@Jocs  Duplicate of #942?

**Comment by Jocs** [comment] 2019-08-19 11:07
Duplicate of #942, and be closed.

**Closed by Jocs** 2019-08-19 11:07 UTC
Labels: 🦋 optimization
