### ISSUE TITLE
Change Delete button text in save dialog

### ISSUE THREAD

**Issue by tenbob** [marktext/marktext#492] opened 2018-09-11 09:13 UTC
Could I suggest a change in the wording on the popup dialog that asks if you want to save your changes.

At present it says ...
`Do you want to save the changes you made to 1 file?` followed by buttons `Save` `Cancel` and `Delete`.

The `Delete` button is confusing for users. It would be better to label it `Discard`. Hitting the button will __discard__ the current changes - not __delete__ the file completely.

HTH, Bob.

**Comment by stefnotch** [comment] 2018-09-11 13:19
Duplicate of https://github.com/marktext/marktext/issues/388

**Closed** 2018-09-11 13:37 UTC
