### ISSUE TITLE
File->Export->HTML or PDF does nothing

### ISSUE THREAD

**Issue by tonydiep** [marktext/marktext#680] opened 2019-02-10 04:24 UTC
### Description

Exporting to HTML or PDF does not work under Centos Linux 

- [X] Can you reproduce the issue? 

### Steps to reproduce

1. Click File->Export->HTML or Click File->Export->HTML

**Expected behavior:**

A dialog comes up or HTML or PDF is generated

**Actual behavior:**

Nothing happens. No dialog. No output.

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.65
- Operating system: CentOS Linux release 7.6.1810 (Core)

**Comment by fxha** [comment] 2019-02-10 11:58
Maybe a duplicate of #591? Could you please give us more information.

**Comment by tonydiep** [comment] 2019-02-10 13:03
* It doesn't seem to be a duplicate of #591 because there are no code blocks in the content

* I think it's encountering an error parsing and failing without showing an error message.
* I tested this hypothesis by exporting a simple 'hello world' markdown document to HTML and PDF and it worked.
* When I tried again to export my document it failed with no output and no error message. My document is 5 or 6 pages with links, no code blocks.

While testing I found that using the dark theme makes the PDF export a black page. Logical for a computer but probably not what the user intended. I will file a new issue for that.

**Comment by fxha** [comment] 2019-02-14 13:10
We had a number of issues with exporting documents. Most of the problems should be fixed on master. Is it possible for you to build Mark Text from source? Unfortunately the master branch is currently not stable. Pasting and document printing are upstream issues.

**Comment by Jocs** [comment] 2019-03-05 14:47
@tonydiep Can you paste  a test `markdown` file which cause this issue?

**Comment by bound2020** [comment] 2019-03-11 09:47
I met the same issue when I've added some mathematical formula. The only workaround is to remove the formulas and replace them with images. That's awkward.

**Comment by Jocs** [comment] 2019-03-11 13:56
@bound2020 Thank you for your clues. Let me test it locally.

**Comment by Jocs** [comment] 2019-03-11 14:00
>I met the same issue when I've added some mathematical formula. The only workaround is to remove the formulas and replace them with images. That's awkward.

What mathematical formula do you added? I still can not reproduce this issue, So please paste an `wrong markdown` file in comment?

**Comment by fxha** [comment] 2019-03-11 14:51
@bound2020 In addition, please add you application version (`marktext --version`) and whether you are using a git build or an official binary.

**Comment by fxha** [comment] 2019-03-31 11:23
Closing this issue because no further information has been provided. Please feel free to reopen if you can give more information.

**Closed by fxha** 2019-03-31 11:23 UTC
Labels: more detail

**Comment by TheFox22** [comment] 2020-01-30 14:25
> Closing this issue because no further information has been provided. Please feel free to reopen if you can give more information.

The issue is still there and you can replicate it by adding in the document one **inline** math formula. Consider reopening this issue please.

**Comment by fxha** [comment] 2020-01-30 21:02
@TheFox22 I guess this is a duplicate of #1523 and you may want to subscribe there for further updates. If not, please provide an example to reproduce the issue or try the latest release candidate via Github releases.
