### ISSUE TITLE
double click wrong selection

### ISSUE THREAD

**Issue by Li-An** [marktext/marktext#3161] opened 2022-03-25 16:03 UTC
### Description

When I doubleclick a word, Marktext selects the word and the space after the word quite frequently.

- [ ] Can you reproduce the issue? 

### Steps to reproduce

Doubleclick a word in a text.

**Expected behavior:**

**select the word only**

### Versions

- MarkText version: 0.17.0
- Operating system: Win 10 64 bits

**Comment by DYH-Hong** [comment] 2022-03-26 00:57
Duplicate of #2166

**Closed** 2022-03-31 20:08 UTC
