### ISSUE TITLE
A JavaScript error occurred in the Main process

### ISSUE THREAD

**Issue by zachary-murphy** [marktext/marktext#113] opened 2018-03-31 17:08 UTC
### Description
Uncaught Exception Error when installing from the exe in the readme file for Windows.

### Steps to reproduce

1. Go to ReadMe File and Click Windows Download Installation.
2. Install Exe on Windows
3. And Click Run MarkText after the Installation has completed (Run from Installer)

**Expected behavior:** To Open Up the Application.

**Actual behavior:** Errors.

**Image of Error:** 
![screenshot_6](https://user-images.githubusercontent.com/30607145/38165638-9c0dbf34-34e4-11e8-99e7-eeebb1babd1b.png)

### Versions

- Mark Text: Latest ReadMe Windows Exe Installation (According to the ReadMe Link)
- OS: Windows 10

**Comment by fxha** [comment] 2018-03-31 17:20
Duplicate of #90. This bug is already fixed and release will be available soon.

@Jocs Maybe release v0.9.x in the next days?

**Comment by Jocs** [comment] 2018-03-31 17:27
@fxha Ok, I will release the next version after the `image path auto complement` finished.

**Comment by zachary-murphy** [comment] 2018-03-31 20:33
@Jocs When will `image path auto complement` be finished?

**Comment by Jocs** [comment] 2018-04-01 02:15
@zachary-murphy Almost finished, A new version will be released today.

**Closed** 2018-04-01 04:26 UTC
Labels: fixed but not released
