### ISSUE TITLE
It always asks me if I want to save my changes when I close a tab ,but in fact ,I haven't change anything

### ISSUE THREAD

**Issue by xiaohuan666** [marktext/marktext#2303] opened 2020-08-13 09:53 UTC
As the title says ,I just read my text with a few clicks of the mouse . But it might define this behavior as making a change to the text.
I think there might be some problems with the logic of the judgment.

**Comment by brainchild0** [comment] 2020-08-17 11:55
Duplicate of #2189.

**Closed** 2020-08-28 11:44 UTC
