### ISSUE TITLE
Why did the exported file figure disappear?

### ISSUE THREAD

**Issue by hwyywh** [marktext/marktext#1997] opened 2020-03-23 06:40 UTC
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

I inserted an image into the document and it disappeared when I exported the PDF file

**Comment by fxha** [comment] 2020-03-24 16:54
Thank you for reporting the issue. We noticed that this may be a duplicate of #1367. You could download the latest release candidate from Github releases - otherwise replacing all path spaces with `%20` should work too. Please try out, whether you can reproduce this issue on the latest release candidate or with an image without path spaces.

**Comment by JeffreySE** [comment] 2020-04-08 11:52
The issue still exists, in a fresh installation, images are not exported in the exported file(PDF & HTML), no spaces in the image file path, see the attached video for more details.

**OS**: Win 10
**MarkText Version**: v0.16.1

![demo](https://user-images.githubusercontent.com/12522179/78781141-5555c980-79d2-11ea-888e-612b206c097f.gif)

**Comment by BingLee75** [comment] 2020-04-11 17:38
yes, I checked the issue still exists, latest installation, no spaces in the image file path or document name.

OS: Win 10
MarkText Version: v0.16.1

**Comment by xingdaos** [comment] 2020-04-15 07:29
> Thank you for reporting the issue. We noticed that this may be a duplicate of #1367. You could download the latest release candidate from Github releases - otherwise replacing all path spaces with `%20` should work too. Please try out, whether you can reproduce this issue on the latest release candidate or with an image without path spaces.

no spaces in the image file path or document name, I meet the problem too

**Comment by acicovic** [comment] 2020-04-29 10:01
I can also reproduce the issue in 0.16.1 (Windows 10 x64 1909) in a path without spaces.

Let me know if you need more info.

Thanks!

**Comment by acicovic** [comment] 2020-04-29 10:06
I exported this in HTML and have the same issue. I noticed that the img tag has not src attribute. This is the HTML I'm getting:

```html
<img data-align="center" alt="www.google.com-20200427210637.jpg" title="">
```
So this is not just a PDF issue. It seems more like the src attribute is not generated.

**Comment by fxha** [comment] 2020-05-17 13:53
Thanks for all your feedback! There is an issue with our HTML [sanitizer](https://github.com/marktext/marktext/blob/6892a143939017f07c9fdabb93e468f20bcaf3aa/src/muya/lib/utils/exportHtml.js#L145) that removes all image paths on Windows. I'll open an upstream issue and hope we can solve the issue quickly.

E.g:

- UNIX: `/home/felix/abc.png` -> ok
- `C:\Users\Felix\Pictures\abc.png` -> removed
- `file:///C:\Users\Felix\Pictures\abc.png` -> removed
- `file:///C:/Users/Felix/Pictures/abc.png` -> removed
- `Pictures\abc.png` and `Pictures/abc.png` -> ok (not used by Mark Text)

**Comment by lewisl** [comment] 2020-05-30 20:32
Same thing on Mac.  v0.16.1

**Closed** 2020-05-31 21:18 UTC
Labels: :beetle: pri/major, :hamster: platform/windows, 🐛 bug, 🐟  blocked/upstream
