### ISSUE TITLE
support for setting up a base folder for locating markdown images

### ISSUE THREAD

**Issue by orangejuice** [marktext/marktext#949] opened 2019-04-15 22:56 UTC
### Describe your feature request

as yaml front matter is supported also, 
this function typically useful in some situation e.g. both locally writing and some static blogs rendering will can have a seamless experience.

**Comment by fxha** [comment] 2019-04-16 18:07
I think this is a duplicate of #386?

**Comment by orangejuice** [comment] 2019-04-16 18:15
sorry my decription. 😄  i mean, to set a base folder which used to find the exact location of images in this markdown file.

as like in typora:
![](https://i.loli.net/2019/04/17/5cb61b8b4874d.jpg)

**Comment by fxha** [comment] 2019-04-16 18:21
Sorry, my bad. Related to #549.

**Comment by orangejuice** [comment] 2019-04-16 18:28
emm, actually it's kind of 2 different features, but the feature of #549, copying an pasted image to a pre-customized folder and automaticely insert it would also be great. my proposed feature is aiming for setuping a base url for locating images.

**Comment by fxha** [comment] 2019-04-16 18:46
Yes that true. It's just related to the other issue because these issues can be good implemented together and to note this I mentioned the other issue here. `/` or another marker point to the root or relative filesystem where we don't have permissions to read/write. We need to change some logic to implement this feature.

**Comment by orangejuice** [comment] 2019-04-16 19:45
thanks! 😄

**Closed** 2019-05-26 16:03 UTC
Labels: :unicorn: feature request

**Comment by johanhelsing** [comment] 2021-12-13 07:50
How can this be enabled now? I tried opening a folder, but root urls still seem to fail:

![image](https://user-images.githubusercontent.com/2620557/145772128-e12a762b-ca53-4509-bdc2-b0904fe36321.png)

That is: I have one shared `assets` folder for all posts that is at the root of my project.
