### ISSUE TITLE
marktext.app is down

### ISSUE THREAD

**Issue by stevesobol** [marktext/marktext#3312] opened 2022-06-15 21:17 UTC
The domain is registered, but my web browser says there is an NXDOMAIN when I try to visit https://marktext.app.

Thanks

**Comment by aHappyConstant** [comment] 2022-06-18 08:19
Duplicate of #3243 and #3284

**Comment by lianxia2020** [comment] 2022-06-22 19:53
[https://marktext.app](https://marktext.app/)/Cannot open while accessing this site, Browser tips:DNS_PROBE_FINISHED_NXDOMAIN

**Comment by aleung** [comment] 2022-07-12 03:43
https://github.com/marktext/website/issues/70

**Comment by imran-ur-rahman** [comment] 2022-08-09 16:10
![Marktext app Domain Error](https://user-images.githubusercontent.com/41681974/183702904-a6ac3a6c-ac05-4fdd-b018-ae9316eb2443.png)

**Comment by Jocs** [comment] 2023-08-03 13:45
The new official website is already available, https://www.marktext.cc/

**Closed by Jocs** 2023-08-03 13:45 UTC
