### ISSUE TITLE
File opening issues

### ISSUE THREAD

**Issue by itsagoodbrain** [marktext/marktext#501] opened 2018-10-11 11:25 UTC
Doesn't open files as expected on linux.

1. On linux, KDE Manjaro
2. Use distributed AppImage
3a. In terminal ./marktext-0.12.25-x86_64.AppImage Documents/Untitled.md
OR
3b. Try to open a file from Dolphin (the KDE file explorer)

**Expected behavior:** [What you expected to happen]
Marktext starts and opens the file Untitled.md and perhaps displays the folder contents as well in the sidebar.
![expected](https://user-images.githubusercontent.com/14111646/46800550-015b1d80-cd26-11e8-84f3-9031f7e6071a.png)

**Actual behavior:** [What actually happened]
A white window is created which but rendering is wrong font and the interface is never created. The window is then unresponsive. 
![actual](https://user-images.githubusercontent.com/14111646/46800556-0a4bef00-cd26-11e8-9d65-ddef266ae9c6.png)

After quite a while, this error is generated if in the terminal. Also the application must be force closed.

<--- Last few GCs --->

[4015:0x10c1ca286000]   167077 ms: Mark-sweep 2065.7 (2116.2) -> 2065.7 (2100.2) MB, 1994.4 / 6.3 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1994 ms) last resort GC in old space requested
[4015:0x10c1ca286000]   169138 ms: Mark-sweep 2065.7 (2100.2) -> 2065.7 (2100.2) MB, 2060.0 / 6.3 ms  last resort GC in old space requested

<--- JS stacktrace --->
Cannot get stack trace in GC.

### Versions

- Mark Text: marktext-0.12.25-x86_64.AppImage
- OS: Linux, 4.18.12-1-MANJARO

**Comment by fxha** [comment] 2018-10-11 11:59
Thanks @itsagoodbrain, I think the issue is a duplicate of #481 which is already fixed on master. I tried to reproduce the problem with the latest dev. version and the problem no longer occurs - but I can reproduce it with the latest stable (0.12.25) release.

I guess we will release a pre-release version soon.

**Closed** 2018-10-12 14:32 UTC
Labels: duplicate, linux
