### ISSUE TITLE
Autostart Show Sidebar and Tab Bar

### ISSUE THREAD

**Issue by kaeptnkrunch** [marktext/marktext#2378] opened 2020-11-04 21:23 UTC
### Describe your feature request

Hello,

I use Mark Text since some months, but i really miss one Feature. To set up the Sidebar and Tab Bar at Autostart. I would love to have this option by using a Checkbox at the Settings.

### What problem does this feature solve? [optional]

It solves the Problem that i always have to go to the View Menu and activate the View Settings.

### Additional context [optional]

![Screenshot_20201104_222145](https://user-images.githubusercontent.com/55900780/98169277-442f5580-1eec-11eb-86e0-3563e039fd0c.png)

**Comment by brainchild0** [comment] 2020-11-04 23:14
Possible duplicate of #2271.

**Comment by fxha** [comment] 2020-11-13 12:43
Thank you for reporting the issue. We noticed that this is a duplicate of #1274. You may want to subscribe there for further updates.

**Closed by fxha** 2020-11-13 12:43 UTC
