### ISSUE TITLE
点击大纲，无法跳转

### ISSUE THREAD

**Issue by yuanleyuanleyuan** [marktext/marktext#2768] opened 2021-12-16 07:01 UTC
### Description

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text version:
- Operating system:

**Comment by DYH-Hong** [comment] 2021-12-16 08:48
Duplicate of #2736

**Closed** 2021-12-18 13:56 UTC
