### ISSUE TITLE
Unexpected error: Invalid state: all arguments must be non-null.

### ISSUE THREAD

**Issue by yanjingfan** [marktext/marktext#3083] opened 2022-02-28 03:11 UTC
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: Invalid state: all arguments must be non-null.
    at Object.register (D:\Program Files\MarkText\resources\app.asar\node_modules\@hfelix\electron-localshortcut\src\electron-localshortcut.js:167:11)
    at Object.registerKeyHandlers (D:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:288839)
    at Object.addEditorMenu (D:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:295113)
    at Xt.createWindow (D:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:254198)
    at Object._createEditorWindow (D:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:302982)
    at Object._openPathList (D:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:304520)
    at Object._openFilesToOpen (D:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:303313)
    at App.<anonymous> (D:\Program Files\MarkText\resources\app.asar\dist\electron\main.js:2:300903)
    at App.emit (node:events:394:28)
```

### Version

MarkText: v0.17.0
Operating system: Windows_NT x64 10.0.19044 (win32)

**Comment by yanjingfan** [comment] 2022-02-28 03:36
I just delete the Misc 1st to 10st，and add Transform into Heading 1 to 6 
![image](https://user-images.githubusercontent.com/37790182/155919884-ab1a149d-7790-4e82-95f3-2213bc0620ea.png)
![image](https://user-images.githubusercontent.com/37790182/155919834-3152bce4-a02b-4b41-9269-495aca6229cc.png)

**Comment by fxha** [comment] 2022-02-28 19:12
Duplicate of #3074, but I'll keep this open until a hotfix is released.

**Closed** 2022-03-07 18:09 UTC
Labels: 🦞 resolved/duplicate, :honeybee: resolved/fixed but not released
