### ISSUE TITLE
Ability to create directory inside the root directory

### ISSUE THREAD

**Issue by Waqar144** [marktext/marktext#1459] opened 2019-10-08 12:46 UTC
### Ability to create directory inside the root directory

For example I have a Notes directory which looks like this
```
Notes\
-- Folder 1\
-- Folder 2\
---- SubFolder\
```
There is no option(at least that I know of) to create a directory inside `Notes`. I know I can create directories inside the sub-directories.

**Comment by fxha** [comment] 2019-10-08 17:40
Duplicate of #1239.

**Closed by fxha** 2019-10-08 17:40 UTC
