### ISSUE TITLE
Markdown contained in html block not rendering.

### ISSUE THREAD

**Issue by JACK0YORK** [marktext/marktext#2602] opened 2021-06-15 15:28 UTC
### Description

Markdown contained in html block not rendering.

### Steps to reproduce

1. Create an html block in Mark Text
2. Add any markdown to the inside of the html block.

**Example:**

```html
<div>

*italic*

</div>
```

**Expected behavior:**

<div>

*italic*

</div>

**Actual behavior:**

<div>

\*italic*

</div>

### Versions

- Mark Text: v0.16.3
- Operating system: Windows 10 Home 10.0.19042

**Comment by DYH-Hong** [comment] 2021-12-20 02:45
Duplicate of #2308

**Comment by Jocs** [comment] 2021-12-29 04:01
Duplicated of #1764

**Closed by Jocs** 2021-12-29 04:01 UTC
