### ISSUE TITLE
Export to PDF while using dark theme generates black PDF

### ISSUE THREAD

**Issue by tonydiep** [marktext/marktext#683] opened 2019-02-10 13:07 UTC
### Description

If you're using the dark theme and you export to PDF, the PDF is a big rectangle of black.

- [X] Can you reproduce the issue? 

### Steps to reproduce

1. Theme -> Dark
2. File -> Export -> PDF

**Expected behavior:**

Black text on white background

**Actual behavior:**

* Black text (presumably) on black background

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.65
- Operating system: CentOS Linux release 7.6.1810 (Core)

**Comment by raphaelmartin** [comment] 2019-02-13 23:00
Even theme > Light produces a big white rectangle...

**Comment by fxha** [comment] 2019-02-14 13:11
Duplicate of #583

**Closed by fxha** 2019-02-14 13:11 UTC
