### ISSUE TITLE
official website download link 404

### ISSUE THREAD

**Issue by scarqin** [marktext/marktext#3107] opened 2022-03-07 07:23 UTC
![image](https://user-images.githubusercontent.com/15225835/156986083-ea4673cb-d80b-44df-97e5-d5bd47552eaf.png)

### Description
click and download 【MacOS】 version,resource not find

**Comment by DYH-Hong** [comment] 2022-03-07 11:36
Duplicate of https://github.com/marktext/website/issues/60

**Closed** 2022-03-07 13:34 UTC
