### ISSUE TITLE
Marking text over two lines is not behaving correctly

### ISSUE THREAD

**Issue by btmsn** [marktext/marktext#2417] opened 2020-11-29 23:32 UTC
### Description

As you can see on my uploaded image the marking feature is not working properly.

![image](https://user-images.githubusercontent.com/75227076/100556476-f7e4f480-32a2-11eb-9328-28fa78cf237b.png)

- [Yes] Can you reproduce the issue? 

### Steps to reproduce

Just write a sentence over two lines in the document that is marked.

**Expected behavior:**

All text between the marking syntax should be marked.

**Actual behavior:**

See my screenshot above.

### Versions

- Mark Text version: v0.16.2
- Operating system: Win 10

**Comment by fxha** [comment] 2020-12-01 22:16
Thank you for reporting the issue. We noticed that this is a duplicate of #2353.

**Closed by fxha** 2020-12-01 22:16 UTC
