### ISSUE TITLE
Save images in same folder as markdown-file

### ISSUE THREAD

**Issue by mbranchnl** [marktext/marktext#2309] opened 2020-08-19 20:25 UTC
### Describe your feature request

I like the feature of being able to paste an image in my marktext files. There are a few options but i'm missing the option to save the pasted image in the same folder as where my markdown file is.

### What problem does this feature solve? [optional]

Being able to 'export' and easly send the markdown file with the attachments with it.

**Comment by brainchild0** [comment] 2020-08-19 22:11
Is this request the same as in #549?

**Comment by fxha** [comment] 2020-08-28 11:41
Thank you for reporting the issue. We noticed that this is a duplicate of #549. You may want to subscribe there for further updates.

**Closed by fxha** 2020-08-28 11:41 UTC
