### ISSUE TITLE
Ctrl+F search doesn't jump to results

### ISSUE THREAD

**Issue by axelsimon** [marktext/marktext#2471] opened 2021-01-12 14:16 UTC
### Description

When i search a document for a term that i know appears multiple times, Marktext tells me how many times the term appears but hitting <kbd>enter</kbd> to jump to each result doesn't work. Instead, i can see marktext slightly move the viewport down. If i press ctrl+f again, i can see marktext move the viewport slightly back up.

Clicking the up and down arrows in the search pop-up menu bar doesn't work either, and just shifts the viewport up or down slightly.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Open MarkText
2. Open a file from the recent files.The file makes heavy use of code snippets, if that matters.
3. Hit ctrl + F, type in my search term
4. Press enter, viewport moves slightly instead of jumping to the result.

**Expected behaviour:**

Ctrl + F search works.

**Actual behaviour:**

Ctrl + F search is unusable.

### Versions

- Mark Text version: v0.16.3 (Flatpak)

- Operating system: Fedora 32

**Comment by XavierCLL** [comment] 2021-02-08 00:13
I can confirm this bug, and this is a HiDPI scaling issue, issues related: #2424 #1775 

you could confirm that this is a scaling issue testing it running Marktext as: `marktext --force-device-scale-factor=1`

**Comment by YalandHong** [comment] 2021-12-02 02:50
Duplicate of #2424

**Comment by fxha** [comment] 2021-12-23 16:47
Closing as duplicate.

**Closed by fxha** 2021-12-23 16:47 UTC
