### ISSUE TITLE
Keyboard selection bug in bold / italic text

### ISSUE THREAD

**Issue by H16Y** [marktext/marktext#631] opened 2018-12-24 07:45 UTC
### Description

Using `Shift+Left` can cause the selection abnormal.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Type some words and make them bold / italic.
2. Put the cursor inside the text.
3. Try using `Shift+Left` to select some text.

**Expected behavior:**

Text is precisely selected.

**Actual behavior:**

When the selection has time internals between each operation, I can only select one character in the end.

**Link to an example: [optional]**

![8](https://user-images.githubusercontent.com/45055956/50393658-9f417e80-0792-11e9-8cbb-3eec49c719cf.gif)

### Versions

- Mark Text: v 0.13.65
- Operating system: Win10 1607 x64

**Comment by Jocs** [comment] 2018-12-26 05:20
@H16Y How strange, I can not reproduce this issue, and I can select multiple characters.

**Comment by fxha** [comment] 2019-01-02 16:22
@Jocs @H16Y We had a similar issue #240/#513 which we have fixed somehow. It may be because of the change from `<bold>text</bold>` to `<bold>**text**</bold>`.

**Comment by Jocs** [comment] 2019-04-20 02:38
@fxha @H16Y does this issue only existed on Linux and Windows? Because I can not reproduce this issue on macOS.

**Comment by fxha** [comment] 2019-06-02 20:47
Issue is fixed on develop branch.

**Closed by fxha** 2019-06-02 20:47 UTC
Labels: :hamster: platform/windows, :penguin: platform/linux, 🐛 bug
