### ISSUE TITLE
Undo -> Source Code Mode -- text still present.

### ISSUE THREAD

**Issue by mupchrch** [marktext/marktext#747] opened 2019-03-11 13:55 UTC
### Description

Performing an undo and then viewing the source will show that you still have the undone text present in the file.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. In a new document, type `test`.
2. Perform an undo operation (`cmd/ctrl + z`).
3. Go to View > Source Code Mode
4. Notice the source code has the text you've removed via the undo action.

**Expected behavior:**

The text you have undone will not be present in Source Code Mode.

**Actual behavior:**

The text you have undone is present.

### Versions

- Mark Text: v0.13.65
- Operating system: MacOS v10.12.6

**Comment by fxha** [comment] 2019-09-23 15:28
Closing this issue because it's not reproducible with the latest version.

**Closed by fxha** 2019-09-23 15:28 UTC
Labels: 🐛 bug
