### ISSUE TITLE
Unexpected error: Config schema violation: `spellcheckerLanguage` should match pattern "^[a-z]{2}(?:[-][A-Z]{2})?$"

### ISSUE THREAD

**Issue by Rogh64** [marktext/marktext#2341] opened 2020-09-15 18:12 UTC
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
Error: Config schema violation: `spellcheckerLanguage` should match pattern "^[a-z]{2}(?:[-][A-Z]{2})?$"
    at ElectronStore._validate (C:\Program Files\Mark Text\resources\app.asar\node_modules\conf\index.js:154:10)
    at ElectronStore.set store [as store] (C:\Program Files\Mark Text\resources\app.asar\node_modules\conf\index.js:460:8)
    at ElectronStore.set (C:\Program Files\Mark Text\resources\app.asar\node_modules\conf\index.js:339:14)
    at Yt.setItem (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:293546)
    at C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:293633
    at Array.map (<anonymous>)
    at Yt.setItems (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:293620)
    at IpcMainImpl.<anonymous> (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:294075)
    at IpcMainImpl.emit (events.js:210:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3908:15)
```

### Version

Mark Text: v0.16.2
Operating system: Windows_NT x64 10.0.19041 (win32)

**Comment by brainchild0** [comment] 2020-09-30 00:06
What country and language locale do you use on your system? What country and language dictionary are you using for spell checking?

This issue is likely a duplicate of #2280.

**Comment by fxha** [comment] 2020-11-13 12:52
Thank you for reporting the issue. We noticed that this is a duplicate of #2280. You may want to subscribe there for further updates.

**Closed by fxha** 2020-11-13 12:52 UTC
