### ISSUE TITLE
review main window layout

### ISSUE THREAD

**Issue by brainchild0** [marktext/marktext#2076] opened 2020-04-29 11:40 UTC
Currently, the layout of the main application features a bar showing the path and file name directly above the editing pane. In the case of use with the application's custom (non-native) title bar, this feature may be very useful. However, with a native title bar, the additional bar is largely redundant. Therefore,  removing it offers a cleaner appearance that many users may prefer.

The same bar also contains a file statistics summary. This information is generally useful, but could be moved to a lower status bar, which  could also be populated with buttons to control view features, such as sidebar visibility and editing mode.  Currently, these options are only accessible by drop-down menu.

Some rearranging of this kind might be considered to help make the layout less cluttered and also more convenient.

**Comment by fxha** [comment] 2020-06-11 22:01
Thank you for reporting the issue. We noticed that this is a duplicate of #1847. You may want to subscribe there for further updates.

**Closed by fxha** 2020-06-11 22:01 UTC

**Comment by msangel** [comment] 2022-08-25 23:29
"statistics summary" bar can be togglable, since it may be distracting.
