### ISSUE TITLE
Unexpected error: Cannot read property '1' of null

### ISSUE THREAD

**Issue by bound2020** [marktext/marktext#1150] opened 2019-07-15 06:52 UTC
### Description

An unexpected error occurred in the main process.

I insert a code block and write some lines of python code. This error window first pops up when I type a "#" and it appears from time to time since then.

### Stack Trace

```
TypeError: Cannot read property '1' of null
    at matches (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/webpack:/src/main/utils/index.js:31:14)
    at Array.map (<anonymous>)
    at map (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/webpack:/src/main/utils/index.js:28:24)
    at EventEmitter.getRecommendTitle (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/webpack:/src/main/actions/file.js:74:27)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Mark Text.app/Contents/Resources/electron.asar/browser/api/web-contents.js:346:13)
    at WebContents.emit (events.js:182:13)
```

### Version

Mark Text: v0.14.0
Operating system: darwin

**Comment by fxha** [comment] 2019-07-15 22:14
Thanks for reporting this issue. We noticed that this is a duplicate of #1128. You may want to subscribe there for further updates. There is definitely a problem because the title is extracted from the code block and not from a heading.

**Closed by fxha** 2019-07-15 22:14 UTC
