### ISSUE TITLE
Cursor jumps to the front unexpectedly when deleting the last line in code fence

### ISSUE THREAD

**Issue by sgon00** [marktext/marktext#2153] opened 2020-05-26 14:51 UTC
OS: debian 10

If I have something like:

<pre>
```
something
something
something
something|
```
</pre>

Symbol `|` indicates the cursor. 
Now, 
**Case 1:** I press `SHIFT+HOME` to select the last `something`. Then press `Backspace` button to delete the word.
**Case 2:** Simply press `Backspace` again and again to delete the last line char by char, once the last char `s` deleted from the last line: 

The expected behavior is the following (Note the cursor positioin):

<pre>
```
something
something
something
|
```
</pre>

But the current behavior is:

<pre>
```
s|omething
something
something

```
</pre>

Note the cursor position.

This is very dangerous when I edit something very fast. 
Thanks a lot.

**Comment by RomanKornev** [comment] 2020-05-28 09:49
Can confirm, sometimes it also happens when I edit the last list item

**Comment by YalandHong** [comment] 2022-01-04 02:12
Duplicate of #2013, which contains a GIF and better format.

**Closed** 2022-01-23 07:51 UTC
