### ISSUE TITLE
Create a list entry using *

### ISSUE THREAD

**Issue by mklpiening** [marktext/marktext#235] opened 2018-05-03 20:29 UTC
### Description

I try to create a list using a *.
If i try to write a * it creates a second * behind my cursor.
To create a list i now press enter and a list element is being created.
Now the second * stays behind my cursor.
It would me much more comfortable if the * behind my cursor would get removed when i create a list element.

### Steps to reproduce

1. write a *
2. it creates two *
3. press enter
4. it replaces the first * by a list entry dot

**Expected behavior:** The second * should be automatically removed because i'd like to create a list.

**Actual behavior:** I get a list entry containing a * behind my cursor.

### Versions

- Mark Text: v 0.10.21
- OS: macOS 10.13.4

**Comment by fxha** [comment] 2018-05-03 21:10
Thanks @mklpiening,

the problem is that `*` and `**` is also used for *emphasis* and **strong** paragraphs. The double star comes from the auto-completion to enhance user experience. As a workaround: you can use `-` for normal lists.

What's your opinion, @Jocs? Maybe check for `*` not followed by text and remove it, because it's horrible to create a list with `*`. I don't think someone would create a list with a star (`* *`) .

@Jocs BTW Mark Text currently converts `*` lists into `-` lists. I think this is a bug too, because CommonMark and GFM support `*`, `-` and `+` lists.

**Comment by Jocs** [comment] 2018-05-04 00:59
@mklpiening @fxha this issue has been fixed on the master branch, Mark Text will detect weather `*` is open a list item, if it is, Mark Text will remove the second `*`.

**Closed** 2018-05-08 14:27 UTC
Labels: fixed but not released
