### ISSUE TITLE
[feature request]more extension/plugins

### ISSUE THREAD

**Issue by retsyo** [marktext/marktext#1831] opened 2019-12-20 05:07 UTC
as we can find on http://mdp.tylingsoft.com/, more extension is supported. Will marktext support them, for example, `AsciiMath`. `Charts`, `mermaid charts`? Thanks

**Comment by retsyo** [comment] 2019-12-20 05:11
its code is on https://github.com/tylingsoft/markdown-plus

**Comment by fxha** [comment] 2019-12-20 20:51
Thank you for suggestion but we noticed that this is a duplicate of #375 and #224. You may want to subscribe there for further updates.

**Closed by fxha** 2019-12-20 20:51 UTC
