### ISSUE TITLE
Support relative path for saving images locally

### ISSUE THREAD

**Issue by ribtoks** [marktext/marktext#1860] opened 2020-01-13 19:32 UTC
### Describe your feature request

I structure my markdown files in a directory tree. Some files have assets like images. I'm saving assets in the directory `./assets/` along with the markdown file. I would love to switch to this wonderful editor, but I cannot because it does not work with relative assets paths. It only allows me to use absolute filepath by selecting a directory.

### What problem does this feature solve? [optional]

Organizing assets.

### Additional context [optional]

Some other editors like [Typora](https://typora.io) support this mode when you just write a relative path for pasting images instead of selecting an absolute directory (which does not work if you have more than 1 asset directory).

**Comment by FireFrei** [comment] 2020-01-15 16:10
I structure my projects the same way. So this is also a feature I would need. 
In addition, this would work great combined with the possibility to automatically copy images to a relative dir (same dir as md-file or subdir like ./assets/).
This enables a simple copy functionality for e.g. web images to my markdown notes.

**Comment by loughnane** [comment] 2020-01-30 16:49
This is the same for me. I have my project root is at `C:/Users/cl/code/ROOT`  and I stored all my assets at `C:/Users/cl/code/ROOT/resources`. Most critically is that when I sync to github I need the relative path in order for the images to work.

**Comment by fxha** [comment] 2020-01-30 21:13
Thank you for reporting the issue. We noticed that this is a duplicate of #549. You may want to subscribe there for further updates.

**Closed by fxha** 2020-01-30 21:13 UTC
