### ISSUE TITLE
Strange behaviour (characteres) when copying text from MarkText

### ISSUE THREAD

**Issue by drapado** [marktext/marktext#2030] opened 2020-04-04 13:37 UTC
### Description
When I try to copy some text from MarkText to other application (terminal, firefox, etc.) I get always the HTML encoding. For instance:
* Text copied from MarkText: `find .. -name '*.flac' > playlist.m3u`
* When I paste in a different app: `find .. -name &#39;*.flac&#39; &gt; playlist.m3u`

This happens if I copy normally with shortcuts or if I use the option copy as Markdown.

- [x] Can you reproduce the issue?

### Versions

- Mark Text: 0.16.1
- Operating system: Manjaro Linux 19.0.2

**Comment by mbranchnl** [comment] 2020-04-06 09:24
FYI: Same issue exists in version 0.16.1 on Windows 10.

**Comment by vinliao** [comment] 2020-05-07 03:50
Same problem. Fedora 32, version 0.16.1.

**Comment by Papyruse** [comment] 2020-05-13 18:51
Same problem. Mac OS Catalina, version 0.16.1 too.

**Comment by fxha** [comment] 2020-06-06 23:57
Thank you for reporting the issue. We noticed that this is a duplicate of #1821. You may want to subscribe there for further updates.

**Closed by fxha** 2020-06-06 23:57 UTC
