### ISSUE TITLE
Unable to un-indent a list item

### ISSUE THREAD

**Issue by LateralLines** [marktext/marktext#2466] opened 2021-01-04 18:43 UTC
### Description

Isn't possible to indent to the left in regular view (different behaviour in other view modes)

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Create list
2. Indent first item then indent again for second item
3. Un-indenting a third item (moving it back to item #1 indentation) doesn't work with either the `shift + tab` or `ctrl + [` shortcuts. It seems in order to properly indent to the left by any amount, you have to move down one line (using down arrow key) and manually re-indent.

**Expected behavior:**

Before:
- Item1
    - Item 2
    - Item 3

After:
- Item1
    - Item 2
- Item 3

**Actual behavior:**

Before:
- Item 1
    - Item 2
    - Item 3

After:
- Item 1
    - Item 2
    -     Item 3 (same bullet level as item 2, just tabbed over one)

*Sidenote #1* - `ctrl + [` and `ctrl + ]` does absolutely nothing (in default view mode)

*Sidenote #2* - When in Source Code mode however, both `shift + tab` and `ctrl + [` function as expected

### Versions

- Mark Text version: 0.16.3.3214 (launched from .appimage executable instead of installed using .deb installer)
- Operating system: Linux Mint (cinnamon desktop)

Edit: formatting

**Comment by zapme** [comment] 2021-01-19 15:06
Same issue, but
`shift + tab` indents another level

Versions

- Mark Text version v0.16.3
- OS: MacOS Big Sur 11.1 (20C69)

**Comment by jenyangk** [comment] 2021-02-07 22:37
Getting the same issue too.
`shift + tab` indents to another level.

Info:
- Version: v0.16.3
- OS: Windows 10 20H2

**Comment by abuisman** [comment] 2021-02-17 09:12
Same issue:

- Version: v0.16.3 (version in 'About' says 0.16.2 even though I downloaded 0.16.3 🤷‍♂️)
- OS: macOS Catalina v 10.15.7

**Comment by HelloWorld017** [comment] 2021-03-07 06:08
IMHO, I suspect commit 5fb130d96.
Shouldn't [tabCtrl.js#L312](https://github.com/marktext/marktext/blob/develop/src/muya/lib/contentState/tabCtrl.js#L312) be `if (event.shiftKey && startBlock.functionType !== 'cellContent') {`?

**Comment by t-arney** [comment] 2021-04-01 19:10
Possible duplicate of #2371

**Comment by XuluWarrior** [comment] 2021-04-10 10:56
I just updated to 0.16.3 and immediately hit this bug.  Rolling back to 0.16.2 for now.

**Comment by markmillerdev** [comment] 2021-04-14 17:58
I am experiencing it with v0.16.3 on a Mac

**Comment by jottr** [comment] 2021-04-18 23:01
This should be considered a servere bug, since it breaks a core functionality of the application.
@Jocs would you mind having a look?

**Comment by SidG2k1** [comment] 2021-04-19 07:31
Same issue:

Version: v0.16.3
OS: Ubuntu 20.04.2 LTS

**Comment by emileoost** [comment] 2021-04-30 04:03
I've managed to solve it the following way on v0.16.3 OS: MacOS Big Sur:

Summary:
- Press Enter 3 times
- Works for Ordered and Bullet lists

1. Press 1st Enter
This creates a new line with the same indent and bullet.

2. Press 2nd Enter
This indents to the left but removes the bullet.

3. Press 3rd Enter
This keeps the same indent but adds the bullet again.

Continue pressing Enter until you get to the intended indent.

**Comment by o5t6iaqo7** [comment] 2021-08-21 19:19
I am having this problem and it is very frustrating, a major functionality broken, macOS 11.5.2 and Mark Text 0.16.3. The fix suggested by emileoost worked but was very cumbersome. I downgraded Mark Text to 0.16.2 and it works fine, indent / outdent un-indent as in other editors. This issue has two open threads that could be combined so I will cross-post at:

**Closed** 2021-11-29 16:12 UTC
