### ISSUE TITLE
导出PDF文档中无法显示图片

### ISSUE THREAD

**Issue by DerekSun96** [marktext/marktext#1268] opened 2019-08-15 14:08 UTC
版本：v0.15.0
### Description

图片都是自动粘帖到md文档中的，marktext会自动保存在它默认的目录下
当导出PDF或者HTML后，打开PDF或HTML发现文档里面所有的图片都显示成了路径，而不是可见的图片

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text:
- Operating system:

**Comment by Jocs** [comment] 2019-10-02 16:48
请问下有截图吗？你的图片时本地路径还是网络图片？

**Comment by xingdaos** [comment] 2019-10-18 10:58
我也遇到了同样的问题：
* marktext 版本：v0.15.1
* 操作系统：windows 10 x 64
* marktext 截图：
![image](https://user-images.githubusercontent.com/33388842/67088475-d24c7700-f1d7-11e9-829b-d95dbe0307a1.png)
* marktext 源码截图：
![image](https://user-images.githubusercontent.com/33388842/67088656-4dae2880-f1d8-11e9-8eb0-8f72fb6b2f38.png)
* 导出 HTML 截图：
![image](https://user-images.githubusercontent.com/33388842/67088513-e98b6480-f1d7-11e9-8140-fb4c7d40ed15.png)
* HTML 源码截图：
![image](https://user-images.githubusercontent.com/33388842/67088566-09bb2380-f1d8-11e9-95b0-c78c2b68aeb3.png)
* 导出 pdf 截图：
![image](https://user-images.githubusercontent.com/33388842/67088593-1e97b700-f1d8-11e9-81d9-40c7d869a025.png)
---
PS：希望导出的 HTML 可以使用 base64 格式存储图片，方便后期分享
PS：希望可以增加`标题序号`和`[toc]`功能，格式更显标准
PS：在线更新貌似有问题，试了 n+1 次，均未成功

**Comment by fxha** [comment] 2019-12-20 21:35
@Jocs Is this issue still active or can we close it?

**Comment by javafun** [comment] 2020-02-12 22:28
The issue still exists. I tested with the latest `martext` on windows 10. Both PDF and html export does not render any image at all.

**Comment by Jocs** [comment] 2020-02-16 11:41
@javafun Can you show us a failed test file with image in it.

**Comment by javafun** [comment] 2020-02-17 02:34
@Jocs 

The issue can be easily reproduced with the following steps

1. Launch `marktext` app from windows start menu
2. Use windows 10 snippet tool to capture a screenshot into clipboard
3. Paste into marktext
4. Export current document as PDF from File menu


In addition, I captured a video clip to demonstrate this issue
https://vimeo.com/365364540

Let me know if you have enough information

**Comment by Jocs** [comment] 2020-02-23 02:59
I opened the link above and found it's not the marktext using video?

**Comment by javafun** [comment] 2020-02-23 03:58
> I opened the link above and found it's not the marktext using video?

I don’t know why the link was changed. I’ve updated the link, pls check again 


https://vimeo.com/391883646?ref=em-share

**Comment by Jocs** [comment] 2020-02-23 04:30
@javafun Can you show me the markdown file content after you insert the screenshot.

**Comment by javafun** [comment] 2020-02-24 23:27
> @javafun Can you show me the markdown file content after you insert the screenshot.
Hi @Jocs 
Below is what I copied from the MD file. I replaced my actual username with `{Username}` for privacy concern. 
`
test pdf export   

![](C:\Users\{Username}\AppData\Roaming\marktext\images\2020-02-25-10-23-55-image.png)

`

**Comment by xingdaos** [comment] 2020-03-10 10:13
@Jocs I have update to v0.16.0-rc.3 , but this problem is still exist , this file is the video for the question to appear .
[export-pdf-noImage-video.zip](https://github.com/marktext/marktext/files/4311650/export-pdf-noImage-video.zip)

**Comment by fxha** [comment] 2020-06-06 23:43
Duplicate of #1997.

**Closed by fxha** 2020-06-06 23:43 UTC
Labels: :baby_chick: blocked/need info
