### ISSUE TITLE
[Feature Request] Middle Click to close tab

### ISSUE THREAD

**Issue by Zavian** [marktext/marktext#1428] opened 2019-10-01 23:11 UTC
### Describe your feature request

Like any other tabbed application works (be it a browser, an IDE or w/e else) It'd be really nice to be able to middle mouse click on a tab and close it. Currently (at least on windows) it doesn't seem to be the case. I know it's a pet peeve however sometimes I wonder why it's not already a feature.

**Comment by fxha** [comment] 2019-10-02 09:22
Closing as duplicate of #1266. v0.16.0 will suport this feature.

**Closed by fxha** 2019-10-02 09:22 UTC
