### ISSUE TITLE
Unexpected error: Cannot read property 'webContents' of undefined

### ISSUE THREAD

**Issue by wgqimut** [marktext/marktext#1832] opened 2019-12-20 11:42 UTC
### Description

An unexpected error occurred in the main process.

### Stack Trace

```
TypeError: Cannot read property 'webContents' of undefined
    at click (/Applications/Mark Text.app/Contents/Resources/app.asar/dist/electron/main.js:2:291192)
    at MenuItem.click (/Applications/Mark Text.app/Contents/Resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/Applications/Mark Text.app/Contents/Resources/electron.asar/browser/api/menu.js:31:13)
```

### Version

Mark Text: v0.15.1
Operating system: Darwin x64 19.2.0 (darwin)

**Comment by fxha** [comment] 2019-12-20 20:54
@wgqimut Thank you for taking the time to report the issue. We cannot reproduce this issue without steps to reproduce, please provide some steps or how the error occurred.

**Comment by fxha** [comment] 2019-12-20 21:17
@Jocs Maybe duplicate of #1795?

**Comment by Jocs** [comment] 2020-02-16 10:19
@fxha I also can not reproduce this issue, closed, feel free to reopen it if @wgqimut you can reproduce it.

**Closed by Jocs** 2020-02-16 10:19 UTC
Labels: :baby_chick: blocked/need info, :green_apple: platform/macOS
