### ISSUE TITLE
Multi language Translation Support

### ISSUE THREAD

**Issue by keito940** [marktext/marktext#308] opened 2018-05-30 08:30 UTC
### Description

Mark text seems to be absent in English only, so can you correspond to Japanese, Chinese, etc?
By the way, I am a Japanese user.

### Versions

- Mark Text: v0.11.42
- OS:Windows 10

**Comment by Jocs** [comment] 2018-05-30 09:58
@keito940 , Do you mean that the new version download link absent in `Japanese` and `Chinese` readme?

PR is appreciated!:smile:

**Comment by fxha** [comment] 2018-05-30 10:15
I guess duplicate of https://github.com/marktext/marktext/issues/138#issuecomment-380867653.

**Closed** 2018-06-12 15:34 UTC
Labels: more detail
