### ISSUE TITLE
yarn run build:web Failed!

### ISSUE THREAD

**Issue by silsuer** [marktext/marktext#772] opened 2019-03-17 03:29 UTC
`yarn run build` successfully!

but

`yarn run build:web` will throw many exceptions:

```
ERROR in ./node_modules/electron/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/hongbaoliu/project/marktext/marktext/node_modules/electron'
 @ ./node_modules/electron/index.js 1:9-22
 @ ./src/renderer/main.js

ERROR in ./node_modules/fs-extra/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/hongbaoliu/project/marktext/marktext/node_modules/fs-extra/lib'
 @ ./node_modules/fs-extra/lib/index.js 23:11-24
 @ ./src/renderer/util/fileSystem.js
 @ ./src/renderer/store/project.js
 @ ./src/renderer/store/index.js
 @ ./src/renderer/main.js

ERROR in ./node_modules/fs-extra/lib/empty/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/hongbaoliu/project/marktext/marktext/node_modules/fs-extra/lib/empty'
 @ ./node_modules/fs-extra/lib/empty/index.js 4:11-24
 @ ./node_modules/fs-extra/lib/index.js
 @ ./src/renderer/util/fileSystem.js
 @ ./src/renderer/store/project.js
 @ ./src/renderer/store/index.js
 @ ./src/renderer/main.js

ERROR in ./node_modules/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in '/Users/hongbaoliu/project/marktext/marktext/node_modules/graceful-fs'
 @ ./node_modules/graceful-fs/graceful-fs.js 1:9-22
 @ ./node_modules/fs-extra/lib/fs/index.js
 @ ./node_modules/fs-extra/lib/index.js
 @ ./src/renderer/util/fileSystem.js
 @ ./src/renderer/store/project.js
 @ ./src/renderer/store/index.js
 @ ./src/renderer/main.js

ERROR in ./node_modules/jsonfile/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/hongbaoliu/project/marktext/marktext/node_modules/jsonfile'
 @ ./node_modules/jsonfile/index.js 5:8-21
 @ ./node_modules/fs-extra/lib/json/jsonfile.js
 @ ./node_modules/fs-extra/lib/json/index.js
 @ ./node_modules/fs-extra/lib/index.js
 @ ./src/renderer/util/fileSystem.js
 @ ./src/renderer/store/project.js
 @ ./src/renderer/store/index.js
 @ ./src/renderer/main.js

ERROR in ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'muya/lib' in '/Users/hongbaoliu/project/marktext/marktext/src/renderer/components/editorWithTabs'
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&) 5:0-28 164:6-10 165:6-10 166:6-10 167:6-10 168:6-10 169:6-10 171:39-43
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/editor.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue
 @ ./src/renderer/main.js

ERROR in ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'muya/lib/ui/codePicker' in '/Users/hongbaoliu/project/marktext/marktext/src/renderer/components/editorWithTabs'
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&) 8:0-48 166:15-25
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/editor.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue
 @ ./src/renderer/main.js

ERROR in ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'muya/lib/ui/emojiPicker' in '/Users/hongbaoliu/project/marktext/marktext/src/renderer/components/editorWithTabs'
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&) 9:0-50 167:15-26
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/editor.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue
 @ ./src/renderer/main.js

ERROR in ./src/renderer/components/sideBar/icon.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/sideBar/icon.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'muya/lib/ui/fileIcons' in '/Users/hongbaoliu/project/marktext/marktext/src/renderer/components/sideBar'
 @ ./src/renderer/components/sideBar/icon.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/sideBar/icon.vue?vue&type=script&lang=js&) 3:0-46 15:17-26 17:15-24
 @ ./src/renderer/components/sideBar/icon.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/sideBar/icon.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/sideBar/file.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/sideBar/file.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/sideBar/file.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/sideBar/tree.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/sideBar/tree.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/sideBar/tree.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/sideBar/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/sideBar/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/sideBar/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue
 @ ./src/renderer/main.js

ERROR in ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'muya/lib/ui/formatPicker' in '/Users/hongbaoliu/project/marktext/marktext/src/renderer/components/editorWithTabs'
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&) 11:0-52 169:15-27
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/editor.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue
 @ ./src/renderer/main.js

ERROR in ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'muya/lib/ui/imagePicker' in '/Users/hongbaoliu/project/marktext/marktext/src/renderer/components/editorWithTabs'
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&) 10:0-54 168:15-30
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/editor.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue
 @ ./src/renderer/main.js

ERROR in ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'muya/lib/ui/quickInsert' in '/Users/hongbaoliu/project/marktext/marktext/src/renderer/components/editorWithTabs'
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&) 7:0-50 165:15-26
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/editor.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue
 @ ./src/renderer/main.js

ERROR in ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'muya/lib/ui/tablePicker' in '/Users/hongbaoliu/project/marktext/marktext/src/renderer/components/editorWithTabs'
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&) 6:0-50 164:15-26
 @ ./src/renderer/components/editorWithTabs/editor.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/editor.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue
 @ ./src/renderer/main.js

ERROR in ./src/renderer/components/editorWithTabs/sourceCode.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/sourceCode.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'muya/lib/utils' in '/Users/hongbaoliu/project/marktext/marktext/src/renderer/components/editorWithTabs'
 @ ./src/renderer/components/editorWithTabs/sourceCode.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/sourceCode.vue?vue&type=script&lang=js&) 4:0-59 119:24-36
 @ ./src/renderer/components/editorWithTabs/sourceCode.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/sourceCode.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue?vue&type=script&lang=js&
 @ ./src/renderer/components/editorWithTabs/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue?vue&type=script&lang=js&
 @ ./src/renderer/app.vue
 @ ./src/renderer/main.js

ERROR in ./src/renderer/store/editor.js
Module not found: Error: Can't resolve 'muya/lib/utils/dirtyToc' in '/Users/hongbaoliu/project/marktext/marktext/src/renderer/store'
 @ ./src/renderer/store/editor.js 10:0-61 23:11-29
 @ ./src/renderer/store/index.js
 @ ./src/renderer/main.js

ERROR in chunk web [entry]
web.js
/Users/hongbaoliu/project/marktext/marktext/node_modules/babel-loader/lib/index.js!/Users/hongbaoliu/project/marktext/marktext/node_modules/eslint-loader/index.js??ref--0!/Users/hongbaoliu/project/marktext/marktext/src/renderer/main.js 8d7ccde239ba16024bbe3e3aad228972
Unexpected token (178:39)
|       !(function webpackMissingModule() { var e = new Error("Cannot find module 'muya/lib'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()).use(!(function webpackMissingModule() { var e = new Error("Cannot find module 'muya/lib/ui/formatPicker'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
|
|       var _editor = _this.editor = new !(function webpackMissingModule() { var e = new Error("Cannot find module 'muya/lib'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())(ele, {
|         theme: theme,
|         focusMode: focusMode,
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  556 KiB       0
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.2 KiB {0} [built]
    [1] ./node_modules/lodash/lodash.js 527 KiB {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--2-1!node_modules/postcss-loader/src/index.js??postcss!node_modules/codemirror/lib/codemirror.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--2-1!./node_modules/postcss-loader/src??postcss!./node_modules/codemirror/lib/codemirror.css 8.84 KiB {0} [built]
```

I need for help!

**Comment by Jocs** [comment] 2019-03-17 05:27
>yarn run build:web

Sorry, it's not support build a web version of Mark Text, so `yarn run build:web` does not work.

**Comment by Jocs** [comment] 2019-03-17 05:45
If you want a web version, you can reopen this issue and labeled `feature request`.

**Comment by silsuer** [comment] 2019-03-17 06:15
emmm...... I  can't find any reopen button... maybe I'm not the contributor ?  so sad, but I need the feature, help me to reopen and label it . thx. @Jocs

**Comment by fxha** [comment] 2019-03-17 11:33
@Jocs @silsuer To be honest, I think that this is almost a `won't fix` because we build Mark Text on top of Electron and Mark Text was designed as a standalone application, unlike `muya`.

1. We've using Electron dependencies in the renderer, which is fine because maybe we could replace these dependencies.
2. Renderer is a bridge between the main process (IO, platform specific stuff etc) and muya (our backend which can run in a browser). Meaning you need to port the complete `main` source code to a web-application to communicate with the renderer/muya and load files etc.
3. We are using IPC to communicate between multiple process the same instance. With upcoming feature like sessions, tab drag&drop between multiple windows and so on it will be even more difficult.
4. We would need to official support web and make all changes compatible with it.
5. We would need to support non-Chromium browsers.

I strongly recommend to use `muya` and built a UI around it or make a unofficial project for a web application. @Jocs  Remember that we almost have not time to maintain and refactor Mark Text.

**Comment by Jocs** [comment] 2019-03-17 12:38
@silsuer @fxha Indeed, Mark Text now has a significant portion of the code in the main process, such as menus, and the operating file system. In the renderer process, it also uses a considerable number of node APIs, as well as Electron's API, so in terms of its current form, Packaging into a web application is difficult.

In the near future, we also intend to develop a simple note or reminder application, combining note and reminder, the data will be stored in the browser indexDB, or the server, instead of writing the file system, so that Packaged into a web app, or an Electron app. Of course, we also hope that more developers will participate.

**Closed** 2019-03-17 12:58 UTC
Labels: wontfix

**Comment by 625781186** [comment] 2019-06-01 12:36
@fxha 
I am trying to remove the dependence of electron module.
[https://github.com/625781186/marktext2web](https://github.com/625781186/marktext2web)

Here's how I think about it : 
- Customize an electron module . 

![image](https://user-images.githubusercontent.com/30521429/58748500-58c41e80-84ac-11e9-9f07-a91361a8508b.png)

- Customize a vue instance to replace IPC communication like  "renderer/bus"

![image](https://user-images.githubusercontent.com/30521429/58748528-c2442d00-84ac-11e9-8811-60c8c49e60de.png)
