### ISSUE TITLE
The file was opened without modification, but it prompts whether to save the changes when closing

### ISSUE THREAD

**Issue by lygoing** [marktext/marktext#2264] opened 2020-06-28 10:31 UTC
Version: v0.16.2
OS: Windows 10 2004 64bit

![image](https://user-images.githubusercontent.com/5944432/85945039-94f6d680-b96d-11ea-8c55-eb239ea3b95e.png)

**Comment by brainchild0** [comment] 2020-06-29 01:45
Duplicate of #2189.

**Closed** 2020-08-28 11:44 UTC
