### ISSUE TITLE
win版本点击目录无法在右侧正文跳转

### ISSUE THREAD

**Issue by Evan332211** [marktext/marktext#1432] opened 2019-10-02 14:48 UTC
### Description

无法实现点击目录在右侧正文跳转到相应位置的功能

- [x] Can you reproduce the issue? 

**Expected behavior:**
希望能实现跳转

**Actual behavior:**
无法跳转，正文只是缓慢移动

### Versions

- Mark Text:  0.15.1
- Operating system:   win10 1809 jny教育版

**Comment by Jocs** [comment] 2019-10-13 13:03
@fxha This issue description: Under Windows, click on the title in the TOC of the sidebar, the editor does not scroll to the specified location.

**Comment by Jocs** [comment] 2019-10-13 13:04
And I test it ok on macOS.

**Comment by fxha** [comment] 2019-10-14 21:33
Linux works fine too. I think that's an issue with the heading itself. If I remember correctly, we have a whitelist of allowed characters and all other characters are mapped to an empty string. Normally we have to map all non ASCII characters to ASCII. I guess some UTF-8/Unicode character cause the issue, like a chinese character.

@Jocs @Evan332211 Could you please provide the heading text that doesn't work.

**Comment by Jocs** [comment] 2019-10-15 03:46
@Evan332211 可以提供一份不能工作的 markdown 文件吗？

**Comment by SmallPineApp1e** [comment] 2019-10-20 14:56
[Can't not work on Win10.zip](https://github.com/marktext/marktext/files/3747970/Can.t.not.work.on.Win10.zip)

**Comment by Jocs** [comment] 2019-10-21 02:52
@SmallPineApp1e @fxha I just test the file above, and it works well on macOS.

**Comment by SmallPineApp1e** [comment] 2019-10-21 04:18
> @SmallPineApp1e @fxha I just test the file above, and it works well on macOS.

Glad to reply you! I absolutely know it could work normally on macOS, But it didn't work on Windows10, I have tested several files until now, I'm pretty glad to use marktext to edit markdown file, but it disturbed me to use it normally.Have you tested it on Windows10?

**Comment by fxha** [comment] 2019-10-22 18:33
@SmallPineApp1e I tested the file on Windows 10 and it worked fine (both 0.15.1 and develop). Does the issue appear when opening via command-line, file explorer or via application menu? It's may be an issue with file encoding.

**Comment by esmoak** [comment] 2019-12-04 03:17
I'm having this issue after installing the Flatpak 0.15.1 version on Manjaro linux.

The odd thing is that the Flatpak worked fine on Fedora when I tested it yesterday. 

Existing files and new files created are both affected the same.

**Comment by fxha** [comment] 2019-12-07 21:55
I guess this may be a duplicate of #1775.

**Comment by Jocs** [comment] 2019-12-26 08:50
@fxha duplicated with #1775

**Closed by Jocs** 2019-12-26 08:50 UTC
Labels: :question: confirmation needed

**Comment by kkworld** [comment] 2021-11-28 01:27
win10. I have got the same issue.

**Comment by YalandHong** [comment] 2021-12-03 08:02
> win10. I have got the same issue.

Since it's a dup of #1775, please upvote that issue, report your problems there and check if there's any workaround.

Thanks!
