### ISSUE TITLE
Marktext crashes on startup (Fedora 35)

### ISSUE THREAD

**Issue by harisarang** [marktext/marktext#2943] opened 2022-01-27 03:23 UTC
### Description

Latest version of marktext crashes when trying to open the application

```
(node:74230) DeprecationWarning: file property is deprecated and will be removed in v5.
(node:74230) DeprecationWarning: init() is deprecated and will be removed in v5.
[74230:0127/083951.660632:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Failed to generate minidump.[1]    74230 illegal hardware instruction (core dumped)  marktext
```

- [x] Can you reproduce the issue? 

### Versions

- MarkText version: 0.16.3
- Operating system: Fedora 35 + Gnome

**Comment by harisarang** [comment] 2022-01-27 03:27
P.S. I have found a temporary solution to fix this issue,

Edit the `marktext.desktop` file which is located in `/usr/share/applications/marktext.desktop`


Change,
```
Exec="/opt/Mark Text/marktext" %U
```
to,
```
Exec="/opt/Mark Text/marktext" --no-sandbox %U
```

Then the application will work as expected 😇

**Comment by YalandHong** [comment] 2022-01-27 07:58
Duplicate of #2888

**Closed** 2022-01-27 21:09 UTC
