### ISSUE TITLE
Not working hotkeys Undo/Redo

### ISSUE THREAD

**Issue by 0object** [marktext/marktext#468] opened 2018-08-15 17:27 UTC
### Description

Not working hotkey Undo/Redo Ctrl+Z/Ctrl+Shift+Z. Other hotkeys does work.

### Steps to reproduce

1. Enter text
2. I want undo action
3. Shortcut keys undo does not work. I use the command in menu.

**Link to an example:** https://youtu.be/_mk0gayxPIU

### Versions

- Mark Text: 0.12.25
- Os: Windows 10

**Comment by fxha** [comment] 2018-08-16 11:56
Duplicate of #311 and #216

**Closed by fxha** 2018-08-16 11:56 UTC
