### ISSUE TITLE
Writing 09:00-10:00 renders 00-10 in color

### ISSUE THREAD

**Issue by ayedo** [marktext/marktext#2444] opened 2020-12-22 09:16 UTC
### Description

I'm writing time ranges like so: 09:00-10:00. The renderer highlights the middle of the "range" in blue.

<img width="303" alt="Screenshot 2020-12-22 at 10 04 03" src="https://user-images.githubusercontent.com/4739734/102871148-5afb1e80-443e-11eb-91bd-0db1f80a36c1.png">

- [x ] Can you reproduce the issue? 

### Steps to reproduce

1. Create new file in Marktext
2. Write 09:00-10:00

**Expected behavior:**

I expect no color to be rendered.

**Actual behavior:**

00-10 is rendered in color

### Versions

- Mark Text version: v0.16.2
- Operating system: Mac OS X Catalina 10.15.7 (19H2)

**Comment by saegl5** [comment] 2020-12-22 23:45
It happens to me, too, but even within regular text (i.e., not tables).
Example: Simply type 2606:4700:4700::1111 or 2606:4700:4700::1001 (Cloudflare's IPv6 DNS addresses).

Mark Text v0.16.2
macOS Big Sur 11.1 (20C69)

**Comment by fxha** [comment] 2020-12-23 22:02
Thank you for reporting the issue. We noticed that this is a duplicate of #1677. You may want to subscribe there for further updates.

**Closed by fxha** 2020-12-23 22:02 UTC
