### ISSUE TITLE
Deleting a bullet point creates another superfluous bullet point

### ISSUE THREAD

**Issue by fbruetting** [marktext/marktext#2042] opened 2020-04-13 01:51 UTC
### Description

When you delete a bullet point of the first level, another first level pullet point gets created to a second(!) level item – which then has two bullet points on both levels.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Make two bullet points of the first level and then one at the second level like in the following image.
  ![Bildschirmfoto von 2020-04-13 03-43-06](https://user-images.githubusercontent.com/10520767/79085716-df3ac500-7d39-11ea-9610-797b0354cfcb.png)

2. Delete the text of the first bullet point
  ![Bildschirmfoto von 2020-04-13 03-43-23](https://user-images.githubusercontent.com/10520767/79085728-e7930000-7d39-11ea-88a1-0a93e885a7b1.png)

3. With the cursor still at the (empty) first bullet point, now press Delete (not Backspace!). The second-level bullet point now has two bullets.
  ![Bildschirmfoto von 2020-04-13 03-43-28](https://user-images.githubusercontent.com/10520767/79085738-ecf04a80-7d39-11ea-8d9c-24d9ebb881f6.png)

**Expected behavior:**

No doubled bullet points.

**Actual behavior:**

Doubled bullet points.

### Versions

- Mark Text: v16.1
- Operating system: Fedora Silverblue 31

**Comment by fxha** [comment] 2020-06-06 23:31
Thank you for reporting the issue. We noticed that this is a duplicate of #1845.

**Closed by fxha** 2020-06-06 23:31 UTC
