### ISSUE TITLE
No undo functionality for Source Code Mode

### ISSUE THREAD

**Issue by mi-lee** [marktext/marktext#1639] opened 2019-11-06 22:21 UTC
### Description

Lack of undo functionality for Source Code Mode. 

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Type something in Source Code Mode.
2. Undo it (Cmd+Z, etc)

**Expected behavior:**

It should undo the action just completed.

**Actual behavior:**

Not implemented. Also, typing Cmd+Z will unfocus from the editor (i.e., remove the cursor).

**Link to an example: [optional]**

### Versions

- Mark Text: 0.15.1
- Operating system: Mac OS X

**Comment by DanEble** [comment] 2019-11-11 15:26
I humbly ask: why is this a low-priority issue?  I just lost work because of it.

**Comment by fxha** [comment] 2019-11-11 17:02
> I humbly ask: why is this a low-priority issue? I just lost work because of it.

Because all issue about the source-code editor (CodeMirror) as categorized as low priority because the primary focus is to build a realtime editor. Yes, it's a bit annoying but we have to prioritize the issues somehow. Everyone is welcome to contribute to Mark Text and fix these issues.

**Comment by Jocs** [comment] 2019-11-12 15:23
>I just lost work because of it.

Sorry to hear that, do you mean that using Mark Text with this bug(without this feature) that cause you lose you job?

**Comment by DanEble** [comment] 2019-11-12 15:35
> > I just lost work because of it.
> 
> Sorry to hear that, do you mean that using Mark Text with this bug(without this feature) that cause you lose you job?

😆 No, I was editing a list in Source Code Mode and I unintentionally deleted a section of the file.  I lost just that section.  My job is safe!

**Comment by fxha** [comment] 2020-06-07 00:06
Thank you for reporting the issue. We noticed that this is a duplicate of #781. You may want to subscribe there for further updates.

**Closed by fxha** 2020-06-07 00:06 UTC
Labels: :beetle: pri/low, :unicorn: feature request, :whale: help wanted
