### ISSUE TITLE
Left side bar overflows file path and name

### ISSUE THREAD

**Issue by AsierRF** [marktext/marktext#1233] opened 2019-08-05 10:13 UTC
I noticed that if the path of the open file or the side bar are too long, they just overflow each other. See image below, the "Downloads" text is actually over the left side bar.

![image](https://user-images.githubusercontent.com/17161846/62457071-3c798200-b77a-11e9-8dc1-4f10182b852d.png)

Is this the expected behavior, or should the path text realign with the given editor area?

### Versions

- Mark Text: v15 rc3
- Operating system: Linux (AppImage)

**Comment by Jocs** [comment] 2019-08-05 10:31
>Is this the expected behavior, or should the path text realign with the given editor area?

Which do you prefer?

**Comment by AsierRF** [comment] 2019-08-05 10:46
I think the path info should be over the editor area only since it is information regarding the editor active view and nothing to do with the left side bar.

**Comment by fxha** [comment] 2019-09-29 22:12
Closing the issue because it's the expected behavior.

**Closed by fxha** 2019-09-29 22:12 UTC
