### ISSUE TITLE
0.9.25 "save" short cut not work

### ISSUE THREAD

**Issue by umi-neko** [marktext/marktext#151] opened 2018-04-14 02:31 UTC
this time I download marktext from github
it seems that File menu's "Save" not work

OS: macOS

**Comment by fxha** [comment] 2018-04-14 07:07
Do you mean the modification indicator (red dot) or that you cannot save a file. Can you please open the file with another text editor and verify it?

**Comment by Jocs** [comment] 2018-04-14 10:46
@umi-neko Can you give more information about this issue? You'd better follow the issue template!

So I can fully understand what the problem is. thanks.

**Comment by umi-neko** [comment] 2018-04-14 15:17
### Description
after modify a file, "Command + S" can not make the modification indicator disappear.

### Steps to reproduce

1. open a exist file or create a new file
2. type something in the file, now can see the modification indicator appear in title bar
3. press Command + S, the modification indicator still in title bar
4. using File->Save also can not make the red dot disappear
5. press window's close button, it will pop up a dialog "Do you want to save the changes you made to Untitled.md?" 
6. now press "Save" or "Cancel" button, the red dot disappear. I found that even press "Cancel", modification have already saved to the file. So the issue is change to "
command +S can not make the red dot disappear"

### Versions

- Mark Text: 0.9.25
- OS: macOS 10.12.6

**Comment by fxha** [comment] 2018-04-14 15:28
Thanks for you description! Duplicate of #111 and already fixed in master. It was only a UI issue.

**Closed** 2018-04-14 17:38 UTC
Labels: duplicate, fixed but not released
