### ISSUE TITLE
Images not exported to PDF or HTML 

### ISSUE THREAD

**Issue by zizusoft** [marktext/marktext#2085] opened 2020-04-30 13:15 UTC
The export of images is still broken for both PDF and HTML on v0.16.1 for Win 10. HTML export doesn't even include the src in the tag, just an ALT, ex:
`<img alt="ApocClubTestCartoonish.jpg">`

#1367

**Comment by yhancik** [comment] 2020-05-07 15:53
@zizusoft how do you originally insert the images in the the Markdown file? I use relative path starting with "./" through "Embed link" and it exports just fine (same version & OS)

**Comment by acicovic** [comment] 2020-05-17 15:55
Related: #1997

**Comment by fxha** [comment] 2020-05-21 11:42
Thank you for reporting the issue. We noticed that this is a duplicate of #1997. You may want to subscribe there for further updates.

**Closed by fxha** 2020-05-21 11:42 UTC
