### ISSUE TITLE
Do NOT popup a window if there's no change on a file

### ISSUE THREAD

**Issue by trevorwang** [marktext/marktext#1986] opened 2020-03-17 07:44 UTC
### Describe your feature request

Do NOT popup a window if there's no change on a file
### What problem does this feature solve? [optional]

There are no changes on my file but it showed me a popup window when I was trying to close it.

### Additional context [optional]
![Screen Shot 2020-03-17 at 3 41 41 PM](https://user-images.githubusercontent.com/121966/76833287-0222a800-6866-11ea-84a8-9a57198e10ba.png)

**Comment by fxha** [comment] 2020-03-17 18:29
Thank you for reporting the issue. We noticed that this is a duplicate of #1966. You may want to subscribe there for further updates.

**Closed by fxha** 2020-03-17 18:29 UTC
