### ISSUE TITLE
 File encryption

### ISSUE THREAD

**Issue by davi19** [marktext/marktext#2390] opened 2020-11-13 13:53 UTC
### File encryption
Create option to encrypt file with gpg or something in linux. Or create an option to protect the file with a password due to the support of several OS the GPG is not functional.

**Comment by fxha** [comment] 2020-11-13 14:29
Thank you for reporting the issue. We noticed that this is a duplicate of #955. You may want to subscribe there for further updates.

**Closed by fxha** 2020-11-13 14:29 UTC
