### ISSUE TITLE
CTRL+Z not working in Source Code Mode

### ISSUE THREAD

**Issue by DocBrown101** [marktext/marktext#2328] opened 2020-09-04 08:44 UTC
### Description
Pressing `CTRL+Z` doesn't do anything in Source Code Mode.

### Steps to reproduce
1. Toggle Source Code Mode on
1. Type some text
2. Delete some text
3. `CTRL+Z`

**Expected behavior:** That the deleting text gets undone

**Actual behavior:** Nothing happens

### Versions
* Mark Text: v 0.16.2
* OS: Windows 10
* QWERTZ keyboard layout

**Comment by berserkwarwolf** [comment] 2020-09-15 18:17
is this issue recognized by the development team ?

**Comment by xrat** [comment] 2020-10-14 09:09
Also, I can reproduce this on Ubuntu MATE 20.04, also Mark Text v0.16.2

**Comment by xrat** [comment] 2020-10-14 09:21
This issue might be/is likely a duplicate of https://github.com/marktext/marktext/issues/1321

**Comment by fxha** [comment] 2020-11-13 12:57
Thank you for reporting the issue. We noticed that this is a duplicate of #2188. You may want to subscribe there for further updates.

**Closed by fxha** 2020-11-13 12:57 UTC
