### ISSUE TITLE
Resources folder in the same directory as the md file that includes the image

### ISSUE THREAD

**Issue by AsierRF** [marktext/marktext#1232] opened 2019-08-05 10:08 UTC
### Describe your feature request
In v15.0.0, you added new features for images, such as a default directory for all images.

I often organize my notes by topics in directories, therefore, each directory contains several md files related to the same topic: i.e. a book, a project, etc.

I normally create a 'resources' folder in that *topic* folder that contains the images and other resources of the md files of that topic.

Therefore, I would like to request a new option for the image storage, which is, creating a 'resources' (name as an example) folder in the same directory as the md file in which the image has been injected.

This, in my humble opinion, makes it easier to organize and find resources rather than a unique folder with all your images (probably many with random names).

### What problem does this feature solve? [optional]

It helps organizing resources.

### Additional context [optional]

An example of how the directory would look like:
![image](https://user-images.githubusercontent.com/17161846/62456808-9e85b780-b779-11e9-8c76-ffc7919fa09f.png)

 
Where, **Topic1/resources** contains the images and others used by **Topic1/info.md" and **Topic2/intro.md**. Whereas, **Topic2/resources** contains files used by **Topic2/chapter1.md** and **Topic2/chapter2.md**.

**Comment by fxha** [comment] 2019-08-05 11:14
I think this is a duplicate of #549? We could add an option to save as custom unique directory or as `%filename%.assets/`.

**Comment by AsierRF** [comment] 2019-08-05 11:41
> I think this is a duplicate of #549? We could add an option to save as custom unique directory or as `%filename%.assets/`.

My apologies, I did not find the #549, I agree it is a similar functionality. However, the #549 would create an assets folder per md file.

A way to support both ideas may be to add the possibility to add paths to store images with some keywords like %filename%, %filepath%, etc.

**Comment by fxha** [comment] 2019-08-10 15:56
Thanks for reporting this issue. We noticed that this is a duplicate of #549. You may want to subscribe there for further updates.

**Closed by fxha** 2019-08-10 15:56 UTC
Labels: :unicorn: feature request
