### ISSUE TITLE
Path to image with spaces are not exported

### ISSUE THREAD

**Issue by suroh1994** [marktext/marktext#1555] opened 2019-10-29 08:21 UTC
### Description

When you add an image to your mark down file and the path to the image contains spaces, the image will be missing in the export. However, the editor will show the image correctly and not provide any errors in the editor or the exported PDF/HTML file.

- [x ] Can you reproduce the issue? 

### Steps to reproduce

1. Open a new mark down file.
2. Drag and drop an image into the editor, where the path to the image contains spaces (/home/myuser/some path with spaces/test.png). Observe that the image is shown correctly in the editor.
3. Export the file as PDF or HTML.

**Expected behavior:**

I would expect the image to be properly shown in the exported PDF/HTML file. If the image can't be shown, I would expect the editor to show me an error or a warning about the issue.

**Actual behavior:**

In the exported file (both PDFs and HTMLs) the image gets replaced with `![test.png](/home/myuser/some path with spaces/test.png)`. 

### Versions

- Mark Text: 0.15.1
- Operating system: macOS High Sierra 10.13.6

**Comment by fxha** [comment] 2019-10-29 16:50
Duplicate of #1367.

**Closed by fxha** 2019-10-29 16:50 UTC
