### ISSUE TITLE
Mark text cant open .md files edited in other editors.

### ISSUE THREAD

**Issue by AsmisAlan** [marktext/marktext#1979] opened 2020-03-15 02:42 UTC
When I tried to open old .md files creted in other editors ([document node](https://documentnode.io/) and [vscode](https://code.visualstudio.com/)) the program give me this error: 

![image](https://user-images.githubusercontent.com/14351502/76694041-771a9580-664c-11ea-8492-cb0daeb45046.png)
 
1. Create an empty .md file and edit in other editor. 
2. Try to open the file with mark text.
  
- Mark Text: v0.15.1
- Operating system: Windows 10

**Comment by fxha** [comment] 2020-03-17 18:13
Thank you for reporting the issue. We noticed that this is a duplicate of #1703. If you like, you can download the latest release candidate from Github releases to solve the issue.

**Closed by fxha** 2020-03-17 18:13 UTC
