### ISSUE TITLE
Unexpected error: Cannot destructure property `windowId` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by northgardner** [marktext/marktext#1765] opened 2019-11-27 15:30 UTC
### Description

An unexpected error occurred in the main process.

I had just downloaded the application on this machine for the first time, and opened an existing markdown file. While I continued to edit the file in Mark Test, this error kept showing.

### Stack Trace

```
TypeError: Cannot destructure property `windowId` of 'undefined' or 'null'.
    at bn._shouldIgnoreEvent (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:328872)
    at FSWatcher.<anonymous> (C:\Program Files\Mark Text\resources\app.asar\dist\electron\main.js:2:327267)
    at FSWatcher.emit (events.js:194:13)
    at FSWatcher.emitWithAll (C:\Program Files\Mark Text\resources\app.asar\node_modules\chokidar\index.js:487:8)
    at awfEmit (C:\Program Files\Mark Text\resources\app.asar\node_modules\chokidar\index.js:552:14)
    at C:\Program Files\Mark Text\resources\app.asar\node_modules\chokidar\index.js:674:9
    at FSReqCallback.oncomplete (fs.js:164:5)
```

### Version

Mark Text: v0.15.0
Operating system: Windows_NT x64 10.0.18362 (win32)

**Comment by fxha** [comment] 2019-11-27 16:52
Please update to version 0.15.1 to solve this issue. Duplicate of #1284.

@Jocs Our website download links are outdated.

**Closed by fxha** 2019-11-27 16:52 UTC
