### ISSUE TITLE
Copy-pasting a link creates unnecessary code

### ISSUE THREAD

**Issue by lrq3000** [marktext/marktext#1945] opened 2020-02-28 19:51 UTC
### Description

When creating a link on a highlighted text and copy-pasting the link, it will create unnecessary code that must be manually removed.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Type `sample-text`
2. Highlight the text and press CTRL+L to create a link
3. Copy-paste any link

**Expected behavior:**

`[sample-text](https://github.com/marktext/marktext/issues)`

**Actual behavior:**

`[sample-text]([https://github.com/marktext/marktext/issues](https://github.com/marktext/marktext/issues))`

### Versions

- Mark Text: v0.15.1
- Operating system: Windows 10 x64 with latest stable updates

**Comment by lrq3000** [comment] 2020-03-05 15:11
Note: if right-clicking and clicking on "Paste as Plain-text", then it works fine. I suggest that Mark Text should autodetect if it's inside a link markup, and if true, paste a link as plain-text by default.

**Comment by fxha** [comment] 2020-06-06 23:47
Thank you for reporting the issue. We noticed that this is a duplicate of #1882. You may want to subscribe there for further updates.

**Closed by fxha** 2020-06-06 23:47 UTC
