### ISSUE TITLE
Word-select wierd behaviour near html tag

### ISSUE THREAD

**Issue by Gurran** [marktext/marktext#1013] opened 2019-05-08 12:08 UTC
### Description

When working with text I usally use Ctrl-Shift + arrow-left/arrow-right to select by whole word.
Found instance where I get unexpected behaviour using this technique.

- [x] Can you reproduce the issue?

### Steps to reproduce

When I worked with the following string I got unexpected behaviour.

`by showing how show how works <ng-template>`

1. Place cursor after the 's' in 'works'
2. Use Ctrl-Shift + arrow-left a couple of times to select the word 'works' and some of the words to the left of 'works' 

**Expected behavior:**
At first arrow-left press the word `works` should be selected. After that, each additional arrow-left press should select an additional word. 

**Actual behavior:**

[images](https://imgur.com/a/CIFHRKd)

### Versions

OS: Windows_NT x64 10.0.17134
- Mark Text: v0.14.0
- Operating system: Windows_NT x64 10.0.17134

**Comment by fxha** [comment] 2019-05-08 14:55
@Jocs @Gurran I think this issue is already fixed on develop branch because I cannot reproduce it any more.

**Closed** 2019-06-02 20:33 UTC
Labels: 🐛 bug, 🔭 area/editor, :beetle: pri/major
