### ISSUE TITLE
export pdf with styles

### ISSUE THREAD

**Issue by qingant** [marktext/marktext#1298] opened 2019-08-27 14:11 UTC
Export  pdf with current editor styles。Now it exports pdf with no styles which looks bad and limit mark text as a book writing tool.

**Comment by fxha** [comment] 2019-09-20 20:30
> Now it exports pdf with no styles

Thank you for reporting this problem. What do you mean by this? The default style is shown below:

![mt_export_pdf_example](https://user-images.githubusercontent.com/22716132/65356727-7650fb80-dbf5-11e9-9c37-d7b9357a151a.png)


@Jocs  I think this is a duplicate of #354?

**Comment by Jocs** [comment] 2019-09-23 15:54
Closed due to duplicated with #354

**Closed by Jocs** 2019-09-23 15:54 UTC
