### ISSUE TITLE
Formatting keyboard shortcuts not working in Source Code Mode? Same w/ Markdown syntax autocompletion

### ISSUE THREAD

**Issue by HxKT6DcASYwxX2zMWkVxMQnJE3PVBG** [marktext/marktext#2024] opened 2020-03-31 06:36 UTC
Hey!

First of all, thank you for all the hard work.

It seems like that formatting keyboard shortcuts (bold, italic, etc) are not working in Source Code Mode. Same with Markdown syntax autocomletion. Any reason why?

Thanks a lot.

**Comment by fxha** [comment] 2020-06-11 22:07
Thank you for reporting the issue. We noticed that this is a duplicate of #1431. You may want to subscribe there for further updates. Please see #2188 for details.

**Closed by fxha** 2020-06-11 22:07 UTC
