### ISSUE TITLE
Support of full or large width of edit 

### ISSUE THREAD

**Issue by yodatak** [marktext/marktext#994] opened 2019-04-29 20:51 UTC
### Describe your feature request
I want to be able on large screen to use a larger edit width

### Additional context [optional]
![Capture d’écran de 2019-04-29 22-50-41](https://user-images.githubusercontent.com/704477/56926188-62372100-6ad1-11e9-9216-3a22cdbc8576.png)

**Comment by yodatak** [comment] 2019-04-29 20:53
I think this issue could help #750

**Comment by Jocs** [comment] 2019-05-01 06:23
We should add a custom editor width in a future release.

**Comment by fxha** [comment] 2019-06-02 20:35
Duplicate of #1053

**Closed by fxha** 2019-06-02 20:35 UTC
Labels: :panda_face: plugin, :unicorn: feature request
