### ISSUE TITLE
Images don't appear in exported pdf and html

### ISSUE THREAD

**Issue by Hoffenbar** [marktext/marktext#1874] opened 2020-01-18 14:05 UTC
### Steps to reproduce

1. Edit a document
2. Drag an image into the document
3. export the document
4. open the exported document with a pdf reader or browser

**Expected behavior:**

The images should appear

**Actual behavior:**

The image do not appear

**Link to an example: [optional]**

### Versions

- Mark Text: v0.15.1
- Operating system: Windows 10

**Comment by rennrennrenn** [comment] 2020-01-27 14:14
I am also facing the same problem running on macOS Catalina.
At the locations where images should appear the markdown path to the image is shown.

`![](/Users/rennrennrenn/Library/Application Support/marktext/images/image.png)`

**Comment by fxha** [comment] 2020-01-28 16:45
Thank you for reporting the issue. We noticed that this is a duplicate of #1367. You could download the latest release candidate from Github releases - otherwise replacing all path spaces with `%20` should work too.

**Closed by fxha** 2020-01-28 16:45 UTC
