### ISSUE TITLE
inserted images (and other local hyperlinks) should be stored with relative path

### ISSUE THREAD

**Issue by getreu** [marktext/marktext#2556] opened 2021-04-09 04:27 UTC
### Description

Embedded an images are stored by default with an absolute path to the image file. This leads to broken links when the document folder with its images gets moved.

### Suggested solution

Always store local links with relative path.

**Comment by ThePlenkov** [comment] 2021-04-13 18:13
Just came to request exactly same feature and saw your request

Relative folder makes no sense if markdown file still contains `C:\\Documents\Users..` path which won't be rendered on remote server.

I would consider this issue more like a bug than a fix. It definitely works not as expected

**Comment by teopost** [comment] 2021-05-05 11:55
+1

**Comment by carmolim** [comment] 2021-05-13 19:00
+1

**Comment by YalandHong** [comment] 2021-11-30 03:11
Duplicate of #2560

**Comment by fxha** [comment] 2021-12-22 16:18
You can select this behavior under via `Settings -> Image`. Select "Move to designated local folder" and activate "Prefer relative assets folder".

**Closed by fxha** 2021-12-22 16:18 UTC
