### ISSUE TITLE
Loose data or save not efficient when whiting with image at the end

### ISSUE THREAD

**Issue by filclem** [marktext/marktext#1121] opened 2019-06-24 07:50 UTC
### Description

Loose data or save not efficient when writing with image at the end 

- [ ] Can you reproduce the issue?  yes: `[x]`

### Steps to reproduce

1. [Create a new file with a text in one line and save it]
2. [Menu/Edit/Insert image, and insert an .png image]
3. [When you save ,with Menu/File/save or ctrl + s, it doesn't work
4. [In the same way, When you export in pdf format , the image doesn't appair]

### Versions

- Mark Text: 0.14.0
- Operating system: linux / mint 19.1 Tessa 64-bits

**Comment by fxha** [comment] 2019-06-28 19:52
@Jocs I mark this issue as bug, even if this issues should be fixed with the latest development version because of the image refactoring. I guess this was/(is?) an issue about not committing changes or setting the state that the file was edited after the image is inserted. This issue cannot be reproduces on the development branch but with `<v0.14.0`.

**Comment by Jocs** [comment] 2019-06-29 04:21
I'll take a look these two days.

**Comment by filclem** [comment] 2019-06-29 05:57
Well.
Thanks you.
MarkTEXT is very fun.
Have good work.

Philippe


Le ven. 28 juin 2019 à 21:52, Felix Häusler <notifications@github.com> a
écrit :

**Closed** 2019-07-04 03:08 UTC
Labels: :question: confirmation needed, 🐛 bug
