### ISSUE TITLE
Undo will not really undo the status/state

### ISSUE THREAD

**Issue by sgon00** [marktext/marktext#2144] opened 2020-05-24 16:03 UTC
Steps:

* Open a docuemnt with marktext and the document is in `non-edited mode` (saved mode) by default.
* Input a character, such as `a`. The status will become `edited mode` (not saved mode).
* Press Ctrl+Z to undo the change. 

***Expected Behavior:*** The document should go back to `non-edited mode`. (saved mode)

***Current Behavior:*** The document remains in `edited mode` (not saved mode).  and I can never change the status back to saved mode with UNDO. 

This is really an important issue in an editor. I will never know what the clean state of my document is unless I close the document and re-open it. 

Thanks a lot.

**Comment by RicardoHE97** [comment] 2020-06-03 03:14
This seems like an important issue. Can I work on this issue?

**Comment by aisbergde** [comment] 2020-06-03 15:47
@RicardoHE97 
> This seems like an important issue. Can I work on this issue?

maybe you can combine with #2148 when you work on this?

**Comment by RicardoHE97** [comment] 2020-06-03 20:32
> @RicardoHE97
> 
> > This seems like an important issue. Can I work on this issue?
> 
> maybe you can combine with #2148 when you work on this?

I will take a look into that issue as well, and see if I can solve both.

**Comment by brainchild0** [comment] 2020-06-19 05:08
As was #2148, I suggest closing this issue in favor of #2189.

**Comment by fxha** [comment] 2020-08-28 11:50
I'm closing this as duplicate of #2189, even if it's not really a duplicate but an issue with the current engine. As we drop support for the current Muya engine and adding an improved version, we don't fix any issues for this any more. BTW, this is fixed by our new engine that is currently under active development.

**Closed by fxha** 2020-08-28 11:50 UTC
