### ISSUE TITLE
Option to "Show Tab Bar" is not persisted across reruns

### ISSUE THREAD

**Issue by bubersson** [marktext/marktext#2271] opened 2020-07-03 18:25 UTC
# Description
The Tab Bar settings is not persisted across reruns of the application (at least on MacOS). 

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Open a file in MarkText (I have a default folder displayed there)
2. It show the file with a tab
3. In Mac OS top menu select and disable View > Show Tab Bar
4. Turn off the application
5. Open the application again and open a file. 
6. The file opens with a Tab Bar enabled

**Expected behavior:**

I expect the Tab Bar to not be there.

**Actual behavior:**

The Tab Bar is opened

### Versions

- Mark Text version: 0.16.2
- Operating system: Mac OS

**Comment by brainchild0** [comment] 2020-07-04 20:44
Related to, and possible duplicate of, #1274.

**Comment by fxha** [comment] 2020-11-13 12:44
Thank you for reporting the issue. This is the expected behavior and we noticed that this is a duplicate of #1274. You may want to subscribe there for further updates.

**Closed by fxha** 2020-11-13 12:44 UTC
