### ISSUE TITLE
Can not open in mac

### ISSUE THREAD

**Issue by Q-Qplus1s** [marktext/marktext#2442] opened 2020-12-21 04:08 UTC
<img width="372" alt="截屏2020-12-21 12 03 46" src="https://user-images.githubusercontent.com/50064165/102738456-25dec580-4385-11eb-82a8-99752c4f7645.png">

version: lastest version
https://github.com/marktext/marktext/releases/download/v0.16.2/marktext.dmg

system:
<img width="698" alt="截屏2020-12-21 12 08 22" src="https://user-images.githubusercontent.com/50064165/102738491-40b13a00-4385-11eb-9b82-a17885a89083.png">

**Comment by fxha** [comment] 2020-12-23 22:01
Thank you for reporting the issue. We noticed that this is a duplicate of #2435. You may want to subscribe there for further updates. The next release should run as unoptimized x86 binary on ARM based macOS.

**Closed by fxha** 2020-12-23 22:01 UTC
