### ISSUE TITLE
Export to PDF with Dark Theme is unreadable

### ISSUE THREAD

**Issue by andradei** [marktext/marktext#668] opened 2019-02-03 17:01 UTC
### Description

When Dark Theme is being used, `Export > PDF ` results in a PDF with dark background and dark grey text that is unreadable.

When Light Theme is being used, the resulting PDF also has a slightly grey background on the text as well, but is harder to see and the text is readable.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Use Dark theme (or Light theme)
2. Write and save a document
3. Save, then Export to PDF

**Expected behavior:**

PDF should have a white background and dark text like a normal document.

**Actual behavior:**

The borders of the PDF is white, but the text background is dark and the text is also dark.
With Light theme, the background is light grey instead of white like the PDF's borders.

**Link to an example: [optional]**

[Replicating the issue.pdf](https://github.com/marktext/marktext/files/2825742/Replicating.the.issue.pdf)

### Versions

- Mark Text: v 0.13.65
- Operating system: macOS Mojave 10.14.2 (18C54)

**Comment by youmoxiaozi** [comment] 2019-02-04 09:52
Hello Developer
I have the same problem.

**Comment by fxha** [comment] 2019-02-04 15:50
Duplicate of #583

**Closed by fxha** 2019-02-04 15:50 UTC
