### ISSUE TITLE
Two questions about the Table of Contents

### ISSUE THREAD

**Issue by Madoka03** [marktext/marktext#1146] opened 2019-07-10 11:40 UTC
### Questions

First of all I found the editor only a short time ago and find it excellent. Thanks for the great work of the developers. I have two questions about the Table of Contents in the sidebar.

**First question:** Is it possible to keep the structure open permanently? As soon as I switch to the editor, everything changes to its original state, so that I have to expand the tree structure again each time.

**Second question:** A nice tree structure is automatically created based on the headings. Unfortunately, a heading that is one level higher is no longer counted to the topic before.

For example:
- h1 Chapter 1
    - h2 Topic 1
    - h2 Topic 2
        - h3 Subtopic 1
        - h3 Subtopic 2
    - h2 Topic 3

In this case, he no longer counts Topic 3 as Chapter 1. Is there a way to configure it?

The following structure is displayed:
- h1 Chapter 1
    - h2 Topic 1
    - h2 Topic 2
        - h3 Subtopic 1
        - h3 Subtopic 2
- h2 Topic 3

**Comment by fxha** [comment] 2019-07-10 14:53
We changed the default behavior that the TOC entries are opened by default and the state is only changes when editing headers. The second is a duplicate of #966.

**Comment by fxha** [comment] 2019-08-10 15:40
The first question is an improvement for later. Currently the tree structure is only reloaded if you edit a heading. The second question was fixed. You may open another issue (feature request) to not change the tree view structure when editing headings.

**Closed by fxha** 2019-08-10 15:40 UTC
Labels: ❓ question
