### ISSUE TITLE
End of the Line in Windows

### ISSUE THREAD

**Issue by surferjoeit** [marktext/marktext#48] opened 2018-03-21 07:55 UTC
When creating a .txt file with marktext, end of the line is not recognized if file is opened with Windows Notepad. All text is on a single line.

- Mark Text: latest release
- OS: Windows 10

**Comment by notAlaanor** [comment] 2018-03-21 08:11
That would be the text wrapping. Line numbers would help users avoid this issue.

**Comment by Jocs** [comment] 2018-03-21 08:20
@surferjoeit how do you create a .txt file with Mark Text? Mark Text is a markdown editor, can only create .md file.

**Comment by SuperSandro2000** [comment] 2018-03-21 08:58
Under Windows you can change the extension when you save choose ``Save type as: All Files``. You would need to add some categories to that menu that contains *.md, *mdtxt, etc. like the open dialog. You can change the extension but it gets saved as .md anyway (Maybe a bug?)
![](https://i.imgur.com/RP6GnAN.png)

When opening the file with the dumb default notepad editor line breaks are missing:
![](https://i.imgur.com/Ix9MzAO.png)

Looking into Notepad++ we only have linux line breaks that the dumb MS Notepad does not understand:
![](https://i.imgur.com/JQVahYB.png)

Adding some line breaks with the dumb notepad and then showing them in Notepad++ shows that you would have to use ``CR LF`` on Windows instead of only ``LF``.
![](https://i.imgur.com/gGCyoZV.png)

**Comment by surferjoeit** [comment] 2018-03-21 10:42
I can use any software i want, for me it's not a problem. But if i exchange files with others i can't force them to use a particular editor, so in my opinion it should be better to use CR LF on Windows instead of LF only.
It's a matter of portability of the files.
Thanks for this great editor anyway!

**Comment by Jocs** [comment] 2018-03-21 11:37
@surferjoeit It a bug in windows system, I will fix it, or anyone help with this issue. thank you!

![](https://i.loli.net/2018/03/21/5ab243e0f0d18.jpg)

**Comment by surferjoeit** [comment] 2018-03-21 11:40
I can't help, sorry, i'm not a developer, i can only thank you.

**Comment by SuperSandro2000** [comment] 2018-03-21 11:47
I assume this is some electron flag soemwhere maybe but I am a Python/Ruby/C++ dev not .js/electron.

**Comment by fxha** [comment] 2018-03-21 12:01
Maybe you can add this as a feature too: `line endings` -->` { CRLF (windows), LF (else) }`. This will allow us to switch file encodings.

**Comment by Jocs** [comment] 2018-03-21 12:05
@fxha yeah, Good idea! :cry: I need a windows system, the VM is too slow, I don't want to install windows system on VM.

![](https://i.loli.net/2018/03/21/5ab24a68dfb9e.jpg)

**Comment by fxha** [comment] 2018-03-22 09:47
It looks like `src/editor/utils/exportMarkdown.js` translates html to markdown, that's means we can manipulate the line endings there. The problem is, if the user switches the line encoding we have to replace all `\n` (not followed by `\r`) to `\n\r` or `\n\r` to `\n`. Additionally, we have to convert the user input (copy & past content) to the selected line encoding. It is still unclear to me whether the parser (`src/editor/parser/marked.js`) fully supports CRLF but after a few test it seems so. Also, we need to change some new lines in parser too. Correct me if I'm wrong.

Well, this feature/bug seems like a major change - if it is done correctly. There may be other/better ways to support LF and CRLF line endings.

One quick and dirty workaround would be to replace the new lines before saving but I think it's no a good solution and not performant as well.

----

In addition, when loading a file the parser must determine which line ending is used.

**Comment by Jocs** [comment] 2018-03-22 09:57
@fxha The `platform` state is already is the store, You can determine use which line ending by this state.

**Comment by fxha** [comment] 2018-04-13 16:05
@Jocs When I thought about it, it seems there are two possible solutions:

1. If we load a file replace all `\n\r` with `\n` and save line encoding in `state`. Then we can internally work with LF encoding. When we save a file change `\n` to selected line encoding (`LF (\n)`: nothing to do; `CRLF (\n\r`): replace `\n`).
2. see post above. We have to change a lot of files.

**Comment by Jocs** [comment] 2018-04-13 16:40
@fxha Can we determine use `CRLF` or `LF` by platform?

`CRLF` for windows and `LF` for mac and Linux.

Only windows system need to do the work which you described in solution 1?

**Comment by fxha** [comment] 2018-04-13 17:00
> Can we determine use CRLF or LF by platform?

We could, but the problem is if some one using LF on Windows and vi­ce ver­sa you "destroy" the file. You only have to do the work from CRLF -> LF -> CRLF. I think it's better to let the user choose line ending and/or use file line ending.

**Comment by fxha** [comment] 2018-04-13 18:03
@SuperSandro2000 Sorry, perhaps I was not clear enough. Use CRLF default on Windows, but also analyse file endings. If we found one CRLF use CRLF (ask user later when we found mixed ending). And create a menu entry `Line Endings` where the user can select LF/CRLF.

Visual Studio had the same problems with line endings. VS git extension has still some problems.

Sure you can open LF/CRLF on every system, but sometime you have no choice (eg. in projects).

@Jocs If we allow CRLF on windows only you can't open CRLF files on macOS/Linux.

@Jocs @SuperSandro2000 What's your opinion on that?

**Comment by SuperSandro2000** [comment] 2018-04-13 19:27
Now I get it. Sounds good.

Git under windows just converts all LF to CRLF by default and back on push. Don't think we could do it that fancy.

**Comment by Jocs** [comment] 2018-04-14 01:16
@fxha some questions(opinions):

1. If user use mixed `CRLF` and `LF` how we treat this situation?
2. I agree with you 
   >use CRLF default on Windows, but also analyse file endings.
3. Do you find any other editor that user can select the 'LF/CRLF'?(is it necessary? as @SuperSandro2000 saied, maybe user do not know what `LF/CRLF` is.)

**Comment by SuperSandro2000** [comment] 2018-04-14 06:40
1. Convert them all to one or the other.
3. You can change it in Notepad++. Edit> EOL Conversion.

**Comment by fxha** [comment] 2018-04-14 07:14
> If user use mixed CRLF and LF how we treat this situation?

Maybe default to LF and CRLF on Windows (and show user notification). Or create a settings option  `line endings`.

> Do you find any other editor that user can select the 'LF/CRLF'

Atom, Typora, Sublimetext, Notepad++

> saied, maybe user do not know what LF/CRLF is.)

Yeah, that may be true

**Comment by Jocs** [comment] 2018-04-14 16:10
When user create a markdown file by Mark Text, default to LF and CRLF on Windows .
If user open an existed file, We should not change the line break, But give a notification to tell the users the recommended line break to their platform, user can change the line break in menu.

@fxha do you mean this above?

**Comment by Jocs** [comment] 2018-04-14 16:28
@fxha we can set this plan first. I'll assign it to you first, but I don't need to rush to write code because I haven't thought about how to prompt the user. Do you have any good suggestions?

**Comment by fxha** [comment] 2018-04-14 16:40
Maybe we can use the auto. update statusbar to notify or native message box/notifications to prompt the user?

**Comment by Jocs** [comment] 2018-04-14 16:54
I prefer the first solution, use the auto update status bar.

**Comment by SuperSandro2000** [comment] 2018-04-15 07:27
Most of the editors show it in the bottom right somewhere.

**Closed** 2018-05-14 16:18 UTC
Labels: bug, editor core, help wanted, windows
