### ISSUE TITLE
Settings: Open Last Session Files + Dual Panes (Source Code + Preview)

### ISSUE THREAD

**Issue by washere** [marktext/marktext#2067] opened 2020-04-24 12:27 UTC
### Describe your feature request

Settings Option:  Toggle Button:
"Re-open Last Session's Files on Launch" [X]

Remember which files (tabs) were open on exit from last session
On launch:  open them again

Very basic feature for advanced editors, similar to Auto-Save toggle, most have it.

+

"Dual Panes" option:
Source Code + Preview WYSIWYG

I see 2 threads requesting this were shot down and closed but:
One promised it and the other said no way.
Reasons given:

Will do when have time
Will never do this 
App is mainly Preview Mode
Also have Source Code view (it is separate though!)
etc etc

These reasons were contradictory.

Many many .md editors have this dual panes:
Joplin, QOwnNotes, Notable, iA Writer, Journey (two apps studio), WriteMonkey3 etc etc
+
Numerous plugins for: MS Visual Studio, MS VS Code, Atom, Sublime Text, Komodo edit, Brackets, many IDEs etc.
+
Even basic light .md apps: Furthermark, Markpad, GhostWriter, Zettlr etc. have this dual pane (.md editor + preview)

Giving contradictory reasons and simply shutting down people and threads is not right and will only hurt the app in the long run.

### What problem does this feature solve? [optional]

Basic features on many apps.

### Additional context [optional]

Good luck.

**Comment by fxha** [comment] 2020-06-11 22:04
Thanks for creating this issue. The last state is a duplicate of #988 and we do not plan to implement a dual screen as you already mentioned, there are already too many applications and Mark Text is a rich-text  editor.

**Closed by fxha** 2020-06-11 22:04 UTC
