### ISSUE TITLE
store and restore files after reopen Marktext

### ISSUE THREAD

**Issue by imyu37** [marktext/marktext#2134] opened 2020-05-23 03:13 UTC
### store and restore individual configuration
I have found the switch in *preferences.json*.
>~~Is marktext can store individual configuration and restore these configurations after reopen it, something like keeping the same sidebar and tagbar status?~~

And it's appreciated that if marktest can restore once opened files after reopen it~

![new features] (https://github.com/imyu37/IMGs/blob/master/marktext_sidebar%26tagbar.png)

**update**
It seems *"startUpAction": "lastState",* does not work for me~

**Comment by fxha** [comment] 2020-05-23 20:16
Thanks for opening the issue. We noticed that this is a duplicate of #2064.

**Closed by fxha** 2020-05-23 20:16 UTC
