### ISSUE TITLE
Add deb file for easy installation in debian/ubuntu

### ISSUE THREAD

**Issue by Donboscow** [marktext/marktext#1687] opened 2019-11-11 21:42 UTC
Please add 64-bit deb file for easy installation in debian and ubuntu. Appimage doesn't give native feels.

**Comment by fxha** [comment] 2019-11-12 17:33
Thanks for the suggestion! I guess this is a duplicate of  #1245 or do you just want a deb/rpm package without repository hosting for download? We currently only officially support the basic packages for each platform. We have also planned to [setup DEB/RPM repository](https://github.com/marktext/marktext/issues/1245) using a third-party service. Per platform/distro packages should be maintained by the community like for Arch Linux (AUR).

**Comment by adrienbeau** [comment] 2019-11-13 14:35
> Appimage doesn't give native feels.

What do you feel is wrong with the AppImage package? Have you installed `AppImageLauncher` on your system? It automatically integrates AppImage packages in your system menu when you launch them.

**Comment by fxha** [comment] 2019-11-13 19:03
> > Appimage doesn't give native feels.
> 
> What do you feel is wrong with the AppImage package? Have you installed `AppImageLauncher` on your system? It automatically integrates AppImage packages in your system menu when you launch them.

AppImage has advantages and disadvantages. One of the major downsides is that it's an compressed application that is extracted each time you start the application and so the startup time is very bad. Also in newer versions, an additional software is needed to integrate it into the system.
The main reason, why we don't provide a deb/rpm package is the update process and package distribution. Meaning, providing just such a packages don't have any advantages over other methods and we decided to provide the Flatpak package that is easy to install on all distros but also provides free updates - as far as I know unlimited bandwidth. The only reasonable way to provide deb/rpm is:

1. create a repository for each Linux distro - too much effort and also unmaintainable (by me)
2. create a repository for each Linux distro that is maintained by the community - currently
3. use a service, like in #1245, to easy maintain the packages across multiple distros - limited by 1TB/month downloads for FOSS (~14.285 downloads/month for all distros)
4. ???

I'll add deb/rpm as download option without an update service, so everyone can use these packages and manually update it. We may also provide automatically update notification is the future. I don't really like AppImage, not everyone used Flatpak and a deb/rpm integration is very time-consuming to create and maintain. That's the reason why we/I prefer the Flatpak package and the community driven packages for each distro.

**Closed** 2019-11-20 06:38 UTC
Labels: :baby_chick: blocked/need info, :lion: need discuss
