### ISSUE TITLE
Inconsistent line spacing in lists

### ISSUE THREAD

**Issue by fbruetting** [marktext/marktext#1722] opened 2019-11-18 13:49 UTC
### Description

The line spacing of lists is inconsistent and disadvantageous, as it groups items of the second indentation level too tight together. Instead, the items of the third indentation level should be grouped tighter together, and to the parent item they belong to (of the second indentation level).

// Edit: It seems that the display is dependent on empty lines in between the list items. As this effect cannot be influenced from inside Marktext, I’d propose to not respect empty lines for having a consistent display style.

- [x] Can you reproduce the issue?

### Steps to reproduce

1. Just create a list like in the image below.

**Expected behavior:**

Line spacing should either be consistent throughout all levels, or ideally shrink with each indentation level.

**Actual behavior:**

The items of the second level are (because of the small spacing) more connected to each other, than to their children. Also the items of the third indentation level have more spacing than the items of the second indentation level.

**Link to an example: [optional]**

![Bildschirmfoto von 2019-11-18 14-40-33](https://user-images.githubusercontent.com/10520767/69057220-c7247b00-0a11-11ea-972b-143afc3557bc.png)

### Versions

- Mark Text: v0.15.1
- Operating system: Fedora

**Comment by fbruetting** [comment] 2019-11-18 16:53
As you can see, the spacing even is inconsistent throughout the same document:

![Bildschirmfoto von 2019-11-18 17-52-44](https://user-images.githubusercontent.com/10520767/69072626-4b83f780-0a2c-11ea-95e8-467e8b977a2a.png)

**Comment by Jocs** [comment] 2019-11-19 04:01
Markdown can be divided into loose list and tight list by the size of the list item gap(loose list with empty line between list items), so can you adjust the loose/tight type of each level yourself? Is this caused by this?

<img width="625" alt="截屏2019-11-19下午12 00 30" src="https://user-images.githubusercontent.com/9712830/69115641-39559800-0ac4-11ea-868b-46c717468741.png">

**Comment by Jocs** [comment] 2019-11-19 04:02
@fbruetting FYI https://spec.commonmark.org/0.29/#loose

**Comment by fxha** [comment] 2019-12-20 21:24
Closing as this is the expected behavior from tight and loose list items.

**Closed by fxha** 2019-12-20 21:24 UTC
